# ALPA-Net No-Attention Transfer Fine-Tuning CV

## 1. Imports and CONFIG

In [1]:
import json
import logging
import random
import time
import traceback
import warnings
from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import torch
import torch.nn as nn
import torch.nn.functional as F
from IPython.display import display
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score, balanced_accuracy_score, roc_auc_score, roc_curve, precision_recall_curve, average_precision_score
from sklearn.model_selection import StratifiedKFold
from torch.utils.data import DataLoader, Dataset

sns.set_theme(style='whitegrid', context='notebook')
warnings.filterwarnings('ignore', message='enable_nested_tensor is True.*')
warnings.filterwarnings('ignore', category=DeprecationWarning)
PROJECT_ROOT = Path('..').resolve() if Path.cwd().name == 'notebook' else Path('.').resolve()
RUN_TIMESTAMP = datetime.now().strftime('%Y%m%d_%H%M%S')

CONFIG = {
    'SEED': 42,
    'DATASET_DIR': str(PROJECT_ROOT / 'dataset' / 'ptb_diagnostic'),
    'PRETRAIN_ROOT': str(PROJECT_ROOT / 'outputs' / '4_alpanet_pretrain_no_attention'),
    'PRETRAIN_RUN_ID': 'latest',
    'OUTPUT_BASE_DIR': str(PROJECT_ROOT / 'outputs' / '5_alpanet_finetune_no_attention'),
    'RUN_NAME': RUN_TIMESTAMP,
    'DEVICE': 'cuda' if torch.cuda.is_available() else 'cpu',
    'N_FOLDS': 5,
    'STRATEGIES': ['no_pretrain', 'frozen_backbone', 'partial_finetune', 'full_finetune'],
    'FAST_DEV_RUN': False,
    'RESUME': False,
    'num_workers': 2,
    'batch_size': 64,
    'epochs': 50,
    'learning_rate': 1e-4,
    'weight_decay': 1e-4,
    'scheduler_patience': 5,
    'early_stopping_enabled': False,
    'early_stopping_patience': 12,
    'loss_function': 'CrossEntropyLoss',
    'classification_head': 'softmax',
    'attention_prior_strength': 0.0,
    'attention_prior_learnable': False,
    'model': {
        'input_leads': 12,
        'signal_length': 65,
        'stem_channels': 32,
        'cnn_channels': 64,
        'token_dim': 128,
        'num_heads': 4,
        'cross_lead_layers': 2,
        'temporal_layers': 1,
        'transformer_ff_dim': 256,
        'dropout': 0.20,
        'temporal_segments': 20,
        'main_outputs': 4,
        'sub_outputs': 0,
    },
}

MAIN_LABELS = ['Normal', 'Anterior', 'Inferior', 'Lateral']
MAIN_LABEL_DISPLAY = ['NORM', 'AMI', 'IMI', 'LMI']
MAIN_LABEL_TO_INDEX = {label: idx for idx, label in enumerate(MAIN_LABELS)}
INDEX_TO_MAIN_LABEL = {idx: label for label, idx in MAIN_LABEL_TO_INDEX.items()}
LEAD_ORDER = ['I', 'aVL', 'II', 'III', 'aVF', 'aVR', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6']
MAIN_CLASS_LEAD_PRIORS = {
    'Normal': LEAD_ORDER,
    'Anterior': ['V1', 'V2', 'V3', 'V4'],
    'Inferior': ['II', 'III', 'aVF'],
    'Lateral': ['I', 'aVL', 'V5', 'V6'],
}

def build_main_class_prior_matrix(active_weight=0.90):
    matrix=[]; n=len(LEAD_ORDER)
    for class_name in MAIN_LABELS:
        if class_name == 'Normal':
            weights=np.ones(n,dtype=np.float32)/n
        else:
            active=MAIN_CLASS_LEAD_PRIORS[class_name]
            weights=np.full(n,(1-active_weight)/max(n-len(active),1),dtype=np.float32)
            for lead in active: weights[LEAD_ORDER.index(lead)] = active_weight/len(active)
            weights=weights/weights.sum()
        matrix.append(weights)
    return np.stack(matrix).astype(np.float32)
MAIN_CLASS_PRIOR_MATRIX = build_main_class_prior_matrix()

LABEL_MAPPING = {
    'model_name': 'ALPA-Net No-Attention Ablation',
    'task_type': 'single_label_4_class_softmax',
    'main_label_order': MAIN_LABELS,
    'main_label_display': MAIN_LABEL_DISPLAY,
    'class_to_index': MAIN_LABEL_TO_INDEX,
    'index_to_class': INDEX_TO_MAIN_LABEL,
    'head_activation_for_inference': 'softmax',
    'recommended_loss': 'CrossEntropyLoss',
}
LEAD_PRIOR_CONFIG = {
    'lead_order': LEAD_ORDER,
    'main_label_order': MAIN_LABELS,
    'main_class_lead_priors': MAIN_CLASS_LEAD_PRIORS,
    'main_class_prior_matrix': MAIN_CLASS_PRIOR_MATRIX.tolist(),
    'attention_prior_strength': CONFIG['attention_prior_strength'],
    'attention_prior_learnable': CONFIG['attention_prior_learnable'],
}
print('Device:', CONFIG['DEVICE'])
print('Dataset:', CONFIG['DATASET_DIR'])

Device: cuda
Dataset: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/dataset/ptb_diagnostic

## 2. Output Directory and Logging

In [2]:
def set_seed(seed=42):
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic=True; torch.backends.cudnn.benchmark=False
set_seed(CONFIG['SEED'])

OUTPUT_DIR = Path(CONFIG['OUTPUT_BASE_DIR']) / CONFIG['RUN_NAME']
CONFIG_DIR = OUTPUT_DIR / 'configs'; LOG_DIR = OUTPUT_DIR / 'logs'; AGG_DIR = OUTPUT_DIR / 'aggregate_results'; PLOTS_DIR = OUTPUT_DIR / 'plots'; ROOT_METRICS_DIR = OUTPUT_DIR / 'metrics'; STRATEGY_ROOT = OUTPUT_DIR / 'transfer_strategies'
for d in [CONFIG_DIR, LOG_DIR, AGG_DIR, PLOTS_DIR, ROOT_METRICS_DIR, STRATEGY_ROOT]: d.mkdir(parents=True, exist_ok=True)
for strategy in CONFIG['STRATEGIES']: (STRATEGY_ROOT / strategy).mkdir(parents=True, exist_ok=True)
with open(CONFIG_DIR/'config.json','w') as f: json.dump(CONFIG,f,indent=2)
with open(CONFIG_DIR/'label_mapping.json','w') as f: json.dump(LABEL_MAPPING,f,indent=2)
with open(CONFIG_DIR/'lead_prior_config.json','w') as f: json.dump(LEAD_PRIOR_CONFIG,f,indent=2)

def make_logger(name, train_path, error_path):
    logger=logging.getLogger(name); logger.setLevel(logging.INFO); logger.handlers.clear()
    fmt=logging.Formatter('%(asctime)s | %(levelname)s | %(message)s')
    sh=logging.StreamHandler(); sh.setFormatter(fmt)
    fh=logging.FileHandler(train_path); fh.setFormatter(fmt)
    eh=logging.FileHandler(error_path); eh.setLevel(logging.ERROR); eh.setFormatter(fmt)
    logger.addHandler(sh); logger.addHandler(fh); logger.addHandler(eh)
    return logger

global_logger = make_logger('ALPA-Net softmax transfer', LOG_DIR/'train.log', LOG_DIR/'error.log')
ROOT_OUTPUT_LOG = PROJECT_ROOT / 'output.log'
root_handler = logging.FileHandler(ROOT_OUTPUT_LOG); root_handler.setFormatter(logging.Formatter('%(asctime)s | %(levelname)s | %(message)s'))
global_logger.addHandler(root_handler)
RUN_STARTED_AT=datetime.now(); RUN_START_TIME=time.time()
global_logger.info('='*88)
global_logger.info('ALPA-Net softmax transfer CV logger')
global_logger.info('Run started at: %s', RUN_STARTED_AT.strftime('%Y-%m-%d %H:%M:%S'))
global_logger.info('Output directory: %s', OUTPUT_DIR)
global_logger.info('Transfer strategy directory: %s', STRATEGY_ROOT)
global_logger.info('Dataset directory: %s', CONFIG['DATASET_DIR'])
global_logger.info('Device: %s', CONFIG['DEVICE'])
global_logger.info('Strategies: %s', CONFIG['STRATEGIES'])
global_logger.info('='*88)

2026-06-11 20:32:27,870 | INFO | ========================================================================================

2026-06-11 20:32:27,870 | INFO | ALPA-Net softmax transfer CV logger

2026-06-11 20:32:27,870 | INFO | Run started at: 2026-06-11 20:32:27

2026-06-11 20:32:27,871 | INFO | Output directory: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227

2026-06-11 20:32:27,871 | INFO | Transfer strategy directory: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies

2026-06-11 20:32:27,871 | INFO | Dataset directory: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/dataset/ptb_diagnostic

2026-06-11 20:32:27,871 | INFO | Device: cuda

2026-06-11 20:32:27,871 | INFO | Strategies: ['no_pretrain', 'frozen_backbone', 'partial_finetune', 'full_finetune']

2026-06-11 20:32:27,872 | INFO | ========================================================================================

## 3. Load Pretrain Source

In [3]:
def load_json(path):
    with open(path) as f: return json.load(f)

REQUIRED_PRETRAIN_FILES = [
    'alpanet_full_model.pt', 'alpanet_backbone.pt', 'alpanet_heads.pt',
    'model_config.json', 'label_mapping.json', 'lead_prior_config.json',
]

def pretrain_run_is_complete(run_dir):
    transfer = Path(run_dir) / 'transfer_ready'
    return transfer.exists() and all((transfer / name).exists() for name in REQUIRED_PRETRAIN_FILES)

def timestamp_dirs(root):
    root=Path(root)
    return sorted([p for p in root.iterdir() if p.is_dir() and pretrain_run_is_complete(p)], key=lambda p:p.name)

def load_pretrain_run(root, run_id):
    root=Path(root)
    if run_id == 'latest':
        dirs=timestamp_dirs(root)
        if not dirs: raise FileNotFoundError(f'No pretrain runs found under {root}')
        run_dir=dirs[-1]
    else:
        run_dir=root/run_id
    transfer=run_dir/'transfer_ready'
    files={
        'run_dir': run_dir,
        'transfer_dir': transfer,
        'full_model': transfer/'alpanet_full_model.pt',
        'backbone': transfer/'alpanet_backbone.pt',
        'heads': transfer/'alpanet_heads.pt',
        'model_config': transfer/'model_config.json',
        'label_mapping': transfer/'label_mapping.json',
        'lead_prior_config': transfer/'lead_prior_config.json',
    }
    missing=[str(v) for k,v in files.items() if k not in {'run_dir','transfer_dir'} and not Path(v).exists()]
    if missing: raise FileNotFoundError('Missing pretrain artifacts:\n'+'\n'.join(missing))
    return files

try:
    PRETRAIN_SOURCE=load_pretrain_run(CONFIG['PRETRAIN_ROOT'], CONFIG['PRETRAIN_RUN_ID'])
    pretrain_label_mapping=load_json(PRETRAIN_SOURCE['label_mapping'])
    if pretrain_label_mapping.get('task_type') != 'single_label_4_class_softmax':
        raise ValueError(f"Pretrain task_type incompatible: {pretrain_label_mapping.get('task_type')}")
    pretrain_main_order = pretrain_label_mapping.get('main_label_order') or pretrain_label_mapping.get('main_labels')
    if pretrain_main_order != MAIN_LABELS:
        raise ValueError(f'Pretrain main label order mismatch. Expected {MAIN_LABELS}, got {pretrain_main_order}')
    with open(CONFIG_DIR/'pretrain_source.json','w') as f: json.dump({k:str(v) for k,v in PRETRAIN_SOURCE.items()},f,indent=2)
    global_logger.info('Using pretrained source: %s', PRETRAIN_SOURCE['run_dir'])
except Exception:
    global_logger.exception('Failed to load pretrain source.')
    raise

2026-06-11 20:32:27,877 | INFO | Using pretrained source: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/4_alpanet_pretrain_no_attention/20260610_230702

## 4. Data Loading and Label Mapping

In [4]:
def load_split(dataset_dir, split):
    split_dir=Path(dataset_dir)/split
    x_path=split_dir/'x_beats.npy'
    if not x_path.exists(): x_path=split_dir/'x.npy'
    x=np.load(x_path).astype(np.float32)
    csv_path=split_dir/'metadata.csv' if (split_dir/'metadata.csv').exists() else split_dir/'labels.csv'
    labels=pd.read_csv(csv_path)
    labels['source_split']=split
    return x, labels

def parse_vector_column(value):
    import ast
    if isinstance(value, np.ndarray): return value.astype(np.float32)
    if isinstance(value, list): return np.asarray(value,dtype=np.float32)
    return np.asarray(ast.literal_eval(str(value)), dtype=np.float32)

def build_class_targets(labels_df):
    labels_df=labels_df.copy().reset_index(drop=True)
    if 'main_label_name' in labels_df.columns:
        y=labels_df['main_label_name'].map(MAIN_LABEL_TO_INDEX).to_numpy(dtype=np.int64)
    elif 'main_label_vector' in labels_df.columns:
        mat=np.vstack(labels_df['main_label_vector'].map(parse_vector_column).to_numpy())
        y=np.argmax(mat,axis=1).astype(np.int64)
        labels_df['main_label_name']=[INDEX_TO_MAIN_LABEL[int(i)] for i in y]
    else:
        raise ValueError('main_label_name or main_label_vector is required')
    labels_df['class_index']=y
    return y, labels_df

DATASET_DIR=Path(CONFIG['DATASET_DIR'])
x_train, labels_train = load_split(DATASET_DIR,'train')
x_val, labels_val = load_split(DATASET_DIR,'val')
x_test, labels_test = load_split(DATASET_DIR,'test')
y_train, labels_train = build_class_targets(labels_train)
y_val, labels_val = build_class_targets(labels_val)
y_test, labels_test = build_class_targets(labels_test)

x_all=np.concatenate([x_train,x_val,x_test],axis=0)
labels_all=pd.concat([labels_train,labels_val,labels_test],ignore_index=True)
y_all=np.concatenate([y_train,y_val,y_test])
TRAINVAL_INDICES=np.arange(len(x_train)+len(x_val))
TEST_INDICES=np.arange(len(x_train)+len(x_val), len(x_all))

global_logger.info('Loaded beat data train=%s val=%s test=%s', x_train.shape, x_val.shape, x_test.shape)
for split_name, y in [('train', y_train), ('val', y_val), ('test', y_test)]:
    counts=pd.Series(y).value_counts().reindex(range(4),fill_value=0); counts.index=MAIN_LABELS
    global_logger.info('%s class distribution: %s', split_name, counts.to_dict())
    display(counts.rename(split_name).to_frame())
display(labels_all[[c for c in ['beat_id','record_id','main_label_name','class_index','source_split'] if c in labels_all.columns]].head(10))

2026-06-11 20:32:27,901 | INFO | Loaded beat data train=(1720, 65, 12) val=(224, 65, 12) test=(499, 65, 12)

2026-06-11 20:32:27,901 | INFO | train class distribution: {'Normal': 552, 'Anterior': 344, 'Inferior': 669, 'Lateral': 155}

          train
Normal      552
Anterior    344
Inferior    669
Lateral     155

2026-06-11 20:32:27,905 | INFO | val class distribution: {'Normal': 75, 'Anterior': 60, 'Inferior': 89, 'Lateral': 0}

          val
Normal     75
Anterior   60
Inferior   89
Lateral     0

2026-06-11 20:32:27,906 | INFO | test class distribution: {'Normal': 135, 'Anterior': 97, 'Inferior': 184, 'Lateral': 83}

          test
Normal     135
Anterior    97
Inferior   184
Lateral     83

          beat_id record_id main_label_name  class_index source_split
0  s0398lre_beat0  s0398lre        Inferior            2        train
1  s0398lre_beat1  s0398lre        Inferior            2        train
2  s0398lre_beat2  s0398lre        Inferior            2        train
3  s0398lre_beat3  s0398lre        Inferior            2        train
4  s0398lre_beat4  s0398lre        Inferior            2        train
5  s0398lre_beat5  s0398lre        Inferior            2        train
6  s0398lre_beat6  s0398lre        Inferior            2        train
7  s0398lre_beat7  s0398lre        Inferior            2        train
8  s0398lre_beat8  s0398lre        Inferior            2        train
9  s0398lre_beat9  s0398lre        Inferior            2        train

## 5. Dataset and DataLoader

In [5]:
class PerLeadZScore:
    def __init__(self, eps=1e-6): self.eps=eps; self.mean_=None; self.std_=None
    def fit(self,x):
        self.mean_=x.mean(axis=(0,1),keepdims=True); self.std_=np.maximum(x.std(axis=(0,1),keepdims=True), self.eps); return self
    def transform(self,x): return ((x-self.mean_)/self.std_).astype(np.float32)

mean_path=PRETRAIN_SOURCE['transfer_dir']/'normalizer_mean.npy'
std_path=PRETRAIN_SOURCE['transfer_dir']/'normalizer_std.npy'
if mean_path.exists() and std_path.exists():
    normalizer=PerLeadZScore(); normalizer.mean_=np.load(mean_path); normalizer.std_=np.load(std_path)
    global_logger.info('Loaded pretrain normalizer from transfer_ready.')
else:
    normalizer=PerLeadZScore().fit(x_all[TRAINVAL_INDICES])
    global_logger.warning('Pretrain normalizer not found; fitted from target train+val pool.')
x_all_n=normalizer.transform(x_all)

class ECGClassificationDataset(Dataset):
    def __init__(self,x,y,indices):
        self.x=torch.tensor(x[indices],dtype=torch.float32); self.y=torch.tensor(y[indices],dtype=torch.long); self.indices=np.asarray(indices)
    def __len__(self): return len(self.indices)
    def __getitem__(self,idx): return {'x':self.x[idx], 'y':self.y[idx], 'idx':int(self.indices[idx])}

def make_loaders(train_idx,val_idx,test_idx):
    tr=ECGClassificationDataset(x_all_n,y_all,train_idx); va=ECGClassificationDataset(x_all_n,y_all,val_idx); te=ECGClassificationDataset(x_all_n,y_all,test_idx)
    return (
        DataLoader(tr,batch_size=CONFIG['batch_size'],shuffle=True,num_workers=CONFIG['num_workers'],pin_memory=torch.cuda.is_available()),
        DataLoader(va,batch_size=CONFIG['batch_size'],shuffle=False,num_workers=CONFIG['num_workers'],pin_memory=torch.cuda.is_available()),
        DataLoader(te,batch_size=CONFIG['batch_size'],shuffle=False,num_workers=CONFIG['num_workers'],pin_memory=torch.cuda.is_available()),
    )

2026-06-11 20:32:27,914 | INFO | Loaded pretrain normalizer from transfer_ready.

## 6. ALPA-Net Softmax Model Definition

In [6]:
global_logger.info('ALPA-Net softmax model definition loaded.')

class SharedLeadCNNStem(nn.Module):
    def __init__(self, in_channels=1, stem_channels=32, dropout=0.1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv1d(in_channels, stem_channels, kernel_size=7, padding=3, bias=False),
            nn.BatchNorm1d(stem_channels),
            nn.GELU(),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)


class MultiScaleResidualCNNBlock(nn.Module):
    def __init__(self, channels, kernels=(3, 7, 15, 31), dropout=0.1):
        super().__init__()
        branch_channels = channels // len(kernels)
        self.branches = nn.ModuleList([
            nn.Sequential(
                nn.Conv1d(channels, branch_channels, kernel_size=k, padding=k // 2, bias=False),
                nn.BatchNorm1d(branch_channels),
                nn.GELU(),
            )
            for k in kernels
        ])
        self.project = nn.Sequential(
            nn.Conv1d(branch_channels * len(kernels), channels, kernel_size=1, bias=False),
            nn.BatchNorm1d(channels),
            nn.Dropout(dropout),
        )
        self.act = nn.GELU()

    def forward(self, x):
        out = torch.cat([branch(x) for branch in self.branches], dim=1)
        out = self.project(out)
        return self.act(out + x)


class LeadTokenBuilder(nn.Module):
    def __init__(self, in_channels, token_dim):
        super().__init__()
        self.proj = nn.Linear(in_channels, token_dim)

    def forward(self, lead_features):
        pooled = lead_features.mean(dim=-1)
        return self.proj(pooled)




class LeadTimeAttentionPooling(nn.Module):
    def __init__(self, token_dim, dropout=0.1):
        super().__init__()
        self.score = nn.Sequential(
            nn.LayerNorm(token_dim),
            nn.Linear(token_dim, token_dim // 2),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(token_dim // 2, 1),
        )

    def forward(self, tokens):
        scores = self.score(tokens).squeeze(-1)
        weights = torch.softmax(scores, dim=1)
        pooled = torch.einsum('bn,bnd->bd', weights, tokens)
        return pooled, weights


class ALPANetBackbone(nn.Module):
    def __init__(self, config):
        super().__init__()
        m = config['model']
        self.input_leads = m['input_leads']
        self.temporal_segments = m['temporal_segments']
        self.stem = SharedLeadCNNStem(1, m['stem_channels'], m['dropout'])
        self.channel_project = nn.Sequential(
            nn.Conv1d(m['stem_channels'], m['cnn_channels'], kernel_size=1, bias=False),
            nn.BatchNorm1d(m['cnn_channels']),
            nn.GELU(),
        )
        self.multi_scale = MultiScaleResidualCNNBlock(m['cnn_channels'], dropout=m['dropout'])
        self.token_builder = LeadTokenBuilder(m['cnn_channels'], m['token_dim'])
        cross_layer = nn.TransformerEncoderLayer(
            d_model=m['token_dim'], nhead=m['num_heads'], dim_feedforward=m['transformer_ff_dim'],
            dropout=m['dropout'], batch_first=True, activation='gelu', norm_first=True,
        )
        self.cross_lead_transformer = nn.TransformerEncoder(cross_layer, num_layers=m['cross_lead_layers'])
        temporal_layer = nn.TransformerEncoderLayer(
            d_model=m['token_dim'], nhead=m['num_heads'], dim_feedforward=m['transformer_ff_dim'],
            dropout=m['dropout'], batch_first=True, activation='gelu', norm_first=True,
        )
        self.temporal_transformer = nn.TransformerEncoder(temporal_layer, num_layers=m['temporal_layers'])
        self.pooling = LeadTimeAttentionPooling(m['token_dim'], dropout=m['dropout'])
        self.norm = nn.LayerNorm(m['token_dim'] * 2)

    def forward(self, x):
        b, t, l = x.shape
        x_lead = x.permute(0, 2, 1).reshape(b * l, 1, t)
        features = self.stem(x_lead)
        features = self.channel_project(features)
        features = self.multi_scale(features)
        lead_features = features.reshape(b, l, features.shape[1], features.shape[2])
        lead_tokens_raw = self.token_builder(lead_features)
        class_count = len(MAIN_LABELS)
        class_attention = lead_tokens_raw.new_full((b, class_count, l), 1.0 / float(l))
        class_context = torch.einsum('bql,bld->bqd', class_attention, lead_tokens_raw)
        lead_attention = class_attention.mean(dim=1)
        lead_tokens = self.cross_lead_transformer(lead_tokens_raw)

        segment_features = F.adaptive_avg_pool1d(features, self.temporal_segments)
        segment_features = segment_features.reshape(b, l, segment_features.shape[1], self.temporal_segments).mean(dim=1)
        temporal_tokens = segment_features.permute(0, 2, 1)
        temporal_tokens = self.temporal_transformer(self.token_builder.proj(temporal_tokens))

        lead_pooled, lead_pool_weights = self.pooling(lead_tokens)
        time_pooled, time_pool_weights = self.pooling(temporal_tokens)
        pooled_features = self.norm(torch.cat([lead_pooled, time_pooled], dim=-1))
        return {
            'pooled_features': pooled_features,
            'lead_tokens': lead_tokens,
            'temporal_tokens': temporal_tokens,
            'class_context': class_context,
            'class_attention': class_attention,
            'lead_attention': lead_attention,
            'lead_pool_weights': lead_pool_weights,
            'time_pool_weights': time_pool_weights,
        }


class ALPANet(nn.Module):
    def __init__(self, config):
        super().__init__()
        m = config['model']
        self.backbone = ALPANetBackbone(config)
        self.classification_head = nn.Sequential(
            nn.LayerNorm(m['token_dim'] * 2),
            nn.Linear(m['token_dim'] * 2, m['token_dim']),
            nn.GELU(),
            nn.Dropout(m['dropout']),
            nn.Linear(m['token_dim'], m['main_outputs']),
        )

    def forward(self, x):
        backbone_out = self.backbone(x)
        logits = self.classification_head(backbone_out['pooled_features'])
        return {
            'logits': logits,
            'probabilities': torch.softmax(logits, dim=1),
            **backbone_out,
        }


def freeze_for_transfer(model, scheme):
    for param in model.parameters():
        param.requires_grad = True
    if scheme == 'frozen_backbone':
        for param in model.backbone.parameters():
            param.requires_grad = False
    elif scheme == 'partial_finetune':
        for module in [model.backbone.stem, model.backbone.channel_project, model.backbone.multi_scale]:
            for param in module.parameters():
                param.requires_grad = False
    elif scheme in {'full_finetune', 'no_pretrain'}:
        pass
    else:
        raise ValueError(f'Unknown transfer scheme: {scheme}')


def backbone_state_dict(model):
    return model.backbone.state_dict()


def heads_state_dict(model):
    return {'classification_head': model.classification_head.state_dict()}

def build_alpanet_model():
    return ALPANet(CONFIG).to(CONFIG['DEVICE'])

global_logger.info('ALPA-Net softmax model definition completed.')

2026-06-11 20:32:27,931 | INFO | ALPA-Net softmax model definition loaded.

2026-06-11 20:32:27,932 | INFO | ALPA-Net softmax model definition completed.

## 7. Transfer Strategy Utilities

In [7]:
def load_pretrained_weights(model, strategy, logger):
    if strategy == 'no_pretrain':
        logger.info('No pretrained weights loaded.'); return model
    if strategy == 'full_finetune':
        payload=torch.load(PRETRAIN_SOURCE['full_model'], map_location=CONFIG['DEVICE'])
        model.load_state_dict(payload['model_state_dict'], strict=True)
        logger.info('Loaded pretrained full model.'); return model
    payload=torch.load(PRETRAIN_SOURCE['backbone'], map_location=CONFIG['DEVICE'])
    model.backbone.load_state_dict(payload['backbone_state_dict'], strict=True)
    logger.info('Loaded pretrained backbone.'); return model

def apply_transfer_strategy(model, strategy):
    for p in model.parameters(): p.requires_grad=True
    if strategy == 'frozen_backbone':
        for p in model.backbone.parameters(): p.requires_grad=False
    elif strategy == 'partial_finetune':
        for module in [model.backbone.stem, model.backbone.channel_project, model.backbone.multi_scale]:
            for p in module.parameters(): p.requires_grad=False
    elif strategy in {'no_pretrain','full_finetune'}:
        pass
    else: raise ValueError(strategy)
    return model

def print_trainable_parameters(model, logger):
    total=sum(p.numel() for p in model.parameters()); trainable=sum(p.numel() for p in model.parameters() if p.requires_grad)
    logger.info('Parameters trainable=%d total=%d ratio=%.4f', trainable, total, trainable/max(total,1))
    return {'trainable_params':trainable,'total_params':total,'trainable_ratio':trainable/max(total,1)}

def heads_state_dict(model): return {'classification_head': model.classification_head.state_dict()}

## 8. Metrics and Evaluation Helpers

In [8]:
def softmax_np(logits):
    logits=logits-logits.max(axis=1,keepdims=True); exp=np.exp(logits); return exp/exp.sum(axis=1,keepdims=True)

def compute_metrics(y_true, logits):
    prob=softmax_np(logits); pred=np.argmax(prob,axis=1)
    cm=confusion_matrix(y_true,pred,labels=np.arange(len(MAIN_LABELS)))
    out={
        'accuracy':float(accuracy_score(y_true,pred)),
        'balanced_accuracy':float(balanced_accuracy_score(y_true,pred)),
        'macro_f1':float(f1_score(y_true,pred,average='macro',zero_division=0)),
        'micro_f1':float(f1_score(y_true,pred,average='micro',zero_division=0)),
        'weighted_f1':float(f1_score(y_true,pred,average='weighted',zero_division=0)),
    }
    per=f1_score(y_true,pred,labels=np.arange(len(MAIN_LABELS)),average=None,zero_division=0)
    class_rows=[]; auc_values=[]
    for idx,(label,display_label,val) in enumerate(zip(MAIN_LABELS,MAIN_LABEL_DISPLAY,per)):
        tp=float(cm[idx,idx]); fn=float(cm[idx,:].sum()-cm[idx,idx]); fp=float(cm[:,idx].sum()-cm[idx,idx]); tn=float(cm.sum()-tp-fn-fp)
        sensitivity=tp/max(tp+fn,1.0); specificity=tn/max(tn+fp,1.0)
        try:
            auc_value=float(roc_auc_score((y_true==idx).astype(int), prob[:,idx])); auc_values.append(auc_value)
        except ValueError:
            auc_value=np.nan
        out[f'f1_{label}']=float(val); out[f'sensitivity_{label}']=float(sensitivity); out[f'specificity_{label}']=float(specificity); out[f'auc_{label}']=float(auc_value) if np.isfinite(auc_value) else np.nan
        class_rows.append({'label':display_label,'internal_label':label,'f1_score':float(val),'sensitivity':float(sensitivity),'specificity':float(specificity),'auc':float(auc_value) if np.isfinite(auc_value) else np.nan,'support':int((y_true==idx).sum())})
    out['macro_auc']=float(np.nanmean(auc_values)) if auc_values else np.nan
    return out, prob, pred, pd.DataFrame(class_rows)

def run_epoch(model, loader, criterion, optimizer=None):
    training=optimizer is not None; model.train(training)
    total=0; n=0; logits=[]; y=[]; idxs=[]; attn=[]
    ctx=torch.enable_grad() if training else torch.no_grad()
    with ctx:
        for b in loader:
            xb=b['x'].to(CONFIG['DEVICE']); yb=b['y'].to(CONFIG['DEVICE'])
            if training: optimizer.zero_grad(set_to_none=True)
            out=model(xb); loss=criterion(out['logits'], yb)
            if training:
                loss.backward(); torch.nn.utils.clip_grad_norm_(model.parameters(),1.0); optimizer.step()
            bs=xb.size(0); total += float(loss.detach().cpu())*bs; n+=bs
            logits.append(out['logits'].detach().cpu().numpy()); y.append(yb.detach().cpu().numpy()); idxs.append(b['idx'].detach().cpu().numpy())
            if 'class_attention' in out: attn.append(out['class_attention'].detach().cpu().numpy())
    state={'loss':total/max(n,1),'logits':np.concatenate(logits),'y_true':np.concatenate(y),'idx':np.concatenate(idxs)}
    if attn: state['class_attention']=np.concatenate(attn)
    return state

def save_cm(y_true,y_pred,labels,path_png,path_csv,title,metrics_dir=None):
    cm=confusion_matrix(y_true,y_pred,labels=np.arange(len(labels)))
    pd.DataFrame(cm,index=labels,columns=labels).to_csv(path_csv)
    fig,ax=plt.subplots(figsize=(9,8),dpi=400)
    sns.heatmap(cm,annot=True,fmt='d',cmap='Oranges',xticklabels=labels,yticklabels=labels,linewidths=1,linecolor='black',ax=ax,annot_kws={'fontsize':14})
    ax.set_xlabel('Predicted'); ax.set_ylabel('True'); ax.set_title(title,fontsize=16,weight='bold')
    fig.tight_layout(); fig.savefig(path_png,bbox_inches='tight')
    if metrics_dir is not None:
        metrics_dir=Path(metrics_dir); metrics_dir.mkdir(parents=True,exist_ok=True)
        pd.DataFrame(cm,index=labels,columns=labels).to_csv(metrics_dir/path_csv.name)
        fig.savefig(metrics_dir/path_png.name,bbox_inches='tight')
    plt.close(fig)
    return cm

def save_roc_curves(y_true, prob, output_png, output_csv, title, metrics_png=None):
    rows=[]; fig,ax=plt.subplots(figsize=(9,7),dpi=400)
    for idx,label in enumerate(MAIN_LABEL_DISPLAY):
        binary=(y_true==idx).astype(int)
        if binary.min()==binary.max():
            continue
        fpr,tpr,_=roc_curve(binary,prob[:,idx]); auc_value=roc_auc_score(binary,prob[:,idx])
        ax.plot(fpr,tpr,linewidth=2.2,label=f'{label} AUC={auc_value:.3f}')
        rows.extend([{'label':label,'fpr':float(x),'tpr':float(y),'auc':float(auc_value)} for x,y in zip(fpr,tpr)])
    ax.plot([0,1],[0,1],linestyle='--',color='black',linewidth=1.2)
    ax.set_xlabel('False Positive Rate'); ax.set_ylabel('True Positive Rate / Sensitivity'); ax.set_title(title,fontsize=16,weight='bold')
    ax.legend(fontsize=10); ax.grid(True,alpha=.25); fig.tight_layout(); fig.savefig(output_png,bbox_inches='tight')
    if metrics_png is not None:
        fig.savefig(metrics_png,bbox_inches='tight')
    plt.close(fig)
    pd.DataFrame(rows).to_csv(output_csv,index=False)


def save_pr_curves(y_true, prob, output_png, output_csv, title, metrics_png=None):
    rows=[]; fig,ax=plt.subplots(figsize=(9,7),dpi=400)
    for idx,label in enumerate(MAIN_LABEL_DISPLAY):
        binary=(y_true==idx).astype(int)
        if binary.min()==binary.max():
            continue
        precision,recall,_=precision_recall_curve(binary,prob[:,idx]); auprc_value=average_precision_score(binary,prob[:,idx])
        ax.plot(recall,precision,linewidth=2.2,label=f'{label} AUPRC={auprc_value:.3f}')
        rows.extend([{'label':label,'recall':float(r),'precision':float(p),'auprc':float(auprc_value)} for r,p in zip(recall,precision)])
    ax.set_xlabel('Recall / Sensitivity'); ax.set_ylabel('Precision'); ax.set_title(title,fontsize=16,weight='bold')
    ax.legend(fontsize=10); ax.grid(True,alpha=.25); fig.tight_layout(); fig.savefig(output_png,bbox_inches='tight')
    if metrics_png is not None:
        fig.savefig(metrics_png,bbox_inches='tight')
    plt.close(fig)
    pd.DataFrame(rows).to_csv(output_csv,index=False)

def plot_training_curves(metrics_df, output_path, metrics_output_path=None):
    fig,axes=plt.subplots(1,2,figsize=(14,5),dpi=300)
    axes[0].plot(metrics_df['epoch'],metrics_df['train_loss'],label='train'); axes[0].plot(metrics_df['epoch'],metrics_df['val_loss'],label='val'); axes[0].set_title('Loss'); axes[0].set_xlabel('Epoch'); axes[0].legend(); axes[0].grid(True,alpha=.3)
    axes[1].plot(metrics_df['epoch'],metrics_df['train_main_macro_f1'],label='train'); axes[1].plot(metrics_df['epoch'],metrics_df['val_main_macro_f1'],label='val'); axes[1].set_title('Macro F1'); axes[1].set_xlabel('Epoch'); axes[1].legend(); axes[1].grid(True,alpha=.3)
    fig.tight_layout(); fig.savefig(output_path,bbox_inches='tight')
    if metrics_output_path is not None:
        fig.savefig(metrics_output_path,bbox_inches='tight')
    plt.close(fig)

def save_predictions(path, labels_df, indices, y_true, prob, pred):
    df=labels_df.iloc[indices].copy().reset_index(drop=True)
    df['true_class_index']=y_true.astype(int); df['pred_class_index']=pred.astype(int)
    df['true_label']=[MAIN_LABELS[int(i)] for i in y_true]; df['pred_label']=[MAIN_LABELS[int(i)] for i in pred]
    for i,name in enumerate(MAIN_LABELS): df[f'prob_{name}']=prob[:,i]
    df.to_csv(path,index=False)
    return df

## 9. 5-Fold Split Preparation

In [9]:
def make_cv_splits():
    y_dom=y_all[TRAINVAL_INDICES]
    if CONFIG['FAST_DEV_RUN']:
        skf=StratifiedKFold(n_splits=CONFIG['N_FOLDS'],shuffle=True,random_state=CONFIG['SEED'])
        tr_rel,va_rel=next(skf.split(TRAINVAL_INDICES,y_dom))
        return [{'fold':1,'train_idx':TRAINVAL_INDICES[tr_rel],'val_idx':TRAINVAL_INDICES[va_rel],'test_idx':TEST_INDICES.copy()}]
    skf=StratifiedKFold(n_splits=CONFIG['N_FOLDS'],shuffle=True,random_state=CONFIG['SEED'])
    return [{'fold':i,'train_idx':TRAINVAL_INDICES[tr],'val_idx':TRAINVAL_INDICES[va],'test_idx':TEST_INDICES.copy()} for i,(tr,va) in enumerate(skf.split(TRAINVAL_INDICES,y_dom),start=1)]
CV_SPLITS=make_cv_splits()
audit=[]
for s in CV_SPLITS:
    row={'fold':s['fold'],'train_beats':len(s['train_idx']),'val_beats':len(s['val_idx']),'test_beats':len(s['test_idx'])}
    for label_idx,label in enumerate(MAIN_LABELS):
        row[f'train_{label}']=int((y_all[s['train_idx']]==label_idx).sum()); row[f'val_{label}']=int((y_all[s['val_idx']]==label_idx).sum()); row[f'test_{label}']=int((y_all[s['test_idx']]==label_idx).sum())
    audit.append(row)
cv_audit=pd.DataFrame(audit); cv_audit.to_csv(AGG_DIR/'cv_split_audit.csv',index=False); display(cv_audit)

,fold,train_beats,val_beats,test_beats,train_Normal,val_Normal,test_Normal,train_Anterior,val_Anterior,test_Anterior,train_Inferior,val_Inferior,test_Inferior,train_Lateral,val_Lateral,test_Lateral
0,1,1555,389,499,502,125,135,323,81,97,606,152,184,124,31,83
1,2,1555,389,499,502,125,135,323,81,97,606,152,184,124,31,83
2,3,1555,389,499,502,125,135,323,81,97,606,152,184,124,31,83
3,4,1555,389,499,501,126,135,323,81,97,607,151,184,124,31,83
4,5,1556,388,499,501,126,135,324,80,97,607,151,184,124,31,83

## 10. Sanity Check Before Training

In [10]:
global_logger.info('Sanity check started.')
sample_split=CV_SPLITS[0]
train_loader,val_loader,test_loader=make_loaders(sample_split['train_idx'],sample_split['val_idx'],sample_split['test_idx'])
criterion=nn.CrossEntropyLoss().to(CONFIG['DEVICE'])
for strategy in (CONFIG['STRATEGIES'][:1] if CONFIG['FAST_DEV_RUN'] else CONFIG['STRATEGIES']):
    m=build_alpanet_model(); m=load_pretrained_weights(m,strategy,global_logger); m=apply_transfer_strategy(m,strategy); print_trainable_parameters(m,global_logger)
    b=next(iter(train_loader)); out=m(b['x'].to(CONFIG['DEVICE']))
    assert out['logits'].shape == (b['x'].shape[0], 4)
    assert out['probabilities'].shape == (b['x'].shape[0], 4)
    assert out['class_attention'].shape == (b['x'].shape[0], 4, 12)
    loss=criterion(out['logits'], b['y'].to(CONFIG['DEVICE'])); loss.backward()
    global_logger.info('Sanity passed strategy=%s loss=%.4f', strategy, float(loss.detach().cpu()))
    del m

2026-06-11 20:32:27,960 | INFO | Sanity check started.

2026-06-11 20:32:28,098 | INFO | No pretrained weights loaded.

2026-06-11 20:32:28,098 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:32:28,423 | INFO | Sanity passed strategy=no_pretrain loss=1.3611

2026-06-11 20:32:28,449 | INFO | Loaded pretrained backbone.

2026-06-11 20:32:28,450 | INFO | Parameters trainable=33924 total=512933 ratio=0.0661

2026-06-11 20:32:28,520 | INFO | Sanity passed strategy=frozen_backbone loss=1.3798

2026-06-11 20:32:28,536 | INFO | Loaded pretrained backbone.

2026-06-11 20:32:28,537 | INFO | Parameters trainable=448773 total=512933 ratio=0.8749

2026-06-11 20:32:28,607 | INFO | Sanity passed strategy=partial_finetune loss=1.4087

2026-06-11 20:32:28,635 | INFO | Loaded pretrained full model.

2026-06-11 20:32:28,636 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:32:28,715 | INFO | Sanity passed strategy=full_finetune loss=0.7827

## 11. Run Strategy-First 5-Fold Training

In [11]:
def checkpoint_payload(model,optimizer,scheduler,fold,strategy,epoch,best_metric):
    return {
        'model_state_dict':model.state_dict(),
        'backbone_state_dict':model.backbone.state_dict(),
        'heads_state_dict':heads_state_dict(model),
        'optimizer_state_dict':optimizer.state_dict(),
        'scheduler_state_dict':scheduler.state_dict(),
        'strategy':strategy,
        'fold':fold,
        'epoch':epoch,
        'best_val_macro_f1':best_metric,
        'config':CONFIG,
        'pretrain_source':{k:str(v) for k,v in PRETRAIN_SOURCE.items()},
        'label_mapping':LABEL_MAPPING,
        'lead_prior_config':LEAD_PRIOR_CONFIG,
        'lead_order':LEAD_ORDER,
        'main_label_names':MAIN_LABELS,
        'main_label_display':MAIN_LABEL_DISPLAY,
        'main_class_prior_matrix':MAIN_CLASS_PRIOR_MATRIX.tolist(),
        'main_class_lead_priors':MAIN_CLASS_LEAD_PRIORS,
        'task_type':'single_label_4_class_softmax',
    }
def save_checkpoint(path,model,optimizer,scheduler,fold,strategy,epoch,best_metric):
    path.parent.mkdir(parents=True,exist_ok=True)
    torch.save(checkpoint_payload(model,optimizer,scheduler,fold,strategy,epoch,best_metric),path)

strategies = CONFIG['STRATEGIES'][:1] if CONFIG['FAST_DEV_RUN'] else CONFIG['STRATEGIES']
folds = CV_SPLITS[:1] if CONFIG['FAST_DEV_RUN'] else CV_SPLITS
all_results=[]
for strategy in strategies:
    global_logger.info('Strategy started: %s', strategy)
    for split in folds:
        fold=split['fold']; run_dir=STRATEGY_ROOT/strategy/f'fold_{fold}'
        for sub in ['checkpoints','checkpoints/per_5fold','logs','metrics','predictions','plots','configs']: (run_dir/sub).mkdir(parents=True,exist_ok=True)
        with open(run_dir/'configs'/'config.json','w') as f: json.dump({**CONFIG,'strategy':strategy,'fold':fold},f,indent=2)
        with open(run_dir/'configs'/'label_mapping.json','w') as f: json.dump(LABEL_MAPPING,f,indent=2)
        with open(run_dir/'configs'/'lead_prior_config.json','w') as f: json.dump(LEAD_PRIOR_CONFIG,f,indent=2)
        slogger=make_logger(f'ALPA-Net softmax {strategy} fold {fold}', run_dir/'logs'/'train.log', run_dir/'logs'/'error.log')
        result={'strategy':strategy,'fold':fold,'status':'FAILED','output_dir':str(run_dir)}
        try:
            fold_start=time.time(); set_seed(CONFIG['SEED']+fold)
            train_loader,val_loader,test_loader=make_loaders(split['train_idx'],split['val_idx'],split['test_idx'])
            model=build_alpanet_model(); model=load_pretrained_weights(model,strategy,slogger); model=apply_transfer_strategy(model,strategy); param_info=print_trainable_parameters(model,slogger)
            criterion=nn.CrossEntropyLoss().to(CONFIG['DEVICE'])
            optimizer=torch.optim.AdamW([p for p in model.parameters() if p.requires_grad],lr=CONFIG['learning_rate'],weight_decay=CONFIG['weight_decay'])
            scheduler=torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer,mode='max',factor=0.5,patience=CONFIG['scheduler_patience'])
            rows=[]; best_metric=-np.inf; best_val_loss=np.inf; patience=0
            epochs=2 if CONFIG['FAST_DEV_RUN'] else CONFIG['epochs']
            for epoch in range(1,epochs+1):
                t0=time.time(); tr=run_epoch(model,train_loader,criterion,optimizer); va=run_epoch(model,val_loader,criterion)
                tm,_,_,_=compute_metrics(tr['y_true'],tr['logits']); vm,_,_,_=compute_metrics(va['y_true'],va['logits'])
                scheduler.step(vm['macro_f1'])
                row={'strategy':strategy,'fold':fold,'epoch':epoch,'train_loss':tr['loss'],'val_loss':va['loss'],'train_main_macro_f1':tm['macro_f1'],'val_main_macro_f1':vm['macro_f1'],'train_accuracy':tm['accuracy'],'val_accuracy':vm['accuracy'],'train_balanced_accuracy':tm['balanced_accuracy'],'val_balanced_accuracy':vm['balanced_accuracy'],'learning_rate':optimizer.param_groups[0]['lr'],'epoch_time':time.time()-t0}
                for label in MAIN_LABELS: row[f'train_f1_{label}']=tm[f'f1_{label}']; row[f'val_f1_{label}']=vm[f'f1_{label}']
                rows.append(row); pd.DataFrame(rows).to_csv(run_dir/'metrics'/'metrics.csv',index=False)
                slogger.info('Epoch %03d/%03d train_loss=%.5f val_loss=%.5f train_macro_f1=%.4f val_macro_f1=%.4f', epoch, epochs, tr['loss'], va['loss'], tm['macro_f1'], vm['macro_f1'])
                save_checkpoint(run_dir/'checkpoints'/'last.pt',model,optimizer,scheduler,fold,strategy,epoch,best_metric)
                if vm['macro_f1'] > best_metric:
                    best_metric=vm['macro_f1']; patience=0; save_checkpoint(run_dir/'checkpoints'/'best_macro_f1.pt',model,optimizer,scheduler,fold,strategy,epoch,best_metric)
                else: patience += 1
                if va['loss'] < best_val_loss:
                    best_val_loss=va['loss']; save_checkpoint(run_dir/'checkpoints'/'best_val_loss.pt',model,optimizer,scheduler,fold,strategy,epoch,best_metric)
                if epoch >= 5 and epoch % 5 == 0:
                    periodic_path = run_dir/'checkpoints'/'per_5fold'/f'epoch_{epoch:03d}.pt'
                    save_checkpoint(periodic_path,model,optimizer,scheduler,fold,strategy,epoch,best_metric)
                    slogger.info('Saved periodic 5-epoch checkpoint: %s', periodic_path)
                if CONFIG['early_stopping_enabled'] and patience >= CONFIG['early_stopping_patience']:
                    slogger.info('Early stopping at epoch %d', epoch); break
            ckpt=torch.load(run_dir/'checkpoints'/'best_macro_f1.pt',map_location=CONFIG['DEVICE']); model.load_state_dict(ckpt['model_state_dict'])
            val_state=run_epoch(model,val_loader,criterion); test_state=run_epoch(model,test_loader,criterion)
            vm,val_prob,val_pred,val_class_metrics=compute_metrics(val_state['y_true'],val_state['logits']); testm,test_prob,test_pred,test_class_metrics=compute_metrics(test_state['y_true'],test_state['logits'])
            save_predictions(run_dir/'predictions'/'val_predictions.csv', labels_all, val_state['idx'], val_state['y_true'], val_prob, val_pred)
            save_predictions(run_dir/'predictions'/'test_predictions.csv', labels_all, test_state['idx'], test_state['y_true'], test_prob, test_pred)
            save_cm(val_state['y_true'],val_pred,MAIN_LABEL_DISPLAY,run_dir/'plots'/'val_confusion_matrix.png',run_dir/'plots'/'val_confusion_matrix.csv','Validation Confusion Matrix',metrics_dir=run_dir/'metrics')
            save_cm(test_state['y_true'],test_pred,MAIN_LABEL_DISPLAY,run_dir/'plots'/'test_confusion_matrix.png',run_dir/'plots'/'test_confusion_matrix.csv','Test Confusion Matrix',metrics_dir=run_dir/'metrics')
            save_roc_curves(val_state['y_true'],val_prob,run_dir/'plots'/'val_roc_curve.png',run_dir/'metrics'/'val_roc_curve.csv','Validation ROC Curve',metrics_png=run_dir/'metrics'/'val_roc_curve.png')
            save_roc_curves(test_state['y_true'],test_prob,run_dir/'plots'/'test_roc_curve.png',run_dir/'metrics'/'test_roc_curve.csv','Test ROC Curve',metrics_png=run_dir/'metrics'/'test_roc_curve.png')
            save_pr_curves(val_state['y_true'],val_prob,run_dir/'plots'/'val_pr_curve.png',run_dir/'metrics'/'val_pr_curve.csv','Validation PR Curve',metrics_png=run_dir/'metrics'/'val_pr_curve.png')
            save_pr_curves(test_state['y_true'],test_prob,run_dir/'plots'/'test_pr_curve.png',run_dir/'metrics'/'test_pr_curve.csv','Test PR Curve',metrics_png=run_dir/'metrics'/'test_pr_curve.png')
            plot_training_curves(pd.DataFrame(rows), run_dir/'plots'/'training_curve.png', metrics_output_path=run_dir/'metrics'/'training_curve.png')
            if 'class_attention' in test_state:
                mean_att=test_state['class_attention'].mean(axis=0); pd.DataFrame(MAIN_CLASS_PRIOR_MATRIX,index=MAIN_LABEL_DISPLAY,columns=LEAD_ORDER).to_csv(run_dir/'plots'/'initial_attention_prior_matrix.csv'); pd.DataFrame(MAIN_CLASS_PRIOR_MATRIX,index=MAIN_LABEL_DISPLAY,columns=LEAD_ORDER).to_csv(run_dir/'metrics'/'initial_attention_prior_matrix.csv'); pd.DataFrame(mean_att,index=MAIN_LABEL_DISPLAY,columns=LEAD_ORDER).to_csv(run_dir/'plots'/'lead_attention_heatmap.csv'); pd.DataFrame(mean_att,index=MAIN_LABEL_DISPLAY,columns=LEAD_ORDER).to_csv(run_dir/'metrics'/'lead_attention_heatmap.csv')
            test_f1_rows=[]
            val_f1_rows=[]
            for label,display_label in zip(MAIN_LABELS,MAIN_LABEL_DISPLAY):
                val_f1_rows.append({'split':'val','label':display_label,'internal_label':label,'f1_score':vm[f'f1_{label}']})
                test_f1_rows.append({'split':'test','label':display_label,'internal_label':label,'f1_score':testm[f'f1_{label}']})
            pd.DataFrame(test_f1_rows).to_csv(run_dir/'plots'/'test_f1_scores_by_class.csv',index=False)
            pd.DataFrame(test_f1_rows).to_csv(run_dir/'metrics'/'test_f1_scores_by_class.csv',index=False)
            val_class_metrics.insert(0,'split','val'); test_class_metrics.insert(0,'split','test')
            pd.concat([val_class_metrics,test_class_metrics],ignore_index=True).to_csv(run_dir/'metrics'/'per_class_metrics.csv',index=False)
            pd.concat([pd.DataFrame(val_f1_rows),pd.DataFrame(test_f1_rows)],ignore_index=True).to_csv(run_dir/'plots'/'f1_scores_by_class.csv',index=False)
            pd.concat([pd.DataFrame(val_f1_rows),pd.DataFrame(test_f1_rows)],ignore_index=True).to_csv(run_dir/'metrics'/'f1_scores_by_class.csv',index=False)
            pd.DataFrame([{'split':'val',**vm,'loss':val_state['loss']},{'split':'test',**testm,'loss':test_state['loss']}]).to_csv(run_dir/'metrics'/'final_metrics.csv',index=False)
            pd.DataFrame([{'split':'val',**vm,'loss':val_state['loss']},{'split':'test',**testm,'loss':test_state['loss']}]).to_csv(run_dir/'metrics'/'test_metrics.csv',index=False)
            pd.DataFrame([
                {'split':'val','macro_f1':vm['macro_f1'],'micro_f1':vm['micro_f1'],'weighted_f1':vm['weighted_f1'],'accuracy':vm['accuracy'],'loss':val_state['loss']},
                {'split':'test','macro_f1':testm['macro_f1'],'micro_f1':testm['micro_f1'],'weighted_f1':testm['weighted_f1'],'accuracy':testm['accuracy'],'loss':test_state['loss']},
            ]).to_csv(run_dir/'plots'/'f1_score_summary.csv',index=False)
            pd.DataFrame([
                {'split':'val','macro_f1':vm['macro_f1'],'micro_f1':vm['micro_f1'],'weighted_f1':vm['weighted_f1'],'balanced_accuracy':vm['balanced_accuracy'],'macro_auc':vm['macro_auc'],'accuracy':vm['accuracy'],'loss':val_state['loss']},
                {'split':'test','macro_f1':testm['macro_f1'],'micro_f1':testm['micro_f1'],'weighted_f1':testm['weighted_f1'],'balanced_accuracy':testm['balanced_accuracy'],'macro_auc':testm['macro_auc'],'accuracy':testm['accuracy'],'loss':test_state['loss']},
            ]).to_csv(run_dir/'metrics'/'f1_score_summary.csv',index=False)
            with open(run_dir/'metrics'/'test_metrics.json','w') as f: json.dump({'val':vm,'test':testm,'val_loss':val_state['loss'],'test_loss':test_state['loss']},f,indent=2)
            result={'strategy':strategy,'fold':fold,'status':'OK','error':'','train_main_macro_f1':rows[-1]['train_main_macro_f1'],'val_main_macro_f1':vm['macro_f1'],'test_main_macro_f1':testm['macro_f1'],'test_main_micro_f1':testm['micro_f1'],'test_main_weighted_f1':testm['weighted_f1'],'test_accuracy':testm['accuracy'],'test_balanced_accuracy':testm['balanced_accuracy'],'test_macro_auc':testm['macro_auc'],'test_loss':test_state['loss'],'checkpoint_path':str(run_dir/'checkpoints'/'best_macro_f1.pt'),'output_dir':str(run_dir),**param_info}
            for label,display_label in zip(MAIN_LABELS,MAIN_LABEL_DISPLAY):
                result[f'train_f1_{display_label}']=rows[-1].get(f'train_f1_{label}',np.nan)
                result[f'val_f1_{display_label}']=vm[f'f1_{label}']
                result[f'test_f1_{display_label}']=testm[f'f1_{label}']
                result[f'test_sensitivity_{display_label}']=testm[f'sensitivity_{label}']
                result[f'test_specificity_{display_label}']=testm[f'specificity_{label}']
                result[f'test_auc_{display_label}']=testm[f'auc_{label}']
            slogger.info('Fold completed strategy=%s fold=%s test_macro_f1=%.4f duration=%.1fs', strategy, fold, testm['macro_f1'], time.time()-fold_start)
        except Exception as exc:
            result.update({'status':'FAILED','error':str(exc)})
            slogger.error('FAILED strategy=%s fold=%s: %s\n%s',strategy,fold,exc,traceback.format_exc())
        all_results.append(result); pd.DataFrame(all_results).to_csv(AGG_DIR/'all_fold_metrics.csv',index=False); global_logger.info('Finished strategy=%s fold=%s status=%s',strategy,fold,result['status'])

2026-06-11 20:32:28,832 | INFO | Strategy started: no_pretrain

2026-06-11 20:32:28,841 | INFO | No pretrained weights loaded.

2026-06-11 20:32:28,842 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:32:30,220 | INFO | Epoch 001/050 train_loss=1.23166 val_loss=1.18544 train_macro_f1=0.2538 val_macro_f1=0.2142

2026-06-11 20:32:30,864 | INFO | Epoch 002/050 train_loss=1.00640 val_loss=0.85033 train_macro_f1=0.4167 val_macro_f1=0.4823

2026-06-11 20:32:31,511 | INFO | Epoch 003/050 train_loss=0.78327 val_loss=0.74485 train_macro_f1=0.5886 val_macro_f1=0.7625

2026-06-11 20:32:32,155 | INFO | Epoch 004/050 train_loss=0.68502 val_loss=0.69976 train_macro_f1=0.7301 val_macro_f1=0.7055

2026-06-11 20:32:32,790 | INFO | Epoch 005/050 train_loss=0.60788 val_loss=0.63417 train_macro_f1=0.7628 val_macro_f1=0.7671

2026-06-11 20:32:32,845 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:32:33,448 | INFO | Epoch 006/050 train_loss=0.54898 val_loss=0.45771 train_macro_f1=0.8007 val_macro_f1=0.8475

2026-06-11 20:32:34,093 | INFO | Epoch 007/050 train_loss=0.48809 val_loss=0.40666 train_macro_f1=0.8282 val_macro_f1=0.8415

2026-06-11 20:32:34,723 | INFO | Epoch 008/050 train_loss=0.39690 val_loss=0.32879 train_macro_f1=0.8869 val_macro_f1=0.8866

2026-06-11 20:32:35,371 | INFO | Epoch 009/050 train_loss=0.34031 val_loss=0.28811 train_macro_f1=0.9008 val_macro_f1=0.8899

2026-06-11 20:32:36,016 | INFO | Epoch 010/050 train_loss=0.31459 val_loss=0.25181 train_macro_f1=0.9115 val_macro_f1=0.9187

2026-06-11 20:32:36,071 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:32:36,678 | INFO | Epoch 011/050 train_loss=0.25376 val_loss=0.30968 train_macro_f1=0.9339 val_macro_f1=0.8636

2026-06-11 20:32:37,306 | INFO | Epoch 012/050 train_loss=0.24448 val_loss=0.22724 train_macro_f1=0.9318 val_macro_f1=0.9240

2026-06-11 20:32:37,953 | INFO | Epoch 013/050 train_loss=0.23700 val_loss=0.21303 train_macro_f1=0.9387 val_macro_f1=0.9131

2026-06-11 20:32:38,591 | INFO | Epoch 014/050 train_loss=0.18088 val_loss=0.16602 train_macro_f1=0.9512 val_macro_f1=0.9239

2026-06-11 20:32:39,222 | INFO | Epoch 015/050 train_loss=0.14053 val_loss=0.20573 train_macro_f1=0.9547 val_macro_f1=0.9077

2026-06-11 20:32:39,251 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:32:39,857 | INFO | Epoch 016/050 train_loss=0.12224 val_loss=0.16559 train_macro_f1=0.9707 val_macro_f1=0.9071

2026-06-11 20:32:40,493 | INFO | Epoch 017/050 train_loss=0.13252 val_loss=0.17810 train_macro_f1=0.9629 val_macro_f1=0.9043

2026-06-11 20:32:41,118 | INFO | Epoch 018/050 train_loss=0.09329 val_loss=0.10162 train_macro_f1=0.9743 val_macro_f1=0.9660

2026-06-11 20:32:41,772 | INFO | Epoch 019/050 train_loss=0.09890 val_loss=0.08910 train_macro_f1=0.9724 val_macro_f1=0.9415

2026-06-11 20:32:42,410 | INFO | Epoch 020/050 train_loss=0.08535 val_loss=0.16010 train_macro_f1=0.9733 val_macro_f1=0.9126

2026-06-11 20:32:42,439 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:32:43,049 | INFO | Epoch 021/050 train_loss=0.07250 val_loss=0.09637 train_macro_f1=0.9829 val_macro_f1=0.9485

2026-06-11 20:32:43,670 | INFO | Epoch 022/050 train_loss=0.06456 val_loss=0.08677 train_macro_f1=0.9843 val_macro_f1=0.9442

2026-06-11 20:32:44,304 | INFO | Epoch 023/050 train_loss=0.06553 val_loss=0.17544 train_macro_f1=0.9816 val_macro_f1=0.9274

2026-06-11 20:32:44,925 | INFO | Epoch 024/050 train_loss=0.07405 val_loss=0.14022 train_macro_f1=0.9779 val_macro_f1=0.9214

2026-06-11 20:32:45,547 | INFO | Epoch 025/050 train_loss=0.03471 val_loss=0.06334 train_macro_f1=0.9914 val_macro_f1=0.9659

2026-06-11 20:32:45,588 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:32:46,196 | INFO | Epoch 026/050 train_loss=0.03051 val_loss=0.03140 train_macro_f1=0.9935 val_macro_f1=0.9932

2026-06-11 20:32:46,845 | INFO | Epoch 027/050 train_loss=0.04458 val_loss=0.04157 train_macro_f1=0.9880 val_macro_f1=0.9771

2026-06-11 20:32:47,464 | INFO | Epoch 028/050 train_loss=0.04239 val_loss=0.08325 train_macro_f1=0.9889 val_macro_f1=0.9393

2026-06-11 20:32:48,081 | INFO | Epoch 029/050 train_loss=0.02635 val_loss=0.04095 train_macro_f1=0.9922 val_macro_f1=0.9794

2026-06-11 20:32:48,704 | INFO | Epoch 030/050 train_loss=0.02342 val_loss=0.05940 train_macro_f1=0.9927 val_macro_f1=0.9610

2026-06-11 20:32:48,731 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:32:49,338 | INFO | Epoch 031/050 train_loss=0.02157 val_loss=0.05482 train_macro_f1=0.9945 val_macro_f1=0.9686

2026-06-11 20:32:49,963 | INFO | Epoch 032/050 train_loss=0.01438 val_loss=0.04757 train_macro_f1=0.9971 val_macro_f1=0.9676

2026-06-11 20:32:50,583 | INFO | Epoch 033/050 train_loss=0.02060 val_loss=0.02734 train_macro_f1=0.9939 val_macro_f1=0.9908

2026-06-11 20:32:51,225 | INFO | Epoch 034/050 train_loss=0.01256 val_loss=0.04877 train_macro_f1=0.9982 val_macro_f1=0.9795

2026-06-11 20:32:51,843 | INFO | Epoch 035/050 train_loss=0.01200 val_loss=0.04925 train_macro_f1=0.9980 val_macro_f1=0.9753

2026-06-11 20:32:51,870 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:32:52,480 | INFO | Epoch 036/050 train_loss=0.01372 val_loss=0.03198 train_macro_f1=0.9968 val_macro_f1=0.9860

2026-06-11 20:32:53,102 | INFO | Epoch 037/050 train_loss=0.01582 val_loss=0.05980 train_macro_f1=0.9965 val_macro_f1=0.9510

2026-06-11 20:32:53,730 | INFO | Epoch 038/050 train_loss=0.01154 val_loss=0.03240 train_macro_f1=0.9976 val_macro_f1=0.9916

2026-06-11 20:32:54,353 | INFO | Epoch 039/050 train_loss=0.01424 val_loss=0.06228 train_macro_f1=0.9976 val_macro_f1=0.9594

2026-06-11 20:32:54,972 | INFO | Epoch 040/050 train_loss=0.01299 val_loss=0.03249 train_macro_f1=0.9971 val_macro_f1=0.9916

2026-06-11 20:32:55,000 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:32:55,614 | INFO | Epoch 041/050 train_loss=0.01292 val_loss=0.05936 train_macro_f1=0.9968 val_macro_f1=0.9692

2026-06-11 20:32:56,233 | INFO | Epoch 042/050 train_loss=0.01186 val_loss=0.03267 train_macro_f1=0.9965 val_macro_f1=0.9916

2026-06-11 20:32:56,856 | INFO | Epoch 043/050 train_loss=0.00877 val_loss=0.03198 train_macro_f1=0.9978 val_macro_f1=0.9841

2026-06-11 20:32:57,476 | INFO | Epoch 044/050 train_loss=0.01201 val_loss=0.05066 train_macro_f1=0.9970 val_macro_f1=0.9729

2026-06-11 20:32:58,094 | INFO | Epoch 045/050 train_loss=0.01081 val_loss=0.03431 train_macro_f1=0.9971 val_macro_f1=0.9841

2026-06-11 20:32:58,122 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:32:58,729 | INFO | Epoch 046/050 train_loss=0.01470 val_loss=0.04022 train_macro_f1=0.9962 val_macro_f1=0.9841

2026-06-11 20:32:59,348 | INFO | Epoch 047/050 train_loss=0.00617 val_loss=0.02544 train_macro_f1=0.9995 val_macro_f1=0.9867

2026-06-11 20:32:59,985 | INFO | Epoch 048/050 train_loss=0.00636 val_loss=0.03838 train_macro_f1=0.9991 val_macro_f1=0.9841

2026-06-11 20:33:00,611 | INFO | Epoch 049/050 train_loss=0.00566 val_loss=0.03391 train_macro_f1=0.9990 val_macro_f1=0.9841

2026-06-11 20:33:01,235 | INFO | Epoch 050/050 train_loss=0.00567 val_loss=0.04012 train_macro_f1=0.9991 val_macro_f1=0.9841

2026-06-11 20:33:01,263 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_1/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:33:05,347 | INFO | Fold completed strategy=no_pretrain fold=1 test_macro_f1=0.8746 duration=36.5s

2026-06-11 20:33:05,348 | INFO | Finished strategy=no_pretrain fold=1 status=OK

2026-06-11 20:33:05,358 | INFO | No pretrained weights loaded.

2026-06-11 20:33:05,359 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:33:05,994 | INFO | Epoch 001/050 train_loss=1.24353 val_loss=1.25946 train_macro_f1=0.2554 val_macro_f1=0.1636

2026-06-11 20:33:06,667 | INFO | Epoch 002/050 train_loss=1.04053 val_loss=1.03389 train_macro_f1=0.3761 val_macro_f1=0.4435

2026-06-11 20:33:07,349 | INFO | Epoch 003/050 train_loss=0.84773 val_loss=0.80186 train_macro_f1=0.5187 val_macro_f1=0.7604

2026-06-11 20:33:08,027 | INFO | Epoch 004/050 train_loss=0.72497 val_loss=0.73187 train_macro_f1=0.6748 val_macro_f1=0.6976

2026-06-11 20:33:08,691 | INFO | Epoch 005/050 train_loss=0.59630 val_loss=0.70715 train_macro_f1=0.7888 val_macro_f1=0.6977

2026-06-11 20:33:08,733 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:33:09,366 | INFO | Epoch 006/050 train_loss=0.48737 val_loss=0.66638 train_macro_f1=0.8497 val_macro_f1=0.7027

2026-06-11 20:33:10,033 | INFO | Epoch 007/050 train_loss=0.41886 val_loss=0.63456 train_macro_f1=0.8734 val_macro_f1=0.7399

2026-06-11 20:33:10,699 | INFO | Epoch 008/050 train_loss=0.35014 val_loss=0.49784 train_macro_f1=0.8955 val_macro_f1=0.7765

2026-06-11 20:33:11,381 | INFO | Epoch 009/050 train_loss=0.30439 val_loss=0.35566 train_macro_f1=0.9021 val_macro_f1=0.8577

2026-06-11 20:33:12,068 | INFO | Epoch 010/050 train_loss=0.24056 val_loss=0.35771 train_macro_f1=0.9293 val_macro_f1=0.8594

2026-06-11 20:33:12,111 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:33:12,783 | INFO | Epoch 011/050 train_loss=0.21695 val_loss=0.29940 train_macro_f1=0.9468 val_macro_f1=0.8783

2026-06-11 20:33:13,509 | INFO | Epoch 012/050 train_loss=0.21486 val_loss=0.29269 train_macro_f1=0.9411 val_macro_f1=0.8698

2026-06-11 20:33:14,188 | INFO | Epoch 013/050 train_loss=0.16592 val_loss=0.24289 train_macro_f1=0.9575 val_macro_f1=0.8841

2026-06-11 20:33:14,923 | INFO | Epoch 014/050 train_loss=0.16404 val_loss=0.20856 train_macro_f1=0.9534 val_macro_f1=0.9005

2026-06-11 20:33:15,648 | INFO | Epoch 015/050 train_loss=0.13553 val_loss=0.18260 train_macro_f1=0.9671 val_macro_f1=0.9236

2026-06-11 20:33:15,705 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:33:16,349 | INFO | Epoch 016/050 train_loss=0.13644 val_loss=0.18474 train_macro_f1=0.9652 val_macro_f1=0.9353

2026-06-11 20:33:17,021 | INFO | Epoch 017/050 train_loss=0.11206 val_loss=0.11208 train_macro_f1=0.9711 val_macro_f1=0.9607

2026-06-11 20:33:17,708 | INFO | Epoch 018/050 train_loss=0.10007 val_loss=0.15402 train_macro_f1=0.9718 val_macro_f1=0.9515

2026-06-11 20:33:18,411 | INFO | Epoch 019/050 train_loss=0.08318 val_loss=0.13602 train_macro_f1=0.9771 val_macro_f1=0.9469

2026-06-11 20:33:19,068 | INFO | Epoch 020/050 train_loss=0.08323 val_loss=0.11286 train_macro_f1=0.9840 val_macro_f1=0.9625

2026-06-11 20:33:19,111 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:33:19,769 | INFO | Epoch 021/050 train_loss=0.07347 val_loss=0.05685 train_macro_f1=0.9806 val_macro_f1=0.9721

2026-06-11 20:33:20,457 | INFO | Epoch 022/050 train_loss=0.04854 val_loss=0.06044 train_macro_f1=0.9884 val_macro_f1=0.9739

2026-06-11 20:33:21,119 | INFO | Epoch 023/050 train_loss=0.06684 val_loss=0.07939 train_macro_f1=0.9817 val_macro_f1=0.9796

2026-06-11 20:33:21,806 | INFO | Epoch 024/050 train_loss=0.07052 val_loss=0.11570 train_macro_f1=0.9809 val_macro_f1=0.9623

2026-06-11 20:33:22,458 | INFO | Epoch 025/050 train_loss=0.05713 val_loss=0.09499 train_macro_f1=0.9865 val_macro_f1=0.9747

2026-06-11 20:33:22,486 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:33:23,170 | INFO | Epoch 026/050 train_loss=0.04628 val_loss=0.05986 train_macro_f1=0.9872 val_macro_f1=0.9624

2026-06-11 20:33:23,851 | INFO | Epoch 027/050 train_loss=0.04017 val_loss=0.04210 train_macro_f1=0.9858 val_macro_f1=0.9880

2026-06-11 20:33:24,529 | INFO | Epoch 028/050 train_loss=0.02697 val_loss=0.03942 train_macro_f1=0.9943 val_macro_f1=0.9862

2026-06-11 20:33:25,201 | INFO | Epoch 029/050 train_loss=0.04239 val_loss=0.04900 train_macro_f1=0.9884 val_macro_f1=0.9678

2026-06-11 20:33:25,863 | INFO | Epoch 030/050 train_loss=0.03864 val_loss=0.13830 train_macro_f1=0.9910 val_macro_f1=0.9494

2026-06-11 20:33:25,891 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:33:26,538 | INFO | Epoch 031/050 train_loss=0.02735 val_loss=0.02050 train_macro_f1=0.9928 val_macro_f1=0.9910

2026-06-11 20:33:27,230 | INFO | Epoch 032/050 train_loss=0.02745 val_loss=0.13133 train_macro_f1=0.9953 val_macro_f1=0.9402

2026-06-11 20:33:27,884 | INFO | Epoch 033/050 train_loss=0.02591 val_loss=0.03120 train_macro_f1=0.9936 val_macro_f1=0.9910

2026-06-11 20:33:28,552 | INFO | Epoch 034/050 train_loss=0.03841 val_loss=0.01416 train_macro_f1=0.9875 val_macro_f1=0.9976

2026-06-11 20:33:29,233 | INFO | Epoch 035/050 train_loss=0.03976 val_loss=0.10275 train_macro_f1=0.9910 val_macro_f1=0.9696

2026-06-11 20:33:29,262 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:33:29,920 | INFO | Epoch 036/050 train_loss=0.05566 val_loss=0.01293 train_macro_f1=0.9849 val_macro_f1=0.9928

2026-06-11 20:33:30,627 | INFO | Epoch 037/050 train_loss=0.04417 val_loss=0.20217 train_macro_f1=0.9894 val_macro_f1=0.9050

2026-06-11 20:33:31,327 | INFO | Epoch 038/050 train_loss=0.01470 val_loss=0.01944 train_macro_f1=0.9938 val_macro_f1=0.9958

2026-06-11 20:33:32,031 | INFO | Epoch 039/050 train_loss=0.03032 val_loss=0.04808 train_macro_f1=0.9885 val_macro_f1=0.9766

2026-06-11 20:33:32,717 | INFO | Epoch 040/050 train_loss=0.00856 val_loss=0.02349 train_macro_f1=0.9975 val_macro_f1=0.9880

2026-06-11 20:33:32,746 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:33:33,423 | INFO | Epoch 041/050 train_loss=0.00933 val_loss=0.02542 train_macro_f1=0.9979 val_macro_f1=0.9880

2026-06-11 20:33:34,113 | INFO | Epoch 042/050 train_loss=0.00551 val_loss=0.02724 train_macro_f1=0.9985 val_macro_f1=0.9809

2026-06-11 20:33:34,761 | INFO | Epoch 043/050 train_loss=0.00721 val_loss=0.02420 train_macro_f1=0.9982 val_macro_f1=0.9880

2026-06-11 20:33:35,411 | INFO | Epoch 044/050 train_loss=0.01189 val_loss=0.01650 train_macro_f1=0.9968 val_macro_f1=0.9904

2026-06-11 20:33:36,064 | INFO | Epoch 045/050 train_loss=0.00201 val_loss=0.02681 train_macro_f1=1.0000 val_macro_f1=0.9903

2026-06-11 20:33:36,093 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:33:36,729 | INFO | Epoch 046/050 train_loss=0.00762 val_loss=0.02402 train_macro_f1=0.9982 val_macro_f1=0.9927

2026-06-11 20:33:37,385 | INFO | Epoch 047/050 train_loss=0.00700 val_loss=0.02931 train_macro_f1=0.9990 val_macro_f1=0.9832

2026-06-11 20:33:38,035 | INFO | Epoch 048/050 train_loss=0.00175 val_loss=0.02165 train_macro_f1=0.9995 val_macro_f1=0.9880

2026-06-11 20:33:38,734 | INFO | Epoch 049/050 train_loss=0.00379 val_loss=0.01880 train_macro_f1=0.9990 val_macro_f1=0.9952

2026-06-11 20:33:39,425 | INFO | Epoch 050/050 train_loss=0.00635 val_loss=0.02367 train_macro_f1=0.9982 val_macro_f1=0.9856

2026-06-11 20:33:39,457 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_2/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:33:43,725 | INFO | Fold completed strategy=no_pretrain fold=2 test_macro_f1=0.7574 duration=38.4s

2026-06-11 20:33:43,726 | INFO | Finished strategy=no_pretrain fold=2 status=OK

2026-06-11 20:33:43,737 | INFO | No pretrained weights loaded.

2026-06-11 20:33:43,738 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:33:44,421 | INFO | Epoch 001/050 train_loss=1.23653 val_loss=1.17975 train_macro_f1=0.2663 val_macro_f1=0.2077

2026-06-11 20:33:45,120 | INFO | Epoch 002/050 train_loss=0.96976 val_loss=0.91074 train_macro_f1=0.5072 val_macro_f1=0.6273

2026-06-11 20:33:45,837 | INFO | Epoch 003/050 train_loss=0.74735 val_loss=0.68357 train_macro_f1=0.7183 val_macro_f1=0.7631

2026-06-11 20:33:46,544 | INFO | Epoch 004/050 train_loss=0.63187 val_loss=0.69942 train_macro_f1=0.7806 val_macro_f1=0.7050

2026-06-11 20:33:47,223 | INFO | Epoch 005/050 train_loss=0.56149 val_loss=0.58129 train_macro_f1=0.7888 val_macro_f1=0.7325

2026-06-11 20:33:47,268 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:33:47,934 | INFO | Epoch 006/050 train_loss=0.49377 val_loss=0.44634 train_macro_f1=0.8332 val_macro_f1=0.8377

2026-06-11 20:33:48,668 | INFO | Epoch 007/050 train_loss=0.40296 val_loss=0.38176 train_macro_f1=0.8813 val_macro_f1=0.8268

2026-06-11 20:33:49,366 | INFO | Epoch 008/050 train_loss=0.31870 val_loss=0.36385 train_macro_f1=0.9101 val_macro_f1=0.8276

2026-06-11 20:33:50,105 | INFO | Epoch 009/050 train_loss=0.27853 val_loss=0.33942 train_macro_f1=0.9260 val_macro_f1=0.8510

2026-06-11 20:33:50,848 | INFO | Epoch 010/050 train_loss=0.22453 val_loss=0.21859 train_macro_f1=0.9503 val_macro_f1=0.9081

2026-06-11 20:33:50,906 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:33:51,600 | INFO | Epoch 011/050 train_loss=0.18502 val_loss=0.21894 train_macro_f1=0.9453 val_macro_f1=0.9041

2026-06-11 20:33:52,296 | INFO | Epoch 012/050 train_loss=0.16621 val_loss=0.29256 train_macro_f1=0.9544 val_macro_f1=0.8908

2026-06-11 20:33:52,968 | INFO | Epoch 013/050 train_loss=0.16165 val_loss=0.22374 train_macro_f1=0.9523 val_macro_f1=0.9032

2026-06-11 20:33:53,649 | INFO | Epoch 014/050 train_loss=0.13599 val_loss=0.27425 train_macro_f1=0.9617 val_macro_f1=0.9041

2026-06-11 20:33:54,343 | INFO | Epoch 015/050 train_loss=0.12405 val_loss=0.28177 train_macro_f1=0.9660 val_macro_f1=0.8955

2026-06-11 20:33:54,371 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:33:55,035 | INFO | Epoch 016/050 train_loss=0.10543 val_loss=0.21358 train_macro_f1=0.9761 val_macro_f1=0.9158

2026-06-11 20:33:55,746 | INFO | Epoch 017/050 train_loss=0.09470 val_loss=0.17983 train_macro_f1=0.9745 val_macro_f1=0.9291

2026-06-11 20:33:56,448 | INFO | Epoch 018/050 train_loss=0.08448 val_loss=0.06131 train_macro_f1=0.9789 val_macro_f1=0.9725

2026-06-11 20:33:57,158 | INFO | Epoch 019/050 train_loss=0.06638 val_loss=0.13238 train_macro_f1=0.9813 val_macro_f1=0.9334

2026-06-11 20:33:57,836 | INFO | Epoch 020/050 train_loss=0.07290 val_loss=0.14905 train_macro_f1=0.9800 val_macro_f1=0.9404

2026-06-11 20:33:57,864 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:33:58,537 | INFO | Epoch 021/050 train_loss=0.08302 val_loss=0.25484 train_macro_f1=0.9791 val_macro_f1=0.9188

2026-06-11 20:33:59,241 | INFO | Epoch 022/050 train_loss=0.05687 val_loss=0.11657 train_macro_f1=0.9871 val_macro_f1=0.9524

2026-06-11 20:33:59,952 | INFO | Epoch 023/050 train_loss=0.06936 val_loss=0.10383 train_macro_f1=0.9809 val_macro_f1=0.9501

2026-06-11 20:34:00,632 | INFO | Epoch 024/050 train_loss=0.07627 val_loss=0.06662 train_macro_f1=0.9795 val_macro_f1=0.9673

2026-06-11 20:34:01,316 | INFO | Epoch 025/050 train_loss=0.05395 val_loss=0.07912 train_macro_f1=0.9866 val_macro_f1=0.9620

2026-06-11 20:34:01,345 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:34:02,009 | INFO | Epoch 026/050 train_loss=0.02641 val_loss=0.09865 train_macro_f1=0.9945 val_macro_f1=0.9544

2026-06-11 20:34:02,689 | INFO | Epoch 027/050 train_loss=0.02859 val_loss=0.04626 train_macro_f1=0.9927 val_macro_f1=0.9766

2026-06-11 20:34:03,403 | INFO | Epoch 028/050 train_loss=0.02288 val_loss=0.05570 train_macro_f1=0.9952 val_macro_f1=0.9683

2026-06-11 20:34:04,116 | INFO | Epoch 029/050 train_loss=0.02734 val_loss=0.02514 train_macro_f1=0.9929 val_macro_f1=0.9908

2026-06-11 20:34:04,833 | INFO | Epoch 030/050 train_loss=0.02376 val_loss=0.08840 train_macro_f1=0.9937 val_macro_f1=0.9559

2026-06-11 20:34:04,861 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:34:05,559 | INFO | Epoch 031/050 train_loss=0.02542 val_loss=0.02599 train_macro_f1=0.9958 val_macro_f1=0.9910

2026-06-11 20:34:06,261 | INFO | Epoch 032/050 train_loss=0.01772 val_loss=0.05471 train_macro_f1=0.9967 val_macro_f1=0.9701

2026-06-11 20:34:06,985 | INFO | Epoch 033/050 train_loss=0.01604 val_loss=0.04785 train_macro_f1=0.9961 val_macro_f1=0.9694

2026-06-11 20:34:07,682 | INFO | Epoch 034/050 train_loss=0.03017 val_loss=0.03096 train_macro_f1=0.9943 val_macro_f1=0.9831

2026-06-11 20:34:08,363 | INFO | Epoch 035/050 train_loss=0.02036 val_loss=0.09033 train_macro_f1=0.9937 val_macro_f1=0.9608

2026-06-11 20:34:08,392 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:34:09,053 | INFO | Epoch 036/050 train_loss=0.01535 val_loss=0.01587 train_macro_f1=0.9970 val_macro_f1=0.9976

2026-06-11 20:34:09,770 | INFO | Epoch 037/050 train_loss=0.01847 val_loss=0.07142 train_macro_f1=0.9939 val_macro_f1=0.9619

2026-06-11 20:34:10,448 | INFO | Epoch 038/050 train_loss=0.02136 val_loss=0.07536 train_macro_f1=0.9946 val_macro_f1=0.9619

2026-06-11 20:34:11,124 | INFO | Epoch 039/050 train_loss=0.01750 val_loss=0.00485 train_macro_f1=0.9959 val_macro_f1=1.0000

2026-06-11 20:34:11,873 | INFO | Epoch 040/050 train_loss=0.01349 val_loss=0.06132 train_macro_f1=0.9971 val_macro_f1=0.9676

2026-06-11 20:34:11,901 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:34:12,604 | INFO | Epoch 041/050 train_loss=0.01524 val_loss=0.01878 train_macro_f1=0.9954 val_macro_f1=0.9958

2026-06-11 20:34:13,333 | INFO | Epoch 042/050 train_loss=0.01701 val_loss=0.02714 train_macro_f1=0.9968 val_macro_f1=0.9860

2026-06-11 20:34:14,043 | INFO | Epoch 043/050 train_loss=0.00846 val_loss=0.01566 train_macro_f1=0.9977 val_macro_f1=0.9958

2026-06-11 20:34:14,722 | INFO | Epoch 044/050 train_loss=0.00715 val_loss=0.03629 train_macro_f1=0.9991 val_macro_f1=0.9681

2026-06-11 20:34:15,422 | INFO | Epoch 045/050 train_loss=0.01363 val_loss=0.04047 train_macro_f1=0.9955 val_macro_f1=0.9835

2026-06-11 20:34:15,452 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:34:16,120 | INFO | Epoch 046/050 train_loss=0.00909 val_loss=0.03140 train_macro_f1=0.9980 val_macro_f1=0.9794

2026-06-11 20:34:16,801 | INFO | Epoch 047/050 train_loss=0.01048 val_loss=0.04888 train_macro_f1=0.9982 val_macro_f1=0.9660

2026-06-11 20:34:17,490 | INFO | Epoch 048/050 train_loss=0.00420 val_loss=0.02782 train_macro_f1=0.9986 val_macro_f1=0.9723

2026-06-11 20:34:18,189 | INFO | Epoch 049/050 train_loss=0.00563 val_loss=0.05930 train_macro_f1=0.9986 val_macro_f1=0.9721

2026-06-11 20:34:18,924 | INFO | Epoch 050/050 train_loss=0.00891 val_loss=0.01762 train_macro_f1=0.9983 val_macro_f1=0.9908

2026-06-11 20:34:18,953 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_3/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:34:23,101 | INFO | Fold completed strategy=no_pretrain fold=3 test_macro_f1=0.8856 duration=39.4s

2026-06-11 20:34:23,103 | INFO | Finished strategy=no_pretrain fold=3 status=OK

2026-06-11 20:34:23,113 | INFO | No pretrained weights loaded.

2026-06-11 20:34:23,114 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:34:23,813 | INFO | Epoch 001/050 train_loss=1.20686 val_loss=1.36944 train_macro_f1=0.2594 val_macro_f1=0.1499

2026-06-11 20:34:24,536 | INFO | Epoch 002/050 train_loss=0.95869 val_loss=1.11578 train_macro_f1=0.4663 val_macro_f1=0.5147

2026-06-11 20:34:25,257 | INFO | Epoch 003/050 train_loss=0.71671 val_loss=0.84359 train_macro_f1=0.6814 val_macro_f1=0.6893

2026-06-11 20:34:25,972 | INFO | Epoch 004/050 train_loss=0.60206 val_loss=0.72762 train_macro_f1=0.7920 val_macro_f1=0.7230

2026-06-11 20:34:26,708 | INFO | Epoch 005/050 train_loss=0.50653 val_loss=0.55666 train_macro_f1=0.8362 val_macro_f1=0.7827

2026-06-11 20:34:26,763 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:34:27,444 | INFO | Epoch 006/050 train_loss=0.41794 val_loss=0.63750 train_macro_f1=0.8796 val_macro_f1=0.7463

2026-06-11 20:34:28,128 | INFO | Epoch 007/050 train_loss=0.36042 val_loss=0.50688 train_macro_f1=0.9081 val_macro_f1=0.7862

2026-06-11 20:34:28,857 | INFO | Epoch 008/050 train_loss=0.34041 val_loss=0.53053 train_macro_f1=0.9029 val_macro_f1=0.7946

2026-06-11 20:34:29,561 | INFO | Epoch 009/050 train_loss=0.26268 val_loss=0.38375 train_macro_f1=0.9190 val_macro_f1=0.8479

2026-06-11 20:34:30,291 | INFO | Epoch 010/050 train_loss=0.26339 val_loss=0.25696 train_macro_f1=0.9221 val_macro_f1=0.9072

2026-06-11 20:34:30,345 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:34:31,031 | INFO | Epoch 011/050 train_loss=0.22700 val_loss=0.23285 train_macro_f1=0.9301 val_macro_f1=0.9145

2026-06-11 20:34:31,748 | INFO | Epoch 012/050 train_loss=0.19074 val_loss=0.23962 train_macro_f1=0.9470 val_macro_f1=0.9094

2026-06-11 20:34:32,436 | INFO | Epoch 013/050 train_loss=0.19914 val_loss=0.24647 train_macro_f1=0.9388 val_macro_f1=0.9002

2026-06-11 20:34:33,133 | INFO | Epoch 014/050 train_loss=0.16385 val_loss=0.29766 train_macro_f1=0.9506 val_macro_f1=0.8800

2026-06-11 20:34:33,817 | INFO | Epoch 015/050 train_loss=0.12897 val_loss=0.23536 train_macro_f1=0.9638 val_macro_f1=0.9038

2026-06-11 20:34:33,846 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:34:34,515 | INFO | Epoch 016/050 train_loss=0.13138 val_loss=0.12842 train_macro_f1=0.9601 val_macro_f1=0.9432

2026-06-11 20:34:35,238 | INFO | Epoch 017/050 train_loss=0.11394 val_loss=0.10534 train_macro_f1=0.9706 val_macro_f1=0.9574

2026-06-11 20:34:36,003 | INFO | Epoch 018/050 train_loss=0.17244 val_loss=0.14673 train_macro_f1=0.9581 val_macro_f1=0.9286

2026-06-11 20:34:36,705 | INFO | Epoch 019/050 train_loss=0.11120 val_loss=0.11542 train_macro_f1=0.9682 val_macro_f1=0.9513

2026-06-11 20:34:37,406 | INFO | Epoch 020/050 train_loss=0.09882 val_loss=0.08902 train_macro_f1=0.9718 val_macro_f1=0.9623

2026-06-11 20:34:37,464 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:34:38,153 | INFO | Epoch 021/050 train_loss=0.06621 val_loss=0.20215 train_macro_f1=0.9826 val_macro_f1=0.9129

2026-06-11 20:34:38,855 | INFO | Epoch 022/050 train_loss=0.08773 val_loss=0.07347 train_macro_f1=0.9717 val_macro_f1=0.9700

2026-06-11 20:34:39,578 | INFO | Epoch 023/050 train_loss=0.07761 val_loss=0.19305 train_macro_f1=0.9761 val_macro_f1=0.9383

2026-06-11 20:34:40,269 | INFO | Epoch 024/050 train_loss=0.06678 val_loss=0.13052 train_macro_f1=0.9791 val_macro_f1=0.9565

2026-06-11 20:34:40,975 | INFO | Epoch 025/050 train_loss=0.06384 val_loss=0.06675 train_macro_f1=0.9824 val_macro_f1=0.9872

2026-06-11 20:34:41,031 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:34:41,737 | INFO | Epoch 026/050 train_loss=0.05103 val_loss=0.07573 train_macro_f1=0.9857 val_macro_f1=0.9795

2026-06-11 20:34:42,449 | INFO | Epoch 027/050 train_loss=0.03862 val_loss=0.10983 train_macro_f1=0.9918 val_macro_f1=0.9691

2026-06-11 20:34:43,142 | INFO | Epoch 028/050 train_loss=0.04075 val_loss=0.19861 train_macro_f1=0.9901 val_macro_f1=0.9566

2026-06-11 20:34:43,825 | INFO | Epoch 029/050 train_loss=0.04383 val_loss=0.07049 train_macro_f1=0.9870 val_macro_f1=0.9873

2026-06-11 20:34:44,528 | INFO | Epoch 030/050 train_loss=0.04639 val_loss=0.07193 train_macro_f1=0.9856 val_macro_f1=0.9809

2026-06-11 20:34:44,556 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:34:45,267 | INFO | Epoch 031/050 train_loss=0.03451 val_loss=0.02671 train_macro_f1=0.9901 val_macro_f1=0.9958

2026-06-11 20:34:46,024 | INFO | Epoch 032/050 train_loss=0.01998 val_loss=0.04462 train_macro_f1=0.9961 val_macro_f1=0.9901

2026-06-11 20:34:46,730 | INFO | Epoch 033/050 train_loss=0.05274 val_loss=0.02015 train_macro_f1=0.9889 val_macro_f1=0.9945

2026-06-11 20:34:47,448 | INFO | Epoch 034/050 train_loss=0.03617 val_loss=0.03715 train_macro_f1=0.9878 val_macro_f1=0.9909

2026-06-11 20:34:48,153 | INFO | Epoch 035/050 train_loss=0.01199 val_loss=0.03219 train_macro_f1=0.9966 val_macro_f1=0.9927

2026-06-11 20:34:48,188 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:34:48,883 | INFO | Epoch 036/050 train_loss=0.02843 val_loss=0.04371 train_macro_f1=0.9918 val_macro_f1=0.9927

2026-06-11 20:34:49,622 | INFO | Epoch 037/050 train_loss=0.01979 val_loss=0.03312 train_macro_f1=0.9961 val_macro_f1=0.9908

2026-06-11 20:34:50,327 | INFO | Epoch 038/050 train_loss=0.01997 val_loss=0.03246 train_macro_f1=0.9954 val_macro_f1=0.9890

2026-06-11 20:34:51,045 | INFO | Epoch 039/050 train_loss=0.00799 val_loss=0.06693 train_macro_f1=0.9990 val_macro_f1=0.9835

2026-06-11 20:34:51,772 | INFO | Epoch 040/050 train_loss=0.01549 val_loss=0.04041 train_macro_f1=0.9968 val_macro_f1=0.9909

2026-06-11 20:34:51,802 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:34:52,495 | INFO | Epoch 041/050 train_loss=0.01341 val_loss=0.08437 train_macro_f1=0.9964 val_macro_f1=0.9817

2026-06-11 20:34:53,220 | INFO | Epoch 042/050 train_loss=0.01181 val_loss=0.01222 train_macro_f1=0.9952 val_macro_f1=0.9964

2026-06-11 20:34:53,951 | INFO | Epoch 043/050 train_loss=0.01646 val_loss=0.01147 train_macro_f1=0.9959 val_macro_f1=0.9932

2026-06-11 20:34:54,650 | INFO | Epoch 044/050 train_loss=0.00809 val_loss=0.02455 train_macro_f1=0.9980 val_macro_f1=0.9945

2026-06-11 20:34:55,341 | INFO | Epoch 045/050 train_loss=0.00197 val_loss=0.02134 train_macro_f1=1.0000 val_macro_f1=0.9964

2026-06-11 20:34:55,369 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:34:56,040 | INFO | Epoch 046/050 train_loss=0.00337 val_loss=0.01090 train_macro_f1=0.9995 val_macro_f1=0.9982

2026-06-11 20:34:56,764 | INFO | Epoch 047/050 train_loss=0.00352 val_loss=0.02081 train_macro_f1=0.9984 val_macro_f1=0.9964

2026-06-11 20:34:57,508 | INFO | Epoch 048/050 train_loss=0.00388 val_loss=0.02589 train_macro_f1=0.9995 val_macro_f1=0.9945

2026-06-11 20:34:58,214 | INFO | Epoch 049/050 train_loss=0.00900 val_loss=0.02118 train_macro_f1=0.9974 val_macro_f1=0.9964

2026-06-11 20:34:58,970 | INFO | Epoch 050/050 train_loss=0.00368 val_loss=0.03173 train_macro_f1=0.9988 val_macro_f1=0.9945

2026-06-11 20:34:58,999 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_4/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:35:03,215 | INFO | Fold completed strategy=no_pretrain fold=4 test_macro_f1=0.8937 duration=40.1s

2026-06-11 20:35:03,217 | INFO | Finished strategy=no_pretrain fold=4 status=OK

2026-06-11 20:35:03,228 | INFO | No pretrained weights loaded.

2026-06-11 20:35:03,229 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:35:04,019 | INFO | Epoch 001/050 train_loss=1.22951 val_loss=1.24492 train_macro_f1=0.2561 val_macro_f1=0.1702

2026-06-11 20:35:04,782 | INFO | Epoch 002/050 train_loss=0.99631 val_loss=0.85674 train_macro_f1=0.4110 val_macro_f1=0.7388

2026-06-11 20:35:05,547 | INFO | Epoch 003/050 train_loss=0.75461 val_loss=0.72503 train_macro_f1=0.6298 val_macro_f1=0.7297

2026-06-11 20:35:06,298 | INFO | Epoch 004/050 train_loss=0.62331 val_loss=0.59853 train_macro_f1=0.7718 val_macro_f1=0.7391

2026-06-11 20:35:07,064 | INFO | Epoch 005/050 train_loss=0.53343 val_loss=0.58083 train_macro_f1=0.8258 val_macro_f1=0.7357

2026-06-11 20:35:07,107 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:35:07,855 | INFO | Epoch 006/050 train_loss=0.44464 val_loss=0.60400 train_macro_f1=0.8663 val_macro_f1=0.7360

2026-06-11 20:35:08,609 | INFO | Epoch 007/050 train_loss=0.39876 val_loss=0.63076 train_macro_f1=0.8748 val_macro_f1=0.7130

2026-06-11 20:35:09,361 | INFO | Epoch 008/050 train_loss=0.32957 val_loss=0.53021 train_macro_f1=0.9028 val_macro_f1=0.7913

2026-06-11 20:35:10,145 | INFO | Epoch 009/050 train_loss=0.28779 val_loss=0.45860 train_macro_f1=0.9146 val_macro_f1=0.8195

2026-06-11 20:35:10,956 | INFO | Epoch 010/050 train_loss=0.23399 val_loss=0.29434 train_macro_f1=0.9384 val_macro_f1=0.8702

2026-06-11 20:35:11,011 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:35:11,747 | INFO | Epoch 011/050 train_loss=0.20921 val_loss=0.47993 train_macro_f1=0.9417 val_macro_f1=0.8062

2026-06-11 20:35:12,517 | INFO | Epoch 012/050 train_loss=0.18309 val_loss=0.51478 train_macro_f1=0.9494 val_macro_f1=0.8206

2026-06-11 20:35:13,247 | INFO | Epoch 013/050 train_loss=0.17668 val_loss=0.37681 train_macro_f1=0.9564 val_macro_f1=0.8471

2026-06-11 20:35:13,977 | INFO | Epoch 014/050 train_loss=0.15598 val_loss=0.33982 train_macro_f1=0.9560 val_macro_f1=0.8942

2026-06-11 20:35:14,730 | INFO | Epoch 015/050 train_loss=0.14937 val_loss=0.28328 train_macro_f1=0.9594 val_macro_f1=0.8983

2026-06-11 20:35:14,786 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:35:15,533 | INFO | Epoch 016/050 train_loss=0.14249 val_loss=0.36412 train_macro_f1=0.9582 val_macro_f1=0.9066

2026-06-11 20:35:16,320 | INFO | Epoch 017/050 train_loss=0.12458 val_loss=0.44529 train_macro_f1=0.9687 val_macro_f1=0.8643

2026-06-11 20:35:17,059 | INFO | Epoch 018/050 train_loss=0.09772 val_loss=0.34488 train_macro_f1=0.9720 val_macro_f1=0.9020

2026-06-11 20:35:17,829 | INFO | Epoch 019/050 train_loss=0.07851 val_loss=0.25995 train_macro_f1=0.9774 val_macro_f1=0.9032

2026-06-11 20:35:18,598 | INFO | Epoch 020/050 train_loss=0.09711 val_loss=0.13682 train_macro_f1=0.9717 val_macro_f1=0.9600

2026-06-11 20:35:18,653 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:35:19,357 | INFO | Epoch 021/050 train_loss=0.10605 val_loss=0.10875 train_macro_f1=0.9692 val_macro_f1=0.9654

2026-06-11 20:35:20,116 | INFO | Epoch 022/050 train_loss=0.06573 val_loss=0.17748 train_macro_f1=0.9788 val_macro_f1=0.9430

2026-06-11 20:35:20,846 | INFO | Epoch 023/050 train_loss=0.06659 val_loss=0.20991 train_macro_f1=0.9839 val_macro_f1=0.9373

2026-06-11 20:35:21,574 | INFO | Epoch 024/050 train_loss=0.05714 val_loss=0.08073 train_macro_f1=0.9883 val_macro_f1=0.9835

2026-06-11 20:35:22,336 | INFO | Epoch 025/050 train_loss=0.05423 val_loss=0.18357 train_macro_f1=0.9848 val_macro_f1=0.9269

2026-06-11 20:35:22,364 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:35:23,072 | INFO | Epoch 026/050 train_loss=0.04460 val_loss=0.16703 train_macro_f1=0.9892 val_macro_f1=0.9625

2026-06-11 20:35:23,797 | INFO | Epoch 027/050 train_loss=0.04591 val_loss=0.44747 train_macro_f1=0.9907 val_macro_f1=0.8924

2026-06-11 20:35:24,524 | INFO | Epoch 028/050 train_loss=0.05188 val_loss=0.30072 train_macro_f1=0.9843 val_macro_f1=0.9162

2026-06-11 20:35:25,248 | INFO | Epoch 029/050 train_loss=0.02849 val_loss=0.07282 train_macro_f1=0.9947 val_macro_f1=0.9867

2026-06-11 20:35:25,995 | INFO | Epoch 030/050 train_loss=0.07103 val_loss=0.17450 train_macro_f1=0.9787 val_macro_f1=0.9616

2026-06-11 20:35:26,024 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:35:26,762 | INFO | Epoch 031/050 train_loss=0.03122 val_loss=0.24493 train_macro_f1=0.9945 val_macro_f1=0.9507

2026-06-11 20:35:27,491 | INFO | Epoch 032/050 train_loss=0.03206 val_loss=0.11436 train_macro_f1=0.9932 val_macro_f1=0.9775

2026-06-11 20:35:28,250 | INFO | Epoch 033/050 train_loss=0.04250 val_loss=0.16688 train_macro_f1=0.9901 val_macro_f1=0.9682

2026-06-11 20:35:28,978 | INFO | Epoch 034/050 train_loss=0.03776 val_loss=0.19350 train_macro_f1=0.9892 val_macro_f1=0.9568

2026-06-11 20:35:29,709 | INFO | Epoch 035/050 train_loss=0.02845 val_loss=0.09316 train_macro_f1=0.9949 val_macro_f1=0.9788

2026-06-11 20:35:29,738 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:35:30,466 | INFO | Epoch 036/050 train_loss=0.02802 val_loss=0.06373 train_macro_f1=0.9938 val_macro_f1=0.9909

2026-06-11 20:35:31,262 | INFO | Epoch 037/050 train_loss=0.01352 val_loss=0.09016 train_macro_f1=0.9961 val_macro_f1=0.9801

2026-06-11 20:35:32,028 | INFO | Epoch 038/050 train_loss=0.01580 val_loss=0.12401 train_macro_f1=0.9967 val_macro_f1=0.9756

2026-06-11 20:35:32,746 | INFO | Epoch 039/050 train_loss=0.01388 val_loss=0.09765 train_macro_f1=0.9953 val_macro_f1=0.9872

2026-06-11 20:35:33,474 | INFO | Epoch 040/050 train_loss=0.00833 val_loss=0.08681 train_macro_f1=0.9986 val_macro_f1=0.9825

2026-06-11 20:35:33,503 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:35:34,221 | INFO | Epoch 041/050 train_loss=0.01245 val_loss=0.19221 train_macro_f1=0.9968 val_macro_f1=0.9705

2026-06-11 20:35:34,968 | INFO | Epoch 042/050 train_loss=0.01163 val_loss=0.16908 train_macro_f1=0.9977 val_macro_f1=0.9761

2026-06-11 20:35:35,730 | INFO | Epoch 043/050 train_loss=0.00938 val_loss=0.06245 train_macro_f1=0.9991 val_macro_f1=0.9909

2026-06-11 20:35:36,485 | INFO | Epoch 044/050 train_loss=0.00742 val_loss=0.13595 train_macro_f1=0.9982 val_macro_f1=0.9700

2026-06-11 20:35:37,256 | INFO | Epoch 045/050 train_loss=0.00500 val_loss=0.12197 train_macro_f1=0.9991 val_macro_f1=0.9793

2026-06-11 20:35:37,286 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:35:37,990 | INFO | Epoch 046/050 train_loss=0.00698 val_loss=0.09622 train_macro_f1=0.9977 val_macro_f1=0.9767

2026-06-11 20:35:38,705 | INFO | Epoch 047/050 train_loss=0.00305 val_loss=0.11174 train_macro_f1=0.9979 val_macro_f1=0.9793

2026-06-11 20:35:39,448 | INFO | Epoch 048/050 train_loss=0.00507 val_loss=0.13732 train_macro_f1=0.9990 val_macro_f1=0.9705

2026-06-11 20:35:40,180 | INFO | Epoch 049/050 train_loss=0.00605 val_loss=0.08584 train_macro_f1=0.9991 val_macro_f1=0.9835

2026-06-11 20:35:40,907 | INFO | Epoch 050/050 train_loss=0.00513 val_loss=0.11531 train_macro_f1=0.9986 val_macro_f1=0.9835

2026-06-11 20:35:40,937 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/no_pretrain/fold_5/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:35:45,329 | INFO | Fold completed strategy=no_pretrain fold=5 test_macro_f1=0.9211 duration=42.1s

2026-06-11 20:35:45,331 | INFO | Finished strategy=no_pretrain fold=5 status=OK

2026-06-11 20:35:45,331 | INFO | Strategy started: frozen_backbone

2026-06-11 20:35:45,350 | INFO | Loaded pretrained backbone.

2026-06-11 20:35:45,351 | INFO | Parameters trainable=33924 total=512933 ratio=0.0661

2026-06-11 20:35:45,907 | INFO | Epoch 001/050 train_loss=1.16106 val_loss=0.95139 train_macro_f1=0.5016 val_macro_f1=0.5917

2026-06-11 20:35:46,471 | INFO | Epoch 002/050 train_loss=0.88195 val_loss=0.71524 train_macro_f1=0.5956 val_macro_f1=0.6236

2026-06-11 20:35:47,048 | INFO | Epoch 003/050 train_loss=0.70211 val_loss=0.58622 train_macro_f1=0.6357 val_macro_f1=0.6665

2026-06-11 20:35:47,605 | INFO | Epoch 004/050 train_loss=0.60665 val_loss=0.51508 train_macro_f1=0.7448 val_macro_f1=0.7258

2026-06-11 20:35:48,167 | INFO | Epoch 005/050 train_loss=0.54532 val_loss=0.46332 train_macro_f1=0.7982 val_macro_f1=0.7680

2026-06-11 20:35:48,194 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:35:48,745 | INFO | Epoch 006/050 train_loss=0.52366 val_loss=0.43131 train_macro_f1=0.8169 val_macro_f1=0.8249

2026-06-11 20:35:49,291 | INFO | Epoch 007/050 train_loss=0.48880 val_loss=0.40617 train_macro_f1=0.8418 val_macro_f1=0.8516

2026-06-11 20:35:49,854 | INFO | Epoch 008/050 train_loss=0.44635 val_loss=0.37893 train_macro_f1=0.8531 val_macro_f1=0.8320

2026-06-11 20:35:50,429 | INFO | Epoch 009/050 train_loss=0.44127 val_loss=0.36189 train_macro_f1=0.8412 val_macro_f1=0.8652

2026-06-11 20:35:50,994 | INFO | Epoch 010/050 train_loss=0.41941 val_loss=0.34169 train_macro_f1=0.8602 val_macro_f1=0.8741

2026-06-11 20:35:51,022 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:35:51,550 | INFO | Epoch 011/050 train_loss=0.40805 val_loss=0.32936 train_macro_f1=0.8576 val_macro_f1=0.8803

2026-06-11 20:35:52,115 | INFO | Epoch 012/050 train_loss=0.38376 val_loss=0.31321 train_macro_f1=0.8708 val_macro_f1=0.8972

2026-06-11 20:35:52,689 | INFO | Epoch 013/050 train_loss=0.36942 val_loss=0.30494 train_macro_f1=0.8840 val_macro_f1=0.8951

2026-06-11 20:35:53,247 | INFO | Epoch 014/050 train_loss=0.36240 val_loss=0.29157 train_macro_f1=0.8780 val_macro_f1=0.9008

2026-06-11 20:35:53,814 | INFO | Epoch 015/050 train_loss=0.34008 val_loss=0.28426 train_macro_f1=0.8891 val_macro_f1=0.9000

2026-06-11 20:35:53,834 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:35:54,369 | INFO | Epoch 016/050 train_loss=0.33794 val_loss=0.28358 train_macro_f1=0.8865 val_macro_f1=0.9125

2026-06-11 20:35:54,928 | INFO | Epoch 017/050 train_loss=0.32952 val_loss=0.26446 train_macro_f1=0.8903 val_macro_f1=0.9223

2026-06-11 20:35:55,500 | INFO | Epoch 018/050 train_loss=0.31573 val_loss=0.25579 train_macro_f1=0.9032 val_macro_f1=0.9157

2026-06-11 20:35:56,080 | INFO | Epoch 019/050 train_loss=0.31309 val_loss=0.25017 train_macro_f1=0.8949 val_macro_f1=0.9329

2026-06-11 20:35:56,672 | INFO | Epoch 020/050 train_loss=0.29830 val_loss=0.25107 train_macro_f1=0.9021 val_macro_f1=0.9185

2026-06-11 20:35:56,689 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:35:57,252 | INFO | Epoch 021/050 train_loss=0.30443 val_loss=0.23028 train_macro_f1=0.8980 val_macro_f1=0.9337

2026-06-11 20:35:57,804 | INFO | Epoch 022/050 train_loss=0.28389 val_loss=0.23232 train_macro_f1=0.8967 val_macro_f1=0.9430

2026-06-11 20:35:58,375 | INFO | Epoch 023/050 train_loss=0.28047 val_loss=0.22777 train_macro_f1=0.9044 val_macro_f1=0.9473

2026-06-11 20:35:58,960 | INFO | Epoch 024/050 train_loss=0.28031 val_loss=0.22158 train_macro_f1=0.9200 val_macro_f1=0.9370

2026-06-11 20:35:59,541 | INFO | Epoch 025/050 train_loss=0.27025 val_loss=0.20791 train_macro_f1=0.9142 val_macro_f1=0.9373

2026-06-11 20:35:59,564 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:36:00,109 | INFO | Epoch 026/050 train_loss=0.27133 val_loss=0.20706 train_macro_f1=0.9097 val_macro_f1=0.9509

2026-06-11 20:36:00,663 | INFO | Epoch 027/050 train_loss=0.26533 val_loss=0.20086 train_macro_f1=0.9080 val_macro_f1=0.9552

2026-06-11 20:36:01,245 | INFO | Epoch 028/050 train_loss=0.25873 val_loss=0.19839 train_macro_f1=0.9125 val_macro_f1=0.9491

2026-06-11 20:36:01,797 | INFO | Epoch 029/050 train_loss=0.23913 val_loss=0.19703 train_macro_f1=0.9251 val_macro_f1=0.9440

2026-06-11 20:36:02,347 | INFO | Epoch 030/050 train_loss=0.24928 val_loss=0.19154 train_macro_f1=0.9191 val_macro_f1=0.9514

2026-06-11 20:36:02,367 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:36:02,898 | INFO | Epoch 031/050 train_loss=0.24062 val_loss=0.17946 train_macro_f1=0.9176 val_macro_f1=0.9603

2026-06-11 20:36:03,467 | INFO | Epoch 032/050 train_loss=0.24498 val_loss=0.17654 train_macro_f1=0.9149 val_macro_f1=0.9621

2026-06-11 20:36:04,047 | INFO | Epoch 033/050 train_loss=0.23746 val_loss=0.16878 train_macro_f1=0.9227 val_macro_f1=0.9694

2026-06-11 20:36:04,610 | INFO | Epoch 034/050 train_loss=0.22003 val_loss=0.16912 train_macro_f1=0.9306 val_macro_f1=0.9613

2026-06-11 20:36:05,156 | INFO | Epoch 035/050 train_loss=0.22750 val_loss=0.16843 train_macro_f1=0.9280 val_macro_f1=0.9621

2026-06-11 20:36:05,180 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:36:05,746 | INFO | Epoch 036/050 train_loss=0.20158 val_loss=0.16493 train_macro_f1=0.9418 val_macro_f1=0.9613

2026-06-11 20:36:06,314 | INFO | Epoch 037/050 train_loss=0.21918 val_loss=0.16780 train_macro_f1=0.9300 val_macro_f1=0.9547

2026-06-11 20:36:06,888 | INFO | Epoch 038/050 train_loss=0.21655 val_loss=0.15932 train_macro_f1=0.9282 val_macro_f1=0.9639

2026-06-11 20:36:07,451 | INFO | Epoch 039/050 train_loss=0.21951 val_loss=0.15579 train_macro_f1=0.9303 val_macro_f1=0.9655

2026-06-11 20:36:08,006 | INFO | Epoch 040/050 train_loss=0.21883 val_loss=0.15259 train_macro_f1=0.9313 val_macro_f1=0.9717

2026-06-11 20:36:08,037 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:36:08,592 | INFO | Epoch 041/050 train_loss=0.19785 val_loss=0.14998 train_macro_f1=0.9408 val_macro_f1=0.9681

2026-06-11 20:36:09,136 | INFO | Epoch 042/050 train_loss=0.21072 val_loss=0.14751 train_macro_f1=0.9419 val_macro_f1=0.9676

2026-06-11 20:36:09,684 | INFO | Epoch 043/050 train_loss=0.20874 val_loss=0.14819 train_macro_f1=0.9359 val_macro_f1=0.9621

2026-06-11 20:36:10,217 | INFO | Epoch 044/050 train_loss=0.19316 val_loss=0.14984 train_macro_f1=0.9470 val_macro_f1=0.9637

2026-06-11 20:36:10,758 | INFO | Epoch 045/050 train_loss=0.19089 val_loss=0.14328 train_macro_f1=0.9370 val_macro_f1=0.9717

2026-06-11 20:36:10,779 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:36:11,309 | INFO | Epoch 046/050 train_loss=0.20138 val_loss=0.14956 train_macro_f1=0.9310 val_macro_f1=0.9626

2026-06-11 20:36:11,850 | INFO | Epoch 047/050 train_loss=0.18855 val_loss=0.14438 train_macro_f1=0.9401 val_macro_f1=0.9644

2026-06-11 20:36:12,396 | INFO | Epoch 048/050 train_loss=0.19212 val_loss=0.14452 train_macro_f1=0.9488 val_macro_f1=0.9644

2026-06-11 20:36:12,943 | INFO | Epoch 049/050 train_loss=0.19854 val_loss=0.14366 train_macro_f1=0.9447 val_macro_f1=0.9681

2026-06-11 20:36:13,492 | INFO | Epoch 050/050 train_loss=0.19086 val_loss=0.14798 train_macro_f1=0.9429 val_macro_f1=0.9644

2026-06-11 20:36:13,506 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_1/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:36:17,700 | INFO | Fold completed strategy=frozen_backbone fold=1 test_macro_f1=0.6618 duration=32.4s

2026-06-11 20:36:17,702 | INFO | Finished strategy=frozen_backbone fold=1 status=OK

2026-06-11 20:36:17,722 | INFO | Loaded pretrained backbone.

2026-06-11 20:36:17,723 | INFO | Parameters trainable=33924 total=512933 ratio=0.0661

2026-06-11 20:36:18,308 | INFO | Epoch 001/050 train_loss=1.21875 val_loss=0.96502 train_macro_f1=0.4499 val_macro_f1=0.7495

2026-06-11 20:36:18,897 | INFO | Epoch 002/050 train_loss=0.90451 val_loss=0.72503 train_macro_f1=0.7221 val_macro_f1=0.7185

2026-06-11 20:36:19,482 | INFO | Epoch 003/050 train_loss=0.71974 val_loss=0.58689 train_macro_f1=0.7421 val_macro_f1=0.7471

2026-06-11 20:36:20,054 | INFO | Epoch 004/050 train_loss=0.61145 val_loss=0.51015 train_macro_f1=0.7760 val_macro_f1=0.8260

2026-06-11 20:36:20,641 | INFO | Epoch 005/050 train_loss=0.55678 val_loss=0.46188 train_macro_f1=0.7954 val_macro_f1=0.8534

2026-06-11 20:36:20,668 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:36:21,236 | INFO | Epoch 006/050 train_loss=0.51484 val_loss=0.42987 train_macro_f1=0.8047 val_macro_f1=0.8716

2026-06-11 20:36:21,851 | INFO | Epoch 007/050 train_loss=0.48615 val_loss=0.40549 train_macro_f1=0.8281 val_macro_f1=0.8782

2026-06-11 20:36:22,432 | INFO | Epoch 008/050 train_loss=0.45935 val_loss=0.38650 train_macro_f1=0.8403 val_macro_f1=0.8856

2026-06-11 20:36:23,028 | INFO | Epoch 009/050 train_loss=0.43397 val_loss=0.36713 train_macro_f1=0.8424 val_macro_f1=0.8832

2026-06-11 20:36:23,592 | INFO | Epoch 010/050 train_loss=0.41373 val_loss=0.35233 train_macro_f1=0.8523 val_macro_f1=0.8809

2026-06-11 20:36:23,613 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:36:24,175 | INFO | Epoch 011/050 train_loss=0.40043 val_loss=0.33986 train_macro_f1=0.8544 val_macro_f1=0.8884

2026-06-11 20:36:24,783 | INFO | Epoch 012/050 train_loss=0.37290 val_loss=0.32846 train_macro_f1=0.8775 val_macro_f1=0.8901

2026-06-11 20:36:25,372 | INFO | Epoch 013/050 train_loss=0.37668 val_loss=0.31717 train_macro_f1=0.8705 val_macro_f1=0.8912

2026-06-11 20:36:25,970 | INFO | Epoch 014/050 train_loss=0.35733 val_loss=0.30702 train_macro_f1=0.8762 val_macro_f1=0.9041

2026-06-11 20:36:26,547 | INFO | Epoch 015/050 train_loss=0.35926 val_loss=0.29977 train_macro_f1=0.8837 val_macro_f1=0.8998

2026-06-11 20:36:26,567 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:36:27,118 | INFO | Epoch 016/050 train_loss=0.34487 val_loss=0.29263 train_macro_f1=0.8818 val_macro_f1=0.9004

2026-06-11 20:36:27,710 | INFO | Epoch 017/050 train_loss=0.32667 val_loss=0.28829 train_macro_f1=0.8877 val_macro_f1=0.8968

2026-06-11 20:36:28,303 | INFO | Epoch 018/050 train_loss=0.32327 val_loss=0.27714 train_macro_f1=0.8914 val_macro_f1=0.9058

2026-06-11 20:36:28,885 | INFO | Epoch 019/050 train_loss=0.32028 val_loss=0.27395 train_macro_f1=0.8910 val_macro_f1=0.9095

2026-06-11 20:36:29,470 | INFO | Epoch 020/050 train_loss=0.30830 val_loss=0.26280 train_macro_f1=0.8990 val_macro_f1=0.9172

2026-06-11 20:36:29,498 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:36:30,079 | INFO | Epoch 021/050 train_loss=0.29276 val_loss=0.26083 train_macro_f1=0.9100 val_macro_f1=0.9132

2026-06-11 20:36:30,647 | INFO | Epoch 022/050 train_loss=0.29382 val_loss=0.25348 train_macro_f1=0.9034 val_macro_f1=0.9132

2026-06-11 20:36:31,230 | INFO | Epoch 023/050 train_loss=0.27496 val_loss=0.24548 train_macro_f1=0.9207 val_macro_f1=0.9161

2026-06-11 20:36:31,815 | INFO | Epoch 024/050 train_loss=0.28110 val_loss=0.25037 train_macro_f1=0.9136 val_macro_f1=0.9082

2026-06-11 20:36:32,377 | INFO | Epoch 025/050 train_loss=0.27618 val_loss=0.23618 train_macro_f1=0.9033 val_macro_f1=0.9179

2026-06-11 20:36:32,403 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:36:32,952 | INFO | Epoch 026/050 train_loss=0.25775 val_loss=0.23646 train_macro_f1=0.9216 val_macro_f1=0.9200

2026-06-11 20:36:33,524 | INFO | Epoch 027/050 train_loss=0.25376 val_loss=0.22837 train_macro_f1=0.9218 val_macro_f1=0.9274

2026-06-11 20:36:34,105 | INFO | Epoch 028/050 train_loss=0.25024 val_loss=0.23008 train_macro_f1=0.9291 val_macro_f1=0.9167

2026-06-11 20:36:34,661 | INFO | Epoch 029/050 train_loss=0.25681 val_loss=0.22367 train_macro_f1=0.9206 val_macro_f1=0.9200

2026-06-11 20:36:35,265 | INFO | Epoch 030/050 train_loss=0.24613 val_loss=0.21944 train_macro_f1=0.9273 val_macro_f1=0.9261

2026-06-11 20:36:35,288 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:36:35,874 | INFO | Epoch 031/050 train_loss=0.24608 val_loss=0.21936 train_macro_f1=0.9229 val_macro_f1=0.9204

2026-06-11 20:36:36,488 | INFO | Epoch 032/050 train_loss=0.22722 val_loss=0.20925 train_macro_f1=0.9273 val_macro_f1=0.9261

2026-06-11 20:36:37,078 | INFO | Epoch 033/050 train_loss=0.23585 val_loss=0.21087 train_macro_f1=0.9328 val_macro_f1=0.9247

2026-06-11 20:36:37,684 | INFO | Epoch 034/050 train_loss=0.22190 val_loss=0.21256 train_macro_f1=0.9315 val_macro_f1=0.9191

2026-06-11 20:36:38,269 | INFO | Epoch 035/050 train_loss=0.23264 val_loss=0.20478 train_macro_f1=0.9234 val_macro_f1=0.9265

2026-06-11 20:36:38,289 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:36:38,865 | INFO | Epoch 036/050 train_loss=0.22251 val_loss=0.20673 train_macro_f1=0.9266 val_macro_f1=0.9251

2026-06-11 20:36:39,456 | INFO | Epoch 037/050 train_loss=0.21377 val_loss=0.20331 train_macro_f1=0.9377 val_macro_f1=0.9307

2026-06-11 20:36:40,062 | INFO | Epoch 038/050 train_loss=0.20637 val_loss=0.20067 train_macro_f1=0.9408 val_macro_f1=0.9307

2026-06-11 20:36:40,630 | INFO | Epoch 039/050 train_loss=0.22017 val_loss=0.20313 train_macro_f1=0.9325 val_macro_f1=0.9270

2026-06-11 20:36:41,218 | INFO | Epoch 040/050 train_loss=0.21333 val_loss=0.19853 train_macro_f1=0.9300 val_macro_f1=0.9326

2026-06-11 20:36:41,247 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:36:41,816 | INFO | Epoch 041/050 train_loss=0.21548 val_loss=0.19624 train_macro_f1=0.9287 val_macro_f1=0.9265

2026-06-11 20:36:42,401 | INFO | Epoch 042/050 train_loss=0.20037 val_loss=0.18924 train_macro_f1=0.9423 val_macro_f1=0.9345

2026-06-11 20:36:43,013 | INFO | Epoch 043/050 train_loss=0.20354 val_loss=0.19651 train_macro_f1=0.9422 val_macro_f1=0.9265

2026-06-11 20:36:43,586 | INFO | Epoch 044/050 train_loss=0.19812 val_loss=0.19105 train_macro_f1=0.9376 val_macro_f1=0.9392

2026-06-11 20:36:44,165 | INFO | Epoch 045/050 train_loss=0.22082 val_loss=0.18671 train_macro_f1=0.9281 val_macro_f1=0.9386

2026-06-11 20:36:44,186 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:36:44,773 | INFO | Epoch 046/050 train_loss=0.19646 val_loss=0.19037 train_macro_f1=0.9425 val_macro_f1=0.9325

2026-06-11 20:36:45,345 | INFO | Epoch 047/050 train_loss=0.21266 val_loss=0.18706 train_macro_f1=0.9312 val_macro_f1=0.9374

2026-06-11 20:36:45,913 | INFO | Epoch 048/050 train_loss=0.19448 val_loss=0.18758 train_macro_f1=0.9384 val_macro_f1=0.9391

2026-06-11 20:36:46,501 | INFO | Epoch 049/050 train_loss=0.19067 val_loss=0.18152 train_macro_f1=0.9439 val_macro_f1=0.9368

2026-06-11 20:36:47,086 | INFO | Epoch 050/050 train_loss=0.19370 val_loss=0.18026 train_macro_f1=0.9330 val_macro_f1=0.9386

2026-06-11 20:36:47,108 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_2/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:36:51,354 | INFO | Fold completed strategy=frozen_backbone fold=2 test_macro_f1=0.7682 duration=33.7s

2026-06-11 20:36:51,356 | INFO | Finished strategy=frozen_backbone fold=2 status=OK

2026-06-11 20:36:51,374 | INFO | Loaded pretrained backbone.

2026-06-11 20:36:51,375 | INFO | Parameters trainable=33924 total=512933 ratio=0.0661

2026-06-11 20:36:51,973 | INFO | Epoch 001/050 train_loss=1.19391 val_loss=1.03729 train_macro_f1=0.4928 val_macro_f1=0.6022

2026-06-11 20:36:52,584 | INFO | Epoch 002/050 train_loss=0.92579 val_loss=0.81792 train_macro_f1=0.6760 val_macro_f1=0.6884

2026-06-11 20:36:53,209 | INFO | Epoch 003/050 train_loss=0.73943 val_loss=0.67167 train_macro_f1=0.7442 val_macro_f1=0.7234

2026-06-11 20:36:53,818 | INFO | Epoch 004/050 train_loss=0.62024 val_loss=0.58640 train_macro_f1=0.7804 val_macro_f1=0.7503

2026-06-11 20:36:54,439 | INFO | Epoch 005/050 train_loss=0.55481 val_loss=0.53412 train_macro_f1=0.8044 val_macro_f1=0.7857

2026-06-11 20:36:54,467 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:36:55,076 | INFO | Epoch 006/050 train_loss=0.49748 val_loss=0.49302 train_macro_f1=0.8369 val_macro_f1=0.8120

2026-06-11 20:36:55,699 | INFO | Epoch 007/050 train_loss=0.47874 val_loss=0.46442 train_macro_f1=0.8317 val_macro_f1=0.8177

2026-06-11 20:36:56,327 | INFO | Epoch 008/050 train_loss=0.45063 val_loss=0.43960 train_macro_f1=0.8420 val_macro_f1=0.8210

2026-06-11 20:36:56,940 | INFO | Epoch 009/050 train_loss=0.43072 val_loss=0.42175 train_macro_f1=0.8495 val_macro_f1=0.8244

2026-06-11 20:36:57,572 | INFO | Epoch 010/050 train_loss=0.41807 val_loss=0.40232 train_macro_f1=0.8573 val_macro_f1=0.8219

2026-06-11 20:36:57,593 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:36:58,184 | INFO | Epoch 011/050 train_loss=0.39468 val_loss=0.38886 train_macro_f1=0.8690 val_macro_f1=0.8533

2026-06-11 20:36:58,812 | INFO | Epoch 012/050 train_loss=0.39087 val_loss=0.37471 train_macro_f1=0.8626 val_macro_f1=0.8527

2026-06-11 20:36:59,434 | INFO | Epoch 013/050 train_loss=0.39510 val_loss=0.36009 train_macro_f1=0.8625 val_macro_f1=0.8639

2026-06-11 20:37:00,049 | INFO | Epoch 014/050 train_loss=0.34764 val_loss=0.34574 train_macro_f1=0.8794 val_macro_f1=0.8729

2026-06-11 20:37:00,665 | INFO | Epoch 015/050 train_loss=0.35682 val_loss=0.33722 train_macro_f1=0.8847 val_macro_f1=0.8916

2026-06-11 20:37:00,691 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:37:01,277 | INFO | Epoch 016/050 train_loss=0.33586 val_loss=0.32646 train_macro_f1=0.8896 val_macro_f1=0.8961

2026-06-11 20:37:01,896 | INFO | Epoch 017/050 train_loss=0.32674 val_loss=0.31909 train_macro_f1=0.8911 val_macro_f1=0.8962

2026-06-11 20:37:02,525 | INFO | Epoch 018/050 train_loss=0.32572 val_loss=0.31395 train_macro_f1=0.8946 val_macro_f1=0.9071

2026-06-11 20:37:03,160 | INFO | Epoch 019/050 train_loss=0.31674 val_loss=0.29877 train_macro_f1=0.8922 val_macro_f1=0.9004

2026-06-11 20:37:03,782 | INFO | Epoch 020/050 train_loss=0.31038 val_loss=0.29673 train_macro_f1=0.9044 val_macro_f1=0.9069

2026-06-11 20:37:03,803 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:37:04,390 | INFO | Epoch 021/050 train_loss=0.29874 val_loss=0.28953 train_macro_f1=0.9090 val_macro_f1=0.9082

2026-06-11 20:37:05,018 | INFO | Epoch 022/050 train_loss=0.28272 val_loss=0.28080 train_macro_f1=0.9124 val_macro_f1=0.9152

2026-06-11 20:37:05,638 | INFO | Epoch 023/050 train_loss=0.28486 val_loss=0.27552 train_macro_f1=0.9045 val_macro_f1=0.9223

2026-06-11 20:37:06,252 | INFO | Epoch 024/050 train_loss=0.27616 val_loss=0.26677 train_macro_f1=0.9027 val_macro_f1=0.9189

2026-06-11 20:37:06,869 | INFO | Epoch 025/050 train_loss=0.26429 val_loss=0.25919 train_macro_f1=0.9106 val_macro_f1=0.9224

2026-06-11 20:37:06,896 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:37:07,501 | INFO | Epoch 026/050 train_loss=0.25716 val_loss=0.25316 train_macro_f1=0.9229 val_macro_f1=0.9171

2026-06-11 20:37:08,112 | INFO | Epoch 027/050 train_loss=0.26105 val_loss=0.24450 train_macro_f1=0.9198 val_macro_f1=0.9278

2026-06-11 20:37:08,738 | INFO | Epoch 028/050 train_loss=0.26457 val_loss=0.24944 train_macro_f1=0.9075 val_macro_f1=0.9227

2026-06-11 20:37:09,339 | INFO | Epoch 029/050 train_loss=0.25342 val_loss=0.23565 train_macro_f1=0.9192 val_macro_f1=0.9304

2026-06-11 20:37:09,948 | INFO | Epoch 030/050 train_loss=0.24500 val_loss=0.23640 train_macro_f1=0.9221 val_macro_f1=0.9266

2026-06-11 20:37:09,964 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:37:10,596 | INFO | Epoch 031/050 train_loss=0.23408 val_loss=0.22985 train_macro_f1=0.9231 val_macro_f1=0.9266

2026-06-11 20:37:11,210 | INFO | Epoch 032/050 train_loss=0.23974 val_loss=0.22610 train_macro_f1=0.9217 val_macro_f1=0.9273

2026-06-11 20:37:11,827 | INFO | Epoch 033/050 train_loss=0.24726 val_loss=0.22477 train_macro_f1=0.9226 val_macro_f1=0.9211

2026-06-11 20:37:12,439 | INFO | Epoch 034/050 train_loss=0.22256 val_loss=0.21101 train_macro_f1=0.9319 val_macro_f1=0.9322

2026-06-11 20:37:13,060 | INFO | Epoch 035/050 train_loss=0.22507 val_loss=0.20666 train_macro_f1=0.9331 val_macro_f1=0.9409

2026-06-11 20:37:13,086 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:37:13,674 | INFO | Epoch 036/050 train_loss=0.20440 val_loss=0.21010 train_macro_f1=0.9415 val_macro_f1=0.9363

2026-06-11 20:37:14,289 | INFO | Epoch 037/050 train_loss=0.20993 val_loss=0.20472 train_macro_f1=0.9387 val_macro_f1=0.9264

2026-06-11 20:37:14,914 | INFO | Epoch 038/050 train_loss=0.21287 val_loss=0.20872 train_macro_f1=0.9338 val_macro_f1=0.9300

2026-06-11 20:37:15,524 | INFO | Epoch 039/050 train_loss=0.20074 val_loss=0.19783 train_macro_f1=0.9408 val_macro_f1=0.9264

2026-06-11 20:37:16,160 | INFO | Epoch 040/050 train_loss=0.21034 val_loss=0.20271 train_macro_f1=0.9314 val_macro_f1=0.9281

2026-06-11 20:37:16,175 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:37:16,778 | INFO | Epoch 041/050 train_loss=0.19590 val_loss=0.19983 train_macro_f1=0.9435 val_macro_f1=0.9281

2026-06-11 20:37:17,397 | INFO | Epoch 042/050 train_loss=0.19456 val_loss=0.20098 train_macro_f1=0.9447 val_macro_f1=0.9280

2026-06-11 20:37:18,002 | INFO | Epoch 043/050 train_loss=0.18851 val_loss=0.18734 train_macro_f1=0.9477 val_macro_f1=0.9357

2026-06-11 20:37:18,619 | INFO | Epoch 044/050 train_loss=0.20283 val_loss=0.19802 train_macro_f1=0.9366 val_macro_f1=0.9325

2026-06-11 20:37:19,223 | INFO | Epoch 045/050 train_loss=0.19014 val_loss=0.19075 train_macro_f1=0.9450 val_macro_f1=0.9343

2026-06-11 20:37:19,238 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:37:19,832 | INFO | Epoch 046/050 train_loss=0.20262 val_loss=0.19114 train_macro_f1=0.9324 val_macro_f1=0.9343

2026-06-11 20:37:20,445 | INFO | Epoch 047/050 train_loss=0.18417 val_loss=0.18400 train_macro_f1=0.9402 val_macro_f1=0.9320

2026-06-11 20:37:21,052 | INFO | Epoch 048/050 train_loss=0.19425 val_loss=0.18066 train_macro_f1=0.9441 val_macro_f1=0.9469

2026-06-11 20:37:21,672 | INFO | Epoch 049/050 train_loss=0.18536 val_loss=0.18597 train_macro_f1=0.9455 val_macro_f1=0.9343

2026-06-11 20:37:22,284 | INFO | Epoch 050/050 train_loss=0.18211 val_loss=0.18571 train_macro_f1=0.9439 val_macro_f1=0.9343

2026-06-11 20:37:22,298 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_3/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:37:26,609 | INFO | Fold completed strategy=frozen_backbone fold=3 test_macro_f1=0.6926 duration=35.3s

2026-06-11 20:37:26,610 | INFO | Finished strategy=frozen_backbone fold=3 status=OK

2026-06-11 20:37:26,629 | INFO | Loaded pretrained backbone.

2026-06-11 20:37:26,630 | INFO | Parameters trainable=33924 total=512933 ratio=0.0661

2026-06-11 20:37:27,255 | INFO | Epoch 001/050 train_loss=1.23473 val_loss=1.03659 train_macro_f1=0.4601 val_macro_f1=0.5660

2026-06-11 20:37:27,900 | INFO | Epoch 002/050 train_loss=0.94355 val_loss=0.79636 train_macro_f1=0.6307 val_macro_f1=0.6782

2026-06-11 20:37:28,534 | INFO | Epoch 003/050 train_loss=0.75061 val_loss=0.64464 train_macro_f1=0.6946 val_macro_f1=0.7061

2026-06-11 20:37:29,174 | INFO | Epoch 004/050 train_loss=0.62510 val_loss=0.56067 train_macro_f1=0.7593 val_macro_f1=0.7709

2026-06-11 20:37:29,813 | INFO | Epoch 005/050 train_loss=0.55421 val_loss=0.50967 train_macro_f1=0.8090 val_macro_f1=0.8020

2026-06-11 20:37:29,840 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:37:30,458 | INFO | Epoch 006/050 train_loss=0.50058 val_loss=0.47176 train_macro_f1=0.8260 val_macro_f1=0.8243

2026-06-11 20:37:31,108 | INFO | Epoch 007/050 train_loss=0.47995 val_loss=0.44681 train_macro_f1=0.8318 val_macro_f1=0.8333

2026-06-11 20:37:31,758 | INFO | Epoch 008/050 train_loss=0.45009 val_loss=0.42626 train_macro_f1=0.8408 val_macro_f1=0.8427

2026-06-11 20:37:32,407 | INFO | Epoch 009/050 train_loss=0.43332 val_loss=0.40836 train_macro_f1=0.8503 val_macro_f1=0.8521

2026-06-11 20:37:33,051 | INFO | Epoch 010/050 train_loss=0.40321 val_loss=0.39892 train_macro_f1=0.8604 val_macro_f1=0.8545

2026-06-11 20:37:33,079 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:37:33,699 | INFO | Epoch 011/050 train_loss=0.39814 val_loss=0.38591 train_macro_f1=0.8582 val_macro_f1=0.8514

2026-06-11 20:37:34,337 | INFO | Epoch 012/050 train_loss=0.37722 val_loss=0.36790 train_macro_f1=0.8718 val_macro_f1=0.8599

2026-06-11 20:37:34,981 | INFO | Epoch 013/050 train_loss=0.36477 val_loss=0.36175 train_macro_f1=0.8717 val_macro_f1=0.8603

2026-06-11 20:37:35,610 | INFO | Epoch 014/050 train_loss=0.35947 val_loss=0.34758 train_macro_f1=0.8714 val_macro_f1=0.8652

2026-06-11 20:37:36,245 | INFO | Epoch 015/050 train_loss=0.33453 val_loss=0.34584 train_macro_f1=0.8928 val_macro_f1=0.8781

2026-06-11 20:37:36,274 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:37:36,902 | INFO | Epoch 016/050 train_loss=0.33593 val_loss=0.33100 train_macro_f1=0.8851 val_macro_f1=0.8848

2026-06-11 20:37:37,547 | INFO | Epoch 017/050 train_loss=0.33094 val_loss=0.32472 train_macro_f1=0.8801 val_macro_f1=0.8941

2026-06-11 20:37:38,179 | INFO | Epoch 018/050 train_loss=0.31797 val_loss=0.31852 train_macro_f1=0.8861 val_macro_f1=0.8935

2026-06-11 20:37:38,833 | INFO | Epoch 019/050 train_loss=0.31273 val_loss=0.30877 train_macro_f1=0.8914 val_macro_f1=0.9093

2026-06-11 20:37:39,468 | INFO | Epoch 020/050 train_loss=0.28618 val_loss=0.30442 train_macro_f1=0.9097 val_macro_f1=0.9128

2026-06-11 20:37:39,723 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:37:40,347 | INFO | Epoch 021/050 train_loss=0.29962 val_loss=0.29165 train_macro_f1=0.9030 val_macro_f1=0.9097

2026-06-11 20:37:40,994 | INFO | Epoch 022/050 train_loss=0.30696 val_loss=0.28902 train_macro_f1=0.8975 val_macro_f1=0.9115

2026-06-11 20:37:41,625 | INFO | Epoch 023/050 train_loss=0.27526 val_loss=0.29626 train_macro_f1=0.9151 val_macro_f1=0.9078

2026-06-11 20:37:42,252 | INFO | Epoch 024/050 train_loss=0.27536 val_loss=0.28479 train_macro_f1=0.9077 val_macro_f1=0.9155

2026-06-11 20:37:42,888 | INFO | Epoch 025/050 train_loss=0.28126 val_loss=0.27224 train_macro_f1=0.9051 val_macro_f1=0.9218

2026-06-11 20:37:42,917 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:37:43,534 | INFO | Epoch 026/050 train_loss=0.26692 val_loss=0.27270 train_macro_f1=0.9131 val_macro_f1=0.9132

2026-06-11 20:37:44,180 | INFO | Epoch 027/050 train_loss=0.25466 val_loss=0.26323 train_macro_f1=0.9167 val_macro_f1=0.9248

2026-06-11 20:37:44,832 | INFO | Epoch 028/050 train_loss=0.25198 val_loss=0.26147 train_macro_f1=0.9256 val_macro_f1=0.9204

2026-06-11 20:37:45,472 | INFO | Epoch 029/050 train_loss=0.25087 val_loss=0.25105 train_macro_f1=0.9261 val_macro_f1=0.9226

2026-06-11 20:37:46,113 | INFO | Epoch 030/050 train_loss=0.24048 val_loss=0.24760 train_macro_f1=0.9250 val_macro_f1=0.9203

2026-06-11 20:37:46,134 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:37:46,755 | INFO | Epoch 031/050 train_loss=0.24336 val_loss=0.24506 train_macro_f1=0.9135 val_macro_f1=0.9234

2026-06-11 20:37:47,404 | INFO | Epoch 032/050 train_loss=0.22541 val_loss=0.23966 train_macro_f1=0.9310 val_macro_f1=0.9195

2026-06-11 20:37:48,047 | INFO | Epoch 033/050 train_loss=0.22554 val_loss=0.24034 train_macro_f1=0.9310 val_macro_f1=0.9195

2026-06-11 20:37:48,674 | INFO | Epoch 034/050 train_loss=0.22886 val_loss=0.23851 train_macro_f1=0.9330 val_macro_f1=0.9195

2026-06-11 20:37:49,309 | INFO | Epoch 035/050 train_loss=0.21294 val_loss=0.23219 train_macro_f1=0.9252 val_macro_f1=0.9195

2026-06-11 20:37:49,332 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:37:49,982 | INFO | Epoch 036/050 train_loss=0.20842 val_loss=0.23465 train_macro_f1=0.9411 val_macro_f1=0.9195

2026-06-11 20:37:50,619 | INFO | Epoch 037/050 train_loss=0.22696 val_loss=0.22883 train_macro_f1=0.9335 val_macro_f1=0.9191

2026-06-11 20:37:51,272 | INFO | Epoch 038/050 train_loss=0.21220 val_loss=0.22372 train_macro_f1=0.9277 val_macro_f1=0.9189

2026-06-11 20:37:51,915 | INFO | Epoch 039/050 train_loss=0.21404 val_loss=0.23043 train_macro_f1=0.9286 val_macro_f1=0.9170

2026-06-11 20:37:52,543 | INFO | Epoch 040/050 train_loss=0.20937 val_loss=0.22552 train_macro_f1=0.9360 val_macro_f1=0.9191

2026-06-11 20:37:52,558 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:37:53,193 | INFO | Epoch 041/050 train_loss=0.20761 val_loss=0.23380 train_macro_f1=0.9354 val_macro_f1=0.9158

2026-06-11 20:37:53,826 | INFO | Epoch 042/050 train_loss=0.21935 val_loss=0.22510 train_macro_f1=0.9333 val_macro_f1=0.9218

2026-06-11 20:37:54,460 | INFO | Epoch 043/050 train_loss=0.20670 val_loss=0.21829 train_macro_f1=0.9416 val_macro_f1=0.9264

2026-06-11 20:37:55,114 | INFO | Epoch 044/050 train_loss=0.20835 val_loss=0.21954 train_macro_f1=0.9318 val_macro_f1=0.9266

2026-06-11 20:37:55,766 | INFO | Epoch 045/050 train_loss=0.20106 val_loss=0.21709 train_macro_f1=0.9381 val_macro_f1=0.9264

2026-06-11 20:37:55,788 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:37:56,416 | INFO | Epoch 046/050 train_loss=0.20258 val_loss=0.21498 train_macro_f1=0.9369 val_macro_f1=0.9291

2026-06-11 20:37:57,062 | INFO | Epoch 047/050 train_loss=0.20651 val_loss=0.21889 train_macro_f1=0.9379 val_macro_f1=0.9309

2026-06-11 20:37:57,715 | INFO | Epoch 048/050 train_loss=0.22266 val_loss=0.21335 train_macro_f1=0.9226 val_macro_f1=0.9268

2026-06-11 20:37:58,362 | INFO | Epoch 049/050 train_loss=0.19995 val_loss=0.21725 train_macro_f1=0.9419 val_macro_f1=0.9309

2026-06-11 20:37:59,003 | INFO | Epoch 050/050 train_loss=0.20395 val_loss=0.20761 train_macro_f1=0.9434 val_macro_f1=0.9264

2026-06-11 20:37:59,026 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_4/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:38:03,440 | INFO | Fold completed strategy=frozen_backbone fold=4 test_macro_f1=0.6955 duration=36.8s

2026-06-11 20:38:03,443 | INFO | Finished strategy=frozen_backbone fold=4 status=OK

2026-06-11 20:38:03,463 | INFO | Loaded pretrained backbone.

2026-06-11 20:38:03,464 | INFO | Parameters trainable=33924 total=512933 ratio=0.0661

2026-06-11 20:38:04,115 | INFO | Epoch 001/050 train_loss=1.17486 val_loss=1.00489 train_macro_f1=0.4381 val_macro_f1=0.5771

2026-06-11 20:38:04,777 | INFO | Epoch 002/050 train_loss=0.89108 val_loss=0.79822 train_macro_f1=0.6005 val_macro_f1=0.6363

2026-06-11 20:38:05,438 | INFO | Epoch 003/050 train_loss=0.71066 val_loss=0.67555 train_macro_f1=0.6903 val_macro_f1=0.7076

2026-06-11 20:38:06,100 | INFO | Epoch 004/050 train_loss=0.60867 val_loss=0.60644 train_macro_f1=0.7664 val_macro_f1=0.7640

2026-06-11 20:38:06,770 | INFO | Epoch 005/050 train_loss=0.53091 val_loss=0.55947 train_macro_f1=0.8092 val_macro_f1=0.8118

2026-06-11 20:38:06,798 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:38:07,440 | INFO | Epoch 006/050 train_loss=0.49185 val_loss=0.52428 train_macro_f1=0.8309 val_macro_f1=0.8030

2026-06-11 20:38:08,098 | INFO | Epoch 007/050 train_loss=0.47630 val_loss=0.49161 train_macro_f1=0.8357 val_macro_f1=0.8318

2026-06-11 20:38:08,763 | INFO | Epoch 008/050 train_loss=0.44034 val_loss=0.47477 train_macro_f1=0.8489 val_macro_f1=0.8284

2026-06-11 20:38:09,421 | INFO | Epoch 009/050 train_loss=0.41877 val_loss=0.45454 train_macro_f1=0.8680 val_macro_f1=0.8375

2026-06-11 20:38:10,085 | INFO | Epoch 010/050 train_loss=0.39791 val_loss=0.44517 train_macro_f1=0.8650 val_macro_f1=0.8342

2026-06-11 20:38:10,107 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:38:10,748 | INFO | Epoch 011/050 train_loss=0.38991 val_loss=0.42279 train_macro_f1=0.8617 val_macro_f1=0.8631

2026-06-11 20:38:11,407 | INFO | Epoch 012/050 train_loss=0.37453 val_loss=0.41550 train_macro_f1=0.8691 val_macro_f1=0.8633

2026-06-11 20:38:12,065 | INFO | Epoch 013/050 train_loss=0.36843 val_loss=0.39675 train_macro_f1=0.8697 val_macro_f1=0.8824

2026-06-11 20:38:12,727 | INFO | Epoch 014/050 train_loss=0.35255 val_loss=0.38613 train_macro_f1=0.8789 val_macro_f1=0.8750

2026-06-11 20:38:13,385 | INFO | Epoch 015/050 train_loss=0.34963 val_loss=0.37665 train_macro_f1=0.8730 val_macro_f1=0.8850

2026-06-11 20:38:13,413 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:38:14,057 | INFO | Epoch 016/050 train_loss=0.33252 val_loss=0.37091 train_macro_f1=0.8866 val_macro_f1=0.8803

2026-06-11 20:38:14,716 | INFO | Epoch 017/050 train_loss=0.32508 val_loss=0.35744 train_macro_f1=0.8842 val_macro_f1=0.8916

2026-06-11 20:38:15,380 | INFO | Epoch 018/050 train_loss=0.31400 val_loss=0.34427 train_macro_f1=0.8950 val_macro_f1=0.8995

2026-06-11 20:38:16,040 | INFO | Epoch 019/050 train_loss=0.31013 val_loss=0.33891 train_macro_f1=0.8957 val_macro_f1=0.9011

2026-06-11 20:38:16,699 | INFO | Epoch 020/050 train_loss=0.30665 val_loss=0.33486 train_macro_f1=0.9027 val_macro_f1=0.9021

2026-06-11 20:38:16,728 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:38:17,369 | INFO | Epoch 021/050 train_loss=0.29474 val_loss=0.32418 train_macro_f1=0.9133 val_macro_f1=0.9071

2026-06-11 20:38:18,032 | INFO | Epoch 022/050 train_loss=0.28360 val_loss=0.31920 train_macro_f1=0.9169 val_macro_f1=0.9119

2026-06-11 20:38:18,694 | INFO | Epoch 023/050 train_loss=0.26636 val_loss=0.30505 train_macro_f1=0.9093 val_macro_f1=0.9161

2026-06-11 20:38:19,354 | INFO | Epoch 024/050 train_loss=0.27818 val_loss=0.31288 train_macro_f1=0.9079 val_macro_f1=0.9123

2026-06-11 20:38:19,997 | INFO | Epoch 025/050 train_loss=0.27683 val_loss=0.29452 train_macro_f1=0.9116 val_macro_f1=0.9230

2026-06-11 20:38:20,025 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:38:20,669 | INFO | Epoch 026/050 train_loss=0.25919 val_loss=0.29489 train_macro_f1=0.9260 val_macro_f1=0.9162

2026-06-11 20:38:21,318 | INFO | Epoch 027/050 train_loss=0.25703 val_loss=0.28301 train_macro_f1=0.9162 val_macro_f1=0.9250

2026-06-11 20:38:21,983 | INFO | Epoch 028/050 train_loss=0.26011 val_loss=0.27424 train_macro_f1=0.9210 val_macro_f1=0.9248

2026-06-11 20:38:22,636 | INFO | Epoch 029/050 train_loss=0.24125 val_loss=0.27023 train_macro_f1=0.9297 val_macro_f1=0.9252

2026-06-11 20:38:23,300 | INFO | Epoch 030/050 train_loss=0.23943 val_loss=0.26338 train_macro_f1=0.9298 val_macro_f1=0.9286

2026-06-11 20:38:23,328 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:38:23,970 | INFO | Epoch 031/050 train_loss=0.22894 val_loss=0.26294 train_macro_f1=0.9312 val_macro_f1=0.9286

2026-06-11 20:38:24,634 | INFO | Epoch 032/050 train_loss=0.22762 val_loss=0.25809 train_macro_f1=0.9313 val_macro_f1=0.9302

2026-06-11 20:38:25,292 | INFO | Epoch 033/050 train_loss=0.22583 val_loss=0.25385 train_macro_f1=0.9266 val_macro_f1=0.9302

2026-06-11 20:38:25,949 | INFO | Epoch 034/050 train_loss=0.22668 val_loss=0.24797 train_macro_f1=0.9379 val_macro_f1=0.9340

2026-06-11 20:38:26,624 | INFO | Epoch 035/050 train_loss=0.21600 val_loss=0.24518 train_macro_f1=0.9361 val_macro_f1=0.9302

2026-06-11 20:38:26,645 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:38:27,292 | INFO | Epoch 036/050 train_loss=0.21878 val_loss=0.24524 train_macro_f1=0.9376 val_macro_f1=0.9358

2026-06-11 20:38:27,942 | INFO | Epoch 037/050 train_loss=0.20542 val_loss=0.23159 train_macro_f1=0.9423 val_macro_f1=0.9338

2026-06-11 20:38:28,597 | INFO | Epoch 038/050 train_loss=0.21237 val_loss=0.22977 train_macro_f1=0.9369 val_macro_f1=0.9358

2026-06-11 20:38:29,283 | INFO | Epoch 039/050 train_loss=0.20864 val_loss=0.23382 train_macro_f1=0.9378 val_macro_f1=0.9358

2026-06-11 20:38:29,939 | INFO | Epoch 040/050 train_loss=0.19297 val_loss=0.22315 train_macro_f1=0.9461 val_macro_f1=0.9394

2026-06-11 20:38:29,967 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:38:30,607 | INFO | Epoch 041/050 train_loss=0.20741 val_loss=0.21578 train_macro_f1=0.9289 val_macro_f1=0.9410

2026-06-11 20:38:31,269 | INFO | Epoch 042/050 train_loss=0.19684 val_loss=0.22112 train_macro_f1=0.9395 val_macro_f1=0.9396

2026-06-11 20:38:31,921 | INFO | Epoch 043/050 train_loss=0.19437 val_loss=0.21265 train_macro_f1=0.9427 val_macro_f1=0.9416

2026-06-11 20:38:32,584 | INFO | Epoch 044/050 train_loss=0.17924 val_loss=0.20960 train_macro_f1=0.9481 val_macro_f1=0.9441

2026-06-11 20:38:33,255 | INFO | Epoch 045/050 train_loss=0.19152 val_loss=0.20864 train_macro_f1=0.9325 val_macro_f1=0.9403

2026-06-11 20:38:33,275 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:38:33,917 | INFO | Epoch 046/050 train_loss=0.17972 val_loss=0.19694 train_macro_f1=0.9476 val_macro_f1=0.9416

2026-06-11 20:38:34,573 | INFO | Epoch 047/050 train_loss=0.17301 val_loss=0.20069 train_macro_f1=0.9471 val_macro_f1=0.9466

2026-06-11 20:38:35,239 | INFO | Epoch 048/050 train_loss=0.18540 val_loss=0.19940 train_macro_f1=0.9457 val_macro_f1=0.9472

2026-06-11 20:38:35,900 | INFO | Epoch 049/050 train_loss=0.17185 val_loss=0.18726 train_macro_f1=0.9526 val_macro_f1=0.9506

2026-06-11 20:38:36,562 | INFO | Epoch 050/050 train_loss=0.16623 val_loss=0.19535 train_macro_f1=0.9596 val_macro_f1=0.9485

2026-06-11 20:38:36,577 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/frozen_backbone/fold_5/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:38:40,950 | INFO | Fold completed strategy=frozen_backbone fold=5 test_macro_f1=0.7279 duration=37.5s

2026-06-11 20:38:40,952 | INFO | Finished strategy=frozen_backbone fold=5 status=OK

2026-06-11 20:38:40,952 | INFO | Strategy started: partial_finetune

2026-06-11 20:38:40,970 | INFO | Loaded pretrained backbone.

2026-06-11 20:38:40,971 | INFO | Parameters trainable=448773 total=512933 ratio=0.8749

2026-06-11 20:38:41,703 | INFO | Epoch 001/050 train_loss=0.91876 val_loss=0.57026 train_macro_f1=0.5638 val_macro_f1=0.7431

2026-06-11 20:38:42,469 | INFO | Epoch 002/050 train_loss=0.57108 val_loss=0.37656 train_macro_f1=0.8189 val_macro_f1=0.9138

2026-06-11 20:38:43,239 | INFO | Epoch 003/050 train_loss=0.41046 val_loss=0.28741 train_macro_f1=0.8962 val_macro_f1=0.9304

2026-06-11 20:38:44,013 | INFO | Epoch 004/050 train_loss=0.31996 val_loss=0.22634 train_macro_f1=0.9099 val_macro_f1=0.9510

2026-06-11 20:38:44,789 | INFO | Epoch 005/050 train_loss=0.26328 val_loss=0.30925 train_macro_f1=0.9284 val_macro_f1=0.9030

2026-06-11 20:38:44,816 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:38:45,545 | INFO | Epoch 006/050 train_loss=0.23764 val_loss=0.17137 train_macro_f1=0.9337 val_macro_f1=0.9523

2026-06-11 20:38:46,323 | INFO | Epoch 007/050 train_loss=0.18021 val_loss=0.11681 train_macro_f1=0.9555 val_macro_f1=0.9789

2026-06-11 20:38:47,093 | INFO | Epoch 008/050 train_loss=0.16386 val_loss=0.11444 train_macro_f1=0.9512 val_macro_f1=0.9743

2026-06-11 20:38:47,861 | INFO | Epoch 009/050 train_loss=0.14539 val_loss=0.21222 train_macro_f1=0.9660 val_macro_f1=0.9308

2026-06-11 20:38:48,605 | INFO | Epoch 010/050 train_loss=0.14195 val_loss=0.15884 train_macro_f1=0.9616 val_macro_f1=0.9447

2026-06-11 20:38:48,631 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:38:49,359 | INFO | Epoch 011/050 train_loss=0.12961 val_loss=0.11618 train_macro_f1=0.9631 val_macro_f1=0.9687

2026-06-11 20:38:50,112 | INFO | Epoch 012/050 train_loss=0.10481 val_loss=0.11424 train_macro_f1=0.9723 val_macro_f1=0.9668

2026-06-11 20:38:50,877 | INFO | Epoch 013/050 train_loss=0.10402 val_loss=0.09196 train_macro_f1=0.9693 val_macro_f1=0.9706

2026-06-11 20:38:51,637 | INFO | Epoch 014/050 train_loss=0.07398 val_loss=0.07729 train_macro_f1=0.9848 val_macro_f1=0.9803

2026-06-11 20:38:52,408 | INFO | Epoch 015/050 train_loss=0.06326 val_loss=0.12198 train_macro_f1=0.9879 val_macro_f1=0.9630

2026-06-11 20:38:52,434 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:38:53,179 | INFO | Epoch 016/050 train_loss=0.06209 val_loss=0.19408 train_macro_f1=0.9838 val_macro_f1=0.9317

2026-06-11 20:38:53,922 | INFO | Epoch 017/050 train_loss=0.05341 val_loss=0.07098 train_macro_f1=0.9875 val_macro_f1=0.9835

2026-06-11 20:38:54,709 | INFO | Epoch 018/050 train_loss=0.05335 val_loss=0.04870 train_macro_f1=0.9877 val_macro_f1=0.9909

2026-06-11 20:38:55,477 | INFO | Epoch 019/050 train_loss=0.04703 val_loss=0.14770 train_macro_f1=0.9908 val_macro_f1=0.9475

2026-06-11 20:38:56,213 | INFO | Epoch 020/050 train_loss=0.04269 val_loss=0.04702 train_macro_f1=0.9892 val_macro_f1=0.9890

2026-06-11 20:38:56,252 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:38:56,982 | INFO | Epoch 021/050 train_loss=0.04413 val_loss=0.15908 train_macro_f1=0.9872 val_macro_f1=0.9534

2026-06-11 20:38:57,717 | INFO | Epoch 022/050 train_loss=0.04101 val_loss=0.09194 train_macro_f1=0.9903 val_macro_f1=0.9743

2026-06-11 20:38:58,453 | INFO | Epoch 023/050 train_loss=0.05056 val_loss=0.04786 train_macro_f1=0.9866 val_macro_f1=0.9890

2026-06-11 20:38:59,189 | INFO | Epoch 024/050 train_loss=0.04099 val_loss=0.04273 train_macro_f1=0.9897 val_macro_f1=0.9891

2026-06-11 20:38:59,962 | INFO | Epoch 025/050 train_loss=0.03570 val_loss=0.06951 train_macro_f1=0.9908 val_macro_f1=0.9779

2026-06-11 20:38:59,988 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:39:00,711 | INFO | Epoch 026/050 train_loss=0.03623 val_loss=0.11767 train_macro_f1=0.9894 val_macro_f1=0.9667

2026-06-11 20:39:01,442 | INFO | Epoch 027/050 train_loss=0.02596 val_loss=0.05798 train_macro_f1=0.9944 val_macro_f1=0.9890

2026-06-11 20:39:02,170 | INFO | Epoch 028/050 train_loss=0.03762 val_loss=0.03870 train_macro_f1=0.9890 val_macro_f1=0.9909

2026-06-11 20:39:02,920 | INFO | Epoch 029/050 train_loss=0.03360 val_loss=0.04488 train_macro_f1=0.9910 val_macro_f1=0.9872

2026-06-11 20:39:03,655 | INFO | Epoch 030/050 train_loss=0.03231 val_loss=0.06830 train_macro_f1=0.9906 val_macro_f1=0.9817

2026-06-11 20:39:03,682 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:39:04,403 | INFO | Epoch 031/050 train_loss=0.02352 val_loss=0.06053 train_macro_f1=0.9952 val_macro_f1=0.9835

2026-06-11 20:39:05,148 | INFO | Epoch 032/050 train_loss=0.03182 val_loss=0.05898 train_macro_f1=0.9947 val_macro_f1=0.9817

2026-06-11 20:39:05,881 | INFO | Epoch 033/050 train_loss=0.02827 val_loss=0.06643 train_macro_f1=0.9941 val_macro_f1=0.9798

2026-06-11 20:39:06,635 | INFO | Epoch 034/050 train_loss=0.02372 val_loss=0.05291 train_macro_f1=0.9930 val_macro_f1=0.9835

2026-06-11 20:39:07,376 | INFO | Epoch 035/050 train_loss=0.01902 val_loss=0.04954 train_macro_f1=0.9956 val_macro_f1=0.9835

2026-06-11 20:39:07,403 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:39:08,142 | INFO | Epoch 036/050 train_loss=0.01895 val_loss=0.08378 train_macro_f1=0.9953 val_macro_f1=0.9705

2026-06-11 20:39:08,875 | INFO | Epoch 037/050 train_loss=0.02445 val_loss=0.07290 train_macro_f1=0.9950 val_macro_f1=0.9779

2026-06-11 20:39:09,630 | INFO | Epoch 038/050 train_loss=0.02852 val_loss=0.05432 train_macro_f1=0.9918 val_macro_f1=0.9835

2026-06-11 20:39:10,366 | INFO | Epoch 039/050 train_loss=0.02252 val_loss=0.07098 train_macro_f1=0.9946 val_macro_f1=0.9817

2026-06-11 20:39:11,102 | INFO | Epoch 040/050 train_loss=0.02645 val_loss=0.04577 train_macro_f1=0.9918 val_macro_f1=0.9890

2026-06-11 20:39:11,128 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:39:11,865 | INFO | Epoch 041/050 train_loss=0.01665 val_loss=0.04198 train_macro_f1=0.9975 val_macro_f1=0.9890

2026-06-11 20:39:12,600 | INFO | Epoch 042/050 train_loss=0.02349 val_loss=0.04356 train_macro_f1=0.9949 val_macro_f1=0.9909

2026-06-11 20:39:13,339 | INFO | Epoch 043/050 train_loss=0.01788 val_loss=0.05298 train_macro_f1=0.9971 val_macro_f1=0.9854

2026-06-11 20:39:14,101 | INFO | Epoch 044/050 train_loss=0.01434 val_loss=0.06527 train_macro_f1=0.9980 val_macro_f1=0.9835

2026-06-11 20:39:14,874 | INFO | Epoch 045/050 train_loss=0.01529 val_loss=0.06525 train_macro_f1=0.9982 val_macro_f1=0.9798

2026-06-11 20:39:14,902 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:39:15,675 | INFO | Epoch 046/050 train_loss=0.01470 val_loss=0.06109 train_macro_f1=0.9973 val_macro_f1=0.9835

2026-06-11 20:39:16,414 | INFO | Epoch 047/050 train_loss=0.02218 val_loss=0.05286 train_macro_f1=0.9941 val_macro_f1=0.9854

2026-06-11 20:39:17,143 | INFO | Epoch 048/050 train_loss=0.02031 val_loss=0.06354 train_macro_f1=0.9952 val_macro_f1=0.9817

2026-06-11 20:39:17,884 | INFO | Epoch 049/050 train_loss=0.02414 val_loss=0.06138 train_macro_f1=0.9933 val_macro_f1=0.9835

2026-06-11 20:39:18,618 | INFO | Epoch 050/050 train_loss=0.01852 val_loss=0.07196 train_macro_f1=0.9956 val_macro_f1=0.9779

2026-06-11 20:39:18,644 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_1/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:39:23,123 | INFO | Fold completed strategy=partial_finetune fold=1 test_macro_f1=0.8309 duration=42.2s

2026-06-11 20:39:23,126 | INFO | Finished strategy=partial_finetune fold=1 status=OK

2026-06-11 20:39:23,144 | INFO | Loaded pretrained backbone.

2026-06-11 20:39:23,145 | INFO | Parameters trainable=448773 total=512933 ratio=0.8749

2026-06-11 20:39:23,922 | INFO | Epoch 001/050 train_loss=0.93782 val_loss=0.58388 train_macro_f1=0.5808 val_macro_f1=0.8739

2026-06-11 20:39:24,732 | INFO | Epoch 002/050 train_loss=0.53337 val_loss=0.39586 train_macro_f1=0.8443 val_macro_f1=0.8764

2026-06-11 20:39:25,529 | INFO | Epoch 003/050 train_loss=0.38254 val_loss=0.27374 train_macro_f1=0.8892 val_macro_f1=0.9330

2026-06-11 20:39:26,317 | INFO | Epoch 004/050 train_loss=0.32473 val_loss=0.30920 train_macro_f1=0.9088 val_macro_f1=0.8875

2026-06-11 20:39:27,083 | INFO | Epoch 005/050 train_loss=0.28008 val_loss=0.21644 train_macro_f1=0.9270 val_macro_f1=0.9419

2026-06-11 20:39:27,138 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:39:27,890 | INFO | Epoch 006/050 train_loss=0.24332 val_loss=0.27852 train_macro_f1=0.9259 val_macro_f1=0.9081

2026-06-11 20:39:28,655 | INFO | Epoch 007/050 train_loss=0.19079 val_loss=0.23899 train_macro_f1=0.9552 val_macro_f1=0.9242

2026-06-11 20:39:29,422 | INFO | Epoch 008/050 train_loss=0.16479 val_loss=0.22224 train_macro_f1=0.9603 val_macro_f1=0.9212

2026-06-11 20:39:30,186 | INFO | Epoch 009/050 train_loss=0.14220 val_loss=0.29722 train_macro_f1=0.9630 val_macro_f1=0.8993

2026-06-11 20:39:30,948 | INFO | Epoch 010/050 train_loss=0.11876 val_loss=0.28485 train_macro_f1=0.9688 val_macro_f1=0.9046

2026-06-11 20:39:30,974 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:39:31,726 | INFO | Epoch 011/050 train_loss=0.10477 val_loss=0.16825 train_macro_f1=0.9726 val_macro_f1=0.9517

2026-06-11 20:39:32,521 | INFO | Epoch 012/050 train_loss=0.08967 val_loss=0.13859 train_macro_f1=0.9771 val_macro_f1=0.9746

2026-06-11 20:39:33,310 | INFO | Epoch 013/050 train_loss=0.09213 val_loss=0.31576 train_macro_f1=0.9768 val_macro_f1=0.9015

2026-06-11 20:39:34,082 | INFO | Epoch 014/050 train_loss=0.09103 val_loss=0.14619 train_macro_f1=0.9739 val_macro_f1=0.9559

2026-06-11 20:39:34,845 | INFO | Epoch 015/050 train_loss=0.07702 val_loss=0.33898 train_macro_f1=0.9784 val_macro_f1=0.9040

2026-06-11 20:39:34,870 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:39:35,630 | INFO | Epoch 016/050 train_loss=0.08250 val_loss=0.10516 train_macro_f1=0.9794 val_macro_f1=0.9714

2026-06-11 20:39:36,407 | INFO | Epoch 017/050 train_loss=0.05351 val_loss=0.11956 train_macro_f1=0.9885 val_macro_f1=0.9634

2026-06-11 20:39:37,187 | INFO | Epoch 018/050 train_loss=0.05291 val_loss=0.19681 train_macro_f1=0.9843 val_macro_f1=0.9545

2026-06-11 20:39:37,945 | INFO | Epoch 019/050 train_loss=0.05544 val_loss=0.18993 train_macro_f1=0.9839 val_macro_f1=0.9468

2026-06-11 20:39:38,709 | INFO | Epoch 020/050 train_loss=0.03579 val_loss=0.08737 train_macro_f1=0.9929 val_macro_f1=0.9801

2026-06-11 20:39:38,766 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:39:39,523 | INFO | Epoch 021/050 train_loss=0.03374 val_loss=0.06540 train_macro_f1=0.9933 val_macro_f1=0.9838

2026-06-11 20:39:40,302 | INFO | Epoch 022/050 train_loss=0.03414 val_loss=0.05917 train_macro_f1=0.9928 val_macro_f1=0.9856

2026-06-11 20:39:41,100 | INFO | Epoch 023/050 train_loss=0.03360 val_loss=0.20477 train_macro_f1=0.9910 val_macro_f1=0.9386

2026-06-11 20:39:41,870 | INFO | Epoch 024/050 train_loss=0.03755 val_loss=0.15304 train_macro_f1=0.9913 val_macro_f1=0.9502

2026-06-11 20:39:42,636 | INFO | Epoch 025/050 train_loss=0.03177 val_loss=0.12798 train_macro_f1=0.9925 val_macro_f1=0.9653

2026-06-11 20:39:42,663 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:39:43,418 | INFO | Epoch 026/050 train_loss=0.03215 val_loss=0.13756 train_macro_f1=0.9894 val_macro_f1=0.9597

2026-06-11 20:39:44,186 | INFO | Epoch 027/050 train_loss=0.02183 val_loss=0.12535 train_macro_f1=0.9942 val_macro_f1=0.9635

2026-06-11 20:39:44,965 | INFO | Epoch 028/050 train_loss=0.02212 val_loss=0.20051 train_macro_f1=0.9941 val_macro_f1=0.9448

2026-06-11 20:39:45,727 | INFO | Epoch 029/050 train_loss=0.01686 val_loss=0.19947 train_macro_f1=0.9967 val_macro_f1=0.9448

2026-06-11 20:39:46,491 | INFO | Epoch 030/050 train_loss=0.02139 val_loss=0.09019 train_macro_f1=0.9946 val_macro_f1=0.9714

2026-06-11 20:39:46,518 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:39:47,265 | INFO | Epoch 031/050 train_loss=0.01842 val_loss=0.07160 train_macro_f1=0.9953 val_macro_f1=0.9788

2026-06-11 20:39:48,032 | INFO | Epoch 032/050 train_loss=0.01971 val_loss=0.12386 train_macro_f1=0.9953 val_macro_f1=0.9658

2026-06-11 20:39:48,795 | INFO | Epoch 033/050 train_loss=0.03010 val_loss=0.09375 train_macro_f1=0.9924 val_macro_f1=0.9714

2026-06-11 20:39:49,570 | INFO | Epoch 034/050 train_loss=0.01505 val_loss=0.08824 train_macro_f1=0.9958 val_macro_f1=0.9709

2026-06-11 20:39:50,324 | INFO | Epoch 035/050 train_loss=0.01061 val_loss=0.08103 train_macro_f1=0.9995 val_macro_f1=0.9733

2026-06-11 20:39:50,350 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:39:51,109 | INFO | Epoch 036/050 train_loss=0.01414 val_loss=0.07748 train_macro_f1=0.9965 val_macro_f1=0.9770

2026-06-11 20:39:51,875 | INFO | Epoch 037/050 train_loss=0.01640 val_loss=0.10380 train_macro_f1=0.9965 val_macro_f1=0.9695

2026-06-11 20:39:52,645 | INFO | Epoch 038/050 train_loss=0.01406 val_loss=0.08351 train_macro_f1=0.9960 val_macro_f1=0.9733

2026-06-11 20:39:53,433 | INFO | Epoch 039/050 train_loss=0.01201 val_loss=0.09578 train_macro_f1=0.9985 val_macro_f1=0.9733

2026-06-11 20:39:54,200 | INFO | Epoch 040/050 train_loss=0.01576 val_loss=0.08829 train_macro_f1=0.9973 val_macro_f1=0.9751

2026-06-11 20:39:54,226 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:39:54,975 | INFO | Epoch 041/050 train_loss=0.01231 val_loss=0.07479 train_macro_f1=0.9976 val_macro_f1=0.9751

2026-06-11 20:39:55,743 | INFO | Epoch 042/050 train_loss=0.01486 val_loss=0.08265 train_macro_f1=0.9959 val_macro_f1=0.9770

2026-06-11 20:39:56,512 | INFO | Epoch 043/050 train_loss=0.01050 val_loss=0.09736 train_macro_f1=0.9968 val_macro_f1=0.9714

2026-06-11 20:39:57,286 | INFO | Epoch 044/050 train_loss=0.01146 val_loss=0.08664 train_macro_f1=0.9985 val_macro_f1=0.9751

2026-06-11 20:39:58,048 | INFO | Epoch 045/050 train_loss=0.01223 val_loss=0.06320 train_macro_f1=0.9977 val_macro_f1=0.9825

2026-06-11 20:39:58,073 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:39:58,826 | INFO | Epoch 046/050 train_loss=0.00871 val_loss=0.10093 train_macro_f1=0.9973 val_macro_f1=0.9695

2026-06-11 20:39:59,600 | INFO | Epoch 047/050 train_loss=0.01841 val_loss=0.08505 train_macro_f1=0.9962 val_macro_f1=0.9751

2026-06-11 20:40:00,366 | INFO | Epoch 048/050 train_loss=0.00967 val_loss=0.08803 train_macro_f1=0.9977 val_macro_f1=0.9733

2026-06-11 20:40:01,132 | INFO | Epoch 049/050 train_loss=0.00945 val_loss=0.07747 train_macro_f1=0.9986 val_macro_f1=0.9788

2026-06-11 20:40:01,898 | INFO | Epoch 050/050 train_loss=0.01103 val_loss=0.06866 train_macro_f1=0.9976 val_macro_f1=0.9825

2026-06-11 20:40:01,923 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_2/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:40:06,317 | INFO | Fold completed strategy=partial_finetune fold=2 test_macro_f1=0.9085 duration=43.2s

2026-06-11 20:40:06,319 | INFO | Finished strategy=partial_finetune fold=2 status=OK

2026-06-11 20:40:06,337 | INFO | Loaded pretrained backbone.

2026-06-11 20:40:06,338 | INFO | Parameters trainable=448773 total=512933 ratio=0.8749

2026-06-11 20:40:07,145 | INFO | Epoch 001/050 train_loss=0.94191 val_loss=0.65930 train_macro_f1=0.6131 val_macro_f1=0.8027

2026-06-11 20:40:08,002 | INFO | Epoch 002/050 train_loss=0.54361 val_loss=0.46038 train_macro_f1=0.8644 val_macro_f1=0.8666

2026-06-11 20:40:08,820 | INFO | Epoch 003/050 train_loss=0.39004 val_loss=0.32513 train_macro_f1=0.8907 val_macro_f1=0.9260

2026-06-11 20:40:09,634 | INFO | Epoch 004/050 train_loss=0.31328 val_loss=0.32480 train_macro_f1=0.9171 val_macro_f1=0.9076

2026-06-11 20:40:10,454 | INFO | Epoch 005/050 train_loss=0.26657 val_loss=0.37331 train_macro_f1=0.9270 val_macro_f1=0.8740

2026-06-11 20:40:10,480 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:40:11,261 | INFO | Epoch 006/050 train_loss=0.21921 val_loss=0.17174 train_macro_f1=0.9446 val_macro_f1=0.9652

2026-06-11 20:40:12,090 | INFO | Epoch 007/050 train_loss=0.20386 val_loss=0.18171 train_macro_f1=0.9420 val_macro_f1=0.9528

2026-06-11 20:40:12,894 | INFO | Epoch 008/050 train_loss=0.17880 val_loss=0.14349 train_macro_f1=0.9501 val_macro_f1=0.9602

2026-06-11 20:40:13,697 | INFO | Epoch 009/050 train_loss=0.16487 val_loss=0.25224 train_macro_f1=0.9614 val_macro_f1=0.9117

2026-06-11 20:40:14,488 | INFO | Epoch 010/050 train_loss=0.14928 val_loss=0.20167 train_macro_f1=0.9562 val_macro_f1=0.9245

2026-06-11 20:40:14,512 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:40:15,304 | INFO | Epoch 011/050 train_loss=0.13722 val_loss=0.12620 train_macro_f1=0.9642 val_macro_f1=0.9671

2026-06-11 20:40:16,123 | INFO | Epoch 012/050 train_loss=0.11036 val_loss=0.18383 train_macro_f1=0.9718 val_macro_f1=0.9441

2026-06-11 20:40:16,928 | INFO | Epoch 013/050 train_loss=0.11791 val_loss=0.14230 train_macro_f1=0.9673 val_macro_f1=0.9586

2026-06-11 20:40:17,723 | INFO | Epoch 014/050 train_loss=0.09077 val_loss=0.13518 train_macro_f1=0.9762 val_macro_f1=0.9590

2026-06-11 20:40:18,520 | INFO | Epoch 015/050 train_loss=0.08805 val_loss=0.06833 train_macro_f1=0.9776 val_macro_f1=0.9868

2026-06-11 20:40:18,568 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:40:19,364 | INFO | Epoch 016/050 train_loss=0.08042 val_loss=0.09246 train_macro_f1=0.9789 val_macro_f1=0.9680

2026-06-11 20:40:20,164 | INFO | Epoch 017/050 train_loss=0.06191 val_loss=0.18131 train_macro_f1=0.9841 val_macro_f1=0.9291

2026-06-11 20:40:20,959 | INFO | Epoch 018/050 train_loss=0.07119 val_loss=0.05316 train_macro_f1=0.9822 val_macro_f1=0.9890

2026-06-11 20:40:21,782 | INFO | Epoch 019/050 train_loss=0.05091 val_loss=0.21290 train_macro_f1=0.9860 val_macro_f1=0.9305

2026-06-11 20:40:22,579 | INFO | Epoch 020/050 train_loss=0.04434 val_loss=0.11167 train_macro_f1=0.9897 val_macro_f1=0.9567

2026-06-11 20:40:22,604 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:40:23,387 | INFO | Epoch 021/050 train_loss=0.03803 val_loss=0.13936 train_macro_f1=0.9884 val_macro_f1=0.9529

2026-06-11 20:40:24,190 | INFO | Epoch 022/050 train_loss=0.04262 val_loss=0.19852 train_macro_f1=0.9890 val_macro_f1=0.9371

2026-06-11 20:40:24,977 | INFO | Epoch 023/050 train_loss=0.05970 val_loss=0.01583 train_macro_f1=0.9850 val_macro_f1=1.0000

2026-06-11 20:40:25,799 | INFO | Epoch 024/050 train_loss=0.03732 val_loss=0.03073 train_macro_f1=0.9892 val_macro_f1=0.9909

2026-06-11 20:40:26,593 | INFO | Epoch 025/050 train_loss=0.03371 val_loss=0.33065 train_macro_f1=0.9934 val_macro_f1=0.9129

2026-06-11 20:40:26,619 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:40:27,407 | INFO | Epoch 026/050 train_loss=0.04365 val_loss=0.09966 train_macro_f1=0.9894 val_macro_f1=0.9666

2026-06-11 20:40:28,205 | INFO | Epoch 027/050 train_loss=0.02211 val_loss=0.01584 train_macro_f1=0.9940 val_macro_f1=0.9953

2026-06-11 20:40:29,018 | INFO | Epoch 028/050 train_loss=0.02308 val_loss=0.01569 train_macro_f1=0.9935 val_macro_f1=0.9982

2026-06-11 20:40:29,828 | INFO | Epoch 029/050 train_loss=0.03106 val_loss=0.05744 train_macro_f1=0.9917 val_macro_f1=0.9830

2026-06-11 20:40:30,629 | INFO | Epoch 030/050 train_loss=0.01232 val_loss=0.00985 train_macro_f1=0.9976 val_macro_f1=0.9976

2026-06-11 20:40:30,668 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:40:31,454 | INFO | Epoch 031/050 train_loss=0.01357 val_loss=0.03419 train_macro_f1=0.9977 val_macro_f1=0.9927

2026-06-11 20:40:32,254 | INFO | Epoch 032/050 train_loss=0.00820 val_loss=0.06705 train_macro_f1=0.9980 val_macro_f1=0.9798

2026-06-11 20:40:33,051 | INFO | Epoch 033/050 train_loss=0.01436 val_loss=0.04234 train_macro_f1=0.9974 val_macro_f1=0.9872

2026-06-11 20:40:33,842 | INFO | Epoch 034/050 train_loss=0.01000 val_loss=0.01097 train_macro_f1=0.9984 val_macro_f1=0.9982

2026-06-11 20:40:34,640 | INFO | Epoch 035/050 train_loss=0.00899 val_loss=0.02875 train_macro_f1=0.9972 val_macro_f1=0.9927

2026-06-11 20:40:34,670 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:40:35,451 | INFO | Epoch 036/050 train_loss=0.00925 val_loss=0.01365 train_macro_f1=0.9961 val_macro_f1=0.9982

2026-06-11 20:40:36,242 | INFO | Epoch 037/050 train_loss=0.00692 val_loss=0.02223 train_macro_f1=0.9990 val_macro_f1=0.9945

2026-06-11 20:40:37,035 | INFO | Epoch 038/050 train_loss=0.01216 val_loss=0.06238 train_macro_f1=0.9959 val_macro_f1=0.9798

2026-06-11 20:40:37,835 | INFO | Epoch 039/050 train_loss=0.00982 val_loss=0.01322 train_macro_f1=0.9965 val_macro_f1=0.9982

2026-06-11 20:40:38,625 | INFO | Epoch 040/050 train_loss=0.00772 val_loss=0.01126 train_macro_f1=0.9967 val_macro_f1=0.9982

2026-06-11 20:40:38,650 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:40:39,446 | INFO | Epoch 041/050 train_loss=0.00866 val_loss=0.01721 train_macro_f1=0.9979 val_macro_f1=0.9963

2026-06-11 20:40:40,236 | INFO | Epoch 042/050 train_loss=0.00949 val_loss=0.02822 train_macro_f1=0.9970 val_macro_f1=0.9927

2026-06-11 20:40:41,030 | INFO | Epoch 043/050 train_loss=0.00950 val_loss=0.01294 train_macro_f1=0.9976 val_macro_f1=0.9982

2026-06-11 20:40:41,846 | INFO | Epoch 044/050 train_loss=0.00953 val_loss=0.03953 train_macro_f1=0.9977 val_macro_f1=0.9909

2026-06-11 20:40:42,635 | INFO | Epoch 045/050 train_loss=0.00586 val_loss=0.04200 train_macro_f1=0.9991 val_macro_f1=0.9890

2026-06-11 20:40:42,660 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:40:43,456 | INFO | Epoch 046/050 train_loss=0.00438 val_loss=0.02659 train_macro_f1=0.9995 val_macro_f1=0.9927

2026-06-11 20:40:44,256 | INFO | Epoch 047/050 train_loss=0.00398 val_loss=0.02182 train_macro_f1=0.9995 val_macro_f1=0.9927

2026-06-11 20:40:45,060 | INFO | Epoch 048/050 train_loss=0.00416 val_loss=0.01639 train_macro_f1=0.9986 val_macro_f1=0.9982

2026-06-11 20:40:45,852 | INFO | Epoch 049/050 train_loss=0.00395 val_loss=0.01977 train_macro_f1=0.9995 val_macro_f1=0.9963

2026-06-11 20:40:46,652 | INFO | Epoch 050/050 train_loss=0.01050 val_loss=0.02245 train_macro_f1=0.9954 val_macro_f1=0.9927

2026-06-11 20:40:46,677 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_3/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:40:51,354 | INFO | Fold completed strategy=partial_finetune fold=3 test_macro_f1=0.9010 duration=45.0s

2026-06-11 20:40:51,356 | INFO | Finished strategy=partial_finetune fold=3 status=OK

2026-06-11 20:40:51,374 | INFO | Loaded pretrained backbone.

2026-06-11 20:40:51,375 | INFO | Parameters trainable=448773 total=512933 ratio=0.8749

2026-06-11 20:40:52,223 | INFO | Epoch 001/050 train_loss=0.95378 val_loss=0.65200 train_macro_f1=0.5240 val_macro_f1=0.8222

2026-06-11 20:40:53,086 | INFO | Epoch 002/050 train_loss=0.56015 val_loss=0.43584 train_macro_f1=0.8189 val_macro_f1=0.8980

2026-06-11 20:40:53,962 | INFO | Epoch 003/050 train_loss=0.39209 val_loss=0.39953 train_macro_f1=0.8892 val_macro_f1=0.8905

2026-06-11 20:40:54,800 | INFO | Epoch 004/050 train_loss=0.31485 val_loss=0.28596 train_macro_f1=0.9212 val_macro_f1=0.9290

2026-06-11 20:40:55,639 | INFO | Epoch 005/050 train_loss=0.24970 val_loss=0.28571 train_macro_f1=0.9292 val_macro_f1=0.9285

2026-06-11 20:40:55,677 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:40:56,484 | INFO | Epoch 006/050 train_loss=0.20662 val_loss=0.23847 train_macro_f1=0.9454 val_macro_f1=0.9248

2026-06-11 20:40:57,317 | INFO | Epoch 007/050 train_loss=0.20730 val_loss=0.18694 train_macro_f1=0.9399 val_macro_f1=0.9482

2026-06-11 20:40:58,165 | INFO | Epoch 008/050 train_loss=0.18480 val_loss=0.27678 train_macro_f1=0.9538 val_macro_f1=0.9182

2026-06-11 20:40:58,989 | INFO | Epoch 009/050 train_loss=0.15946 val_loss=0.24601 train_macro_f1=0.9569 val_macro_f1=0.9093

2026-06-11 20:40:59,817 | INFO | Epoch 010/050 train_loss=0.14001 val_loss=0.14612 train_macro_f1=0.9652 val_macro_f1=0.9688

2026-06-11 20:40:59,868 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:41:00,693 | INFO | Epoch 011/050 train_loss=0.12549 val_loss=0.10566 train_macro_f1=0.9691 val_macro_f1=0.9684

2026-06-11 20:41:01,526 | INFO | Epoch 012/050 train_loss=0.12378 val_loss=0.18105 train_macro_f1=0.9592 val_macro_f1=0.9522

2026-06-11 20:41:02,350 | INFO | Epoch 013/050 train_loss=0.10999 val_loss=0.20106 train_macro_f1=0.9724 val_macro_f1=0.9342

2026-06-11 20:41:03,177 | INFO | Epoch 014/050 train_loss=0.09681 val_loss=0.14772 train_macro_f1=0.9757 val_macro_f1=0.9574

2026-06-11 20:41:04,002 | INFO | Epoch 015/050 train_loss=0.07580 val_loss=0.21366 train_macro_f1=0.9802 val_macro_f1=0.9361

2026-06-11 20:41:04,027 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:41:04,844 | INFO | Epoch 016/050 train_loss=0.08545 val_loss=0.07691 train_macro_f1=0.9766 val_macro_f1=0.9747

2026-06-11 20:41:05,694 | INFO | Epoch 017/050 train_loss=0.07605 val_loss=0.10044 train_macro_f1=0.9780 val_macro_f1=0.9723

2026-06-11 20:41:06,525 | INFO | Epoch 018/050 train_loss=0.04924 val_loss=0.07362 train_macro_f1=0.9900 val_macro_f1=0.9778

2026-06-11 20:41:07,393 | INFO | Epoch 019/050 train_loss=0.06390 val_loss=0.12405 train_macro_f1=0.9804 val_macro_f1=0.9593

2026-06-11 20:41:08,219 | INFO | Epoch 020/050 train_loss=0.04590 val_loss=0.06964 train_macro_f1=0.9876 val_macro_f1=0.9772

2026-06-11 20:41:08,257 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:41:09,073 | INFO | Epoch 021/050 train_loss=0.04812 val_loss=0.15285 train_macro_f1=0.9899 val_macro_f1=0.9485

2026-06-11 20:41:09,899 | INFO | Epoch 022/050 train_loss=0.05776 val_loss=0.02318 train_macro_f1=0.9831 val_macro_f1=0.9887

2026-06-11 20:41:10,748 | INFO | Epoch 023/050 train_loss=0.03696 val_loss=0.07010 train_macro_f1=0.9895 val_macro_f1=0.9783

2026-06-11 20:41:11,571 | INFO | Epoch 024/050 train_loss=0.04181 val_loss=0.05576 train_macro_f1=0.9881 val_macro_f1=0.9874

2026-06-11 20:41:12,399 | INFO | Epoch 025/050 train_loss=0.03168 val_loss=0.05382 train_macro_f1=0.9897 val_macro_f1=0.9807

2026-06-11 20:41:12,424 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:41:13,239 | INFO | Epoch 026/050 train_loss=0.03529 val_loss=0.02555 train_macro_f1=0.9911 val_macro_f1=0.9898

2026-06-11 20:41:14,078 | INFO | Epoch 027/050 train_loss=0.02749 val_loss=0.05105 train_macro_f1=0.9926 val_macro_f1=0.9862

2026-06-11 20:41:14,902 | INFO | Epoch 028/050 train_loss=0.02531 val_loss=0.03858 train_macro_f1=0.9920 val_macro_f1=0.9887

2026-06-11 20:41:15,728 | INFO | Epoch 029/050 train_loss=0.03322 val_loss=0.03654 train_macro_f1=0.9879 val_macro_f1=0.9903

2026-06-11 20:41:16,564 | INFO | Epoch 030/050 train_loss=0.02015 val_loss=0.04990 train_macro_f1=0.9953 val_macro_f1=0.9801

2026-06-11 20:41:16,591 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:41:17,415 | INFO | Epoch 031/050 train_loss=0.02751 val_loss=0.01939 train_macro_f1=0.9923 val_macro_f1=0.9964

2026-06-11 20:41:18,258 | INFO | Epoch 032/050 train_loss=0.01266 val_loss=0.06403 train_macro_f1=0.9972 val_macro_f1=0.9807

2026-06-11 20:41:19,084 | INFO | Epoch 033/050 train_loss=0.01765 val_loss=0.00453 train_macro_f1=0.9965 val_macro_f1=1.0000

2026-06-11 20:41:19,934 | INFO | Epoch 034/050 train_loss=0.01250 val_loss=0.04808 train_macro_f1=0.9962 val_macro_f1=0.9885

2026-06-11 20:41:20,759 | INFO | Epoch 035/050 train_loss=0.01024 val_loss=0.09257 train_macro_f1=0.9982 val_macro_f1=0.9770

2026-06-11 20:41:20,789 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:41:21,616 | INFO | Epoch 036/050 train_loss=0.01557 val_loss=0.00354 train_macro_f1=0.9939 val_macro_f1=0.9976

2026-06-11 20:41:22,457 | INFO | Epoch 037/050 train_loss=0.02296 val_loss=0.03438 train_macro_f1=0.9935 val_macro_f1=0.9885

2026-06-11 20:41:23,287 | INFO | Epoch 038/050 train_loss=0.01146 val_loss=0.00815 train_macro_f1=0.9970 val_macro_f1=0.9976

2026-06-11 20:41:24,112 | INFO | Epoch 039/050 train_loss=0.00992 val_loss=0.01454 train_macro_f1=0.9966 val_macro_f1=0.9964

2026-06-11 20:41:24,949 | INFO | Epoch 040/050 train_loss=0.00625 val_loss=0.00192 train_macro_f1=0.9982 val_macro_f1=1.0000

2026-06-11 20:41:24,986 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:41:25,806 | INFO | Epoch 041/050 train_loss=0.00289 val_loss=0.01063 train_macro_f1=0.9988 val_macro_f1=0.9982

2026-06-11 20:41:26,646 | INFO | Epoch 042/050 train_loss=0.00865 val_loss=0.00436 train_macro_f1=0.9973 val_macro_f1=0.9976

2026-06-11 20:41:27,460 | INFO | Epoch 043/050 train_loss=0.01014 val_loss=0.03297 train_macro_f1=0.9966 val_macro_f1=0.9835

2026-06-11 20:41:28,284 | INFO | Epoch 044/050 train_loss=0.00354 val_loss=0.02109 train_macro_f1=0.9983 val_macro_f1=0.9945

2026-06-11 20:41:29,104 | INFO | Epoch 045/050 train_loss=0.00446 val_loss=0.00196 train_macro_f1=0.9986 val_macro_f1=1.0000

2026-06-11 20:41:29,129 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:41:29,941 | INFO | Epoch 046/050 train_loss=0.00206 val_loss=0.00498 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:41:30,768 | INFO | Epoch 047/050 train_loss=0.00706 val_loss=0.00480 train_macro_f1=0.9986 val_macro_f1=1.0000

2026-06-11 20:41:31,591 | INFO | Epoch 048/050 train_loss=0.00213 val_loss=0.00110 train_macro_f1=0.9995 val_macro_f1=1.0000

2026-06-11 20:41:32,440 | INFO | Epoch 049/050 train_loss=0.00295 val_loss=0.00968 train_macro_f1=0.9995 val_macro_f1=1.0000

2026-06-11 20:41:33,262 | INFO | Epoch 050/050 train_loss=0.00231 val_loss=0.00227 train_macro_f1=0.9994 val_macro_f1=1.0000

2026-06-11 20:41:33,287 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_4/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:41:37,941 | INFO | Fold completed strategy=partial_finetune fold=4 test_macro_f1=0.8856 duration=46.6s

2026-06-11 20:41:37,943 | INFO | Finished strategy=partial_finetune fold=4 status=OK

2026-06-11 20:41:37,966 | INFO | Loaded pretrained backbone.

2026-06-11 20:41:37,967 | INFO | Parameters trainable=448773 total=512933 ratio=0.8749

2026-06-11 20:41:38,897 | INFO | Epoch 001/050 train_loss=0.91794 val_loss=0.65629 train_macro_f1=0.5334 val_macro_f1=0.7377

2026-06-11 20:41:39,844 | INFO | Epoch 002/050 train_loss=0.54156 val_loss=0.46457 train_macro_f1=0.7935 val_macro_f1=0.8852

2026-06-11 20:41:40,772 | INFO | Epoch 003/050 train_loss=0.38845 val_loss=0.40562 train_macro_f1=0.8995 val_macro_f1=0.8836

2026-06-11 20:41:41,683 | INFO | Epoch 004/050 train_loss=0.32106 val_loss=0.39028 train_macro_f1=0.9200 val_macro_f1=0.8700

2026-06-11 20:41:42,568 | INFO | Epoch 005/050 train_loss=0.26004 val_loss=0.24007 train_macro_f1=0.9400 val_macro_f1=0.9426

2026-06-11 20:41:42,618 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:41:43,468 | INFO | Epoch 006/050 train_loss=0.22197 val_loss=0.31554 train_macro_f1=0.9395 val_macro_f1=0.8802

2026-06-11 20:41:44,321 | INFO | Epoch 007/050 train_loss=0.20459 val_loss=0.31795 train_macro_f1=0.9518 val_macro_f1=0.9082

2026-06-11 20:41:45,192 | INFO | Epoch 008/050 train_loss=0.17224 val_loss=0.27805 train_macro_f1=0.9608 val_macro_f1=0.9096

2026-06-11 20:41:46,050 | INFO | Epoch 009/050 train_loss=0.14095 val_loss=0.24102 train_macro_f1=0.9642 val_macro_f1=0.9173

2026-06-11 20:41:46,913 | INFO | Epoch 010/050 train_loss=0.12722 val_loss=0.28289 train_macro_f1=0.9656 val_macro_f1=0.8881

2026-06-11 20:41:46,940 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:41:47,775 | INFO | Epoch 011/050 train_loss=0.10542 val_loss=0.19548 train_macro_f1=0.9729 val_macro_f1=0.9333

2026-06-11 20:41:48,642 | INFO | Epoch 012/050 train_loss=0.10342 val_loss=0.16189 train_macro_f1=0.9732 val_macro_f1=0.9547

2026-06-11 20:41:49,518 | INFO | Epoch 013/050 train_loss=0.08789 val_loss=0.24874 train_macro_f1=0.9755 val_macro_f1=0.9122

2026-06-11 20:41:50,365 | INFO | Epoch 014/050 train_loss=0.07697 val_loss=0.11395 train_macro_f1=0.9816 val_macro_f1=0.9638

2026-06-11 20:41:51,238 | INFO | Epoch 015/050 train_loss=0.08194 val_loss=0.17994 train_macro_f1=0.9807 val_macro_f1=0.9419

2026-06-11 20:41:51,263 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:41:52,103 | INFO | Epoch 016/050 train_loss=0.08328 val_loss=0.22133 train_macro_f1=0.9759 val_macro_f1=0.9256

2026-06-11 20:41:52,947 | INFO | Epoch 017/050 train_loss=0.06559 val_loss=0.13117 train_macro_f1=0.9867 val_macro_f1=0.9695

2026-06-11 20:41:53,812 | INFO | Epoch 018/050 train_loss=0.06168 val_loss=0.17562 train_macro_f1=0.9803 val_macro_f1=0.9432

2026-06-11 20:41:54,665 | INFO | Epoch 019/050 train_loss=0.05585 val_loss=0.14951 train_macro_f1=0.9860 val_macro_f1=0.9597

2026-06-11 20:41:55,512 | INFO | Epoch 020/050 train_loss=0.06095 val_loss=0.09873 train_macro_f1=0.9850 val_macro_f1=0.9788

2026-06-11 20:41:55,561 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:41:56,411 | INFO | Epoch 021/050 train_loss=0.07867 val_loss=0.06592 train_macro_f1=0.9829 val_macro_f1=0.9867

2026-06-11 20:41:57,281 | INFO | Epoch 022/050 train_loss=0.06360 val_loss=0.16766 train_macro_f1=0.9812 val_macro_f1=0.9505

2026-06-11 20:41:58,127 | INFO | Epoch 023/050 train_loss=0.03811 val_loss=0.12640 train_macro_f1=0.9898 val_macro_f1=0.9657

2026-06-11 20:41:58,968 | INFO | Epoch 024/050 train_loss=0.03657 val_loss=0.07311 train_macro_f1=0.9906 val_macro_f1=0.9837

2026-06-11 20:41:59,825 | INFO | Epoch 025/050 train_loss=0.05350 val_loss=0.12988 train_macro_f1=0.9840 val_macro_f1=0.9606

2026-06-11 20:41:59,852 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:42:00,692 | INFO | Epoch 026/050 train_loss=0.04991 val_loss=0.22395 train_macro_f1=0.9863 val_macro_f1=0.9393

2026-06-11 20:42:01,528 | INFO | Epoch 027/050 train_loss=0.03394 val_loss=0.13419 train_macro_f1=0.9917 val_macro_f1=0.9605

2026-06-11 20:42:02,373 | INFO | Epoch 028/050 train_loss=0.03499 val_loss=0.18253 train_macro_f1=0.9932 val_macro_f1=0.9472

2026-06-11 20:42:03,215 | INFO | Epoch 029/050 train_loss=0.03355 val_loss=0.06600 train_macro_f1=0.9912 val_macro_f1=0.9867

2026-06-11 20:42:04,076 | INFO | Epoch 030/050 train_loss=0.03488 val_loss=0.08288 train_macro_f1=0.9908 val_macro_f1=0.9811

2026-06-11 20:42:04,102 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:42:04,938 | INFO | Epoch 031/050 train_loss=0.03170 val_loss=0.10702 train_macro_f1=0.9938 val_macro_f1=0.9663

2026-06-11 20:42:05,784 | INFO | Epoch 032/050 train_loss=0.02409 val_loss=0.19509 train_macro_f1=0.9945 val_macro_f1=0.9471

2026-06-11 20:42:06,631 | INFO | Epoch 033/050 train_loss=0.03035 val_loss=0.12236 train_macro_f1=0.9924 val_macro_f1=0.9597

2026-06-11 20:42:07,483 | INFO | Epoch 034/050 train_loss=0.02568 val_loss=0.09022 train_macro_f1=0.9954 val_macro_f1=0.9775

2026-06-11 20:42:08,358 | INFO | Epoch 035/050 train_loss=0.02898 val_loss=0.12562 train_macro_f1=0.9959 val_macro_f1=0.9578

2026-06-11 20:42:08,382 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:42:09,216 | INFO | Epoch 036/050 train_loss=0.03598 val_loss=0.09974 train_macro_f1=0.9891 val_macro_f1=0.9737

2026-06-11 20:42:10,066 | INFO | Epoch 037/050 train_loss=0.01916 val_loss=0.12987 train_macro_f1=0.9967 val_macro_f1=0.9567

2026-06-11 20:42:10,904 | INFO | Epoch 038/050 train_loss=0.02256 val_loss=0.11670 train_macro_f1=0.9962 val_macro_f1=0.9606

2026-06-11 20:42:11,756 | INFO | Epoch 039/050 train_loss=0.01861 val_loss=0.12657 train_macro_f1=0.9964 val_macro_f1=0.9605

2026-06-11 20:42:12,599 | INFO | Epoch 040/050 train_loss=0.01974 val_loss=0.08616 train_macro_f1=0.9950 val_macro_f1=0.9737

2026-06-11 20:42:12,624 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:42:13,477 | INFO | Epoch 041/050 train_loss=0.01984 val_loss=0.08041 train_macro_f1=0.9961 val_macro_f1=0.9830

2026-06-11 20:42:14,328 | INFO | Epoch 042/050 train_loss=0.02387 val_loss=0.12054 train_macro_f1=0.9938 val_macro_f1=0.9625

2026-06-11 20:42:15,195 | INFO | Epoch 043/050 train_loss=0.02442 val_loss=0.09459 train_macro_f1=0.9937 val_macro_f1=0.9737

2026-06-11 20:42:16,047 | INFO | Epoch 044/050 train_loss=0.01762 val_loss=0.10195 train_macro_f1=0.9958 val_macro_f1=0.9700

2026-06-11 20:42:16,897 | INFO | Epoch 045/050 train_loss=0.01717 val_loss=0.11134 train_macro_f1=0.9971 val_macro_f1=0.9681

2026-06-11 20:42:16,922 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:42:17,752 | INFO | Epoch 046/050 train_loss=0.01654 val_loss=0.10735 train_macro_f1=0.9976 val_macro_f1=0.9677

2026-06-11 20:42:18,597 | INFO | Epoch 047/050 train_loss=0.01823 val_loss=0.10305 train_macro_f1=0.9962 val_macro_f1=0.9737

2026-06-11 20:42:19,438 | INFO | Epoch 048/050 train_loss=0.01896 val_loss=0.10577 train_macro_f1=0.9944 val_macro_f1=0.9681

2026-06-11 20:42:20,278 | INFO | Epoch 049/050 train_loss=0.01282 val_loss=0.09091 train_macro_f1=0.9986 val_macro_f1=0.9793

2026-06-11 20:42:21,125 | INFO | Epoch 050/050 train_loss=0.01382 val_loss=0.10209 train_macro_f1=0.9962 val_macro_f1=0.9719

2026-06-11 20:42:21,150 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/partial_finetune/fold_5/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:42:25,638 | INFO | Fold completed strategy=partial_finetune fold=5 test_macro_f1=0.8688 duration=47.7s

2026-06-11 20:42:25,640 | INFO | Finished strategy=partial_finetune fold=5 status=OK

2026-06-11 20:42:25,641 | INFO | Strategy started: full_finetune

2026-06-11 20:42:25,663 | INFO | Loaded pretrained full model.

2026-06-11 20:42:25,664 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:42:26,746 | INFO | Epoch 001/050 train_loss=0.51945 val_loss=0.24168 train_macro_f1=0.7985 val_macro_f1=0.9139

2026-06-11 20:42:27,847 | INFO | Epoch 002/050 train_loss=0.29781 val_loss=0.19721 train_macro_f1=0.9026 val_macro_f1=0.9323

2026-06-11 20:42:28,930 | INFO | Epoch 003/050 train_loss=0.18651 val_loss=0.13823 train_macro_f1=0.9478 val_macro_f1=0.9465

2026-06-11 20:42:30,056 | INFO | Epoch 004/050 train_loss=0.14767 val_loss=0.11903 train_macro_f1=0.9518 val_macro_f1=0.9716

2026-06-11 20:42:31,172 | INFO | Epoch 005/050 train_loss=0.10945 val_loss=0.07301 train_macro_f1=0.9675 val_macro_f1=0.9811

2026-06-11 20:42:31,234 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:42:32,272 | INFO | Epoch 006/050 train_loss=0.10723 val_loss=0.08866 train_macro_f1=0.9723 val_macro_f1=0.9660

2026-06-11 20:42:33,342 | INFO | Epoch 007/050 train_loss=0.08571 val_loss=0.05085 train_macro_f1=0.9741 val_macro_f1=0.9927

2026-06-11 20:42:34,427 | INFO | Epoch 008/050 train_loss=0.10285 val_loss=0.04633 train_macro_f1=0.9676 val_macro_f1=0.9878

2026-06-11 20:42:35,499 | INFO | Epoch 009/050 train_loss=0.05249 val_loss=0.08293 train_macro_f1=0.9849 val_macro_f1=0.9816

2026-06-11 20:42:36,561 | INFO | Epoch 010/050 train_loss=0.05085 val_loss=0.07969 train_macro_f1=0.9877 val_macro_f1=0.9721

2026-06-11 20:42:36,592 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:42:37,643 | INFO | Epoch 011/050 train_loss=0.05990 val_loss=0.07680 train_macro_f1=0.9818 val_macro_f1=0.9737

2026-06-11 20:42:38,718 | INFO | Epoch 012/050 train_loss=0.05024 val_loss=0.02591 train_macro_f1=0.9852 val_macro_f1=0.9916

2026-06-11 20:42:39,807 | INFO | Epoch 013/050 train_loss=0.05668 val_loss=0.01799 train_macro_f1=0.9867 val_macro_f1=0.9982

2026-06-11 20:42:40,912 | INFO | Epoch 014/050 train_loss=0.04416 val_loss=0.02230 train_macro_f1=0.9894 val_macro_f1=0.9927

2026-06-11 20:42:41,974 | INFO | Epoch 015/050 train_loss=0.01854 val_loss=0.00950 train_macro_f1=0.9964 val_macro_f1=1.0000

2026-06-11 20:42:42,036 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:42:43,080 | INFO | Epoch 016/050 train_loss=0.02570 val_loss=0.04612 train_macro_f1=0.9899 val_macro_f1=0.9872

2026-06-11 20:42:44,155 | INFO | Epoch 017/050 train_loss=0.01830 val_loss=0.01211 train_macro_f1=0.9950 val_macro_f1=0.9982

2026-06-11 20:42:45,214 | INFO | Epoch 018/050 train_loss=0.01707 val_loss=0.03963 train_macro_f1=0.9958 val_macro_f1=0.9909

2026-06-11 20:42:46,280 | INFO | Epoch 019/050 train_loss=0.01697 val_loss=0.05031 train_macro_f1=0.9949 val_macro_f1=0.9860

2026-06-11 20:42:47,344 | INFO | Epoch 020/050 train_loss=0.01475 val_loss=0.00967 train_macro_f1=0.9955 val_macro_f1=0.9963

2026-06-11 20:42:47,373 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:42:48,413 | INFO | Epoch 021/050 train_loss=0.01304 val_loss=0.06028 train_macro_f1=0.9947 val_macro_f1=0.9769

2026-06-11 20:42:49,489 | INFO | Epoch 022/050 train_loss=0.00702 val_loss=0.02292 train_macro_f1=0.9984 val_macro_f1=0.9927

2026-06-11 20:42:50,554 | INFO | Epoch 023/050 train_loss=0.01009 val_loss=0.00666 train_macro_f1=0.9974 val_macro_f1=0.9982

2026-06-11 20:42:51,632 | INFO | Epoch 024/050 train_loss=0.00972 val_loss=0.00406 train_macro_f1=0.9972 val_macro_f1=1.0000

2026-06-11 20:42:52,735 | INFO | Epoch 025/050 train_loss=0.00228 val_loss=0.00716 train_macro_f1=1.0000 val_macro_f1=0.9950

2026-06-11 20:42:52,764 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:42:53,810 | INFO | Epoch 026/050 train_loss=0.00330 val_loss=0.00487 train_macro_f1=0.9994 val_macro_f1=1.0000

2026-06-11 20:42:54,880 | INFO | Epoch 027/050 train_loss=0.00230 val_loss=0.00375 train_macro_f1=0.9995 val_macro_f1=1.0000

2026-06-11 20:42:55,970 | INFO | Epoch 028/050 train_loss=0.00314 val_loss=0.00488 train_macro_f1=0.9995 val_macro_f1=1.0000

2026-06-11 20:42:57,025 | INFO | Epoch 029/050 train_loss=0.00239 val_loss=0.00480 train_macro_f1=0.9995 val_macro_f1=0.9982

2026-06-11 20:42:58,074 | INFO | Epoch 030/050 train_loss=0.00308 val_loss=0.01774 train_macro_f1=0.9995 val_macro_f1=0.9945

2026-06-11 20:42:58,103 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:42:59,142 | INFO | Epoch 031/050 train_loss=0.00156 val_loss=0.00512 train_macro_f1=0.9995 val_macro_f1=0.9982

2026-06-11 20:43:00,189 | INFO | Epoch 032/050 train_loss=0.00495 val_loss=0.00379 train_macro_f1=0.9978 val_macro_f1=1.0000

2026-06-11 20:43:01,259 | INFO | Epoch 033/050 train_loss=0.00075 val_loss=0.00988 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:02,325 | INFO | Epoch 034/050 train_loss=0.00109 val_loss=0.00750 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:03,400 | INFO | Epoch 035/050 train_loss=0.00111 val_loss=0.00536 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:03,428 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:43:04,460 | INFO | Epoch 036/050 train_loss=0.00382 val_loss=0.00299 train_macro_f1=0.9990 val_macro_f1=1.0000

2026-06-11 20:43:05,553 | INFO | Epoch 037/050 train_loss=0.00093 val_loss=0.00428 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:06,611 | INFO | Epoch 038/050 train_loss=0.00108 val_loss=0.00309 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:07,675 | INFO | Epoch 039/050 train_loss=0.00202 val_loss=0.00359 train_macro_f1=0.9995 val_macro_f1=1.0000

2026-06-11 20:43:08,730 | INFO | Epoch 040/050 train_loss=0.00161 val_loss=0.00370 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:08,759 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:43:09,812 | INFO | Epoch 041/050 train_loss=0.00051 val_loss=0.00332 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:10,870 | INFO | Epoch 042/050 train_loss=0.00384 val_loss=0.00531 train_macro_f1=0.9990 val_macro_f1=1.0000

2026-06-11 20:43:11,930 | INFO | Epoch 043/050 train_loss=0.00078 val_loss=0.00445 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:12,982 | INFO | Epoch 044/050 train_loss=0.00066 val_loss=0.00531 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:14,047 | INFO | Epoch 045/050 train_loss=0.00233 val_loss=0.00390 train_macro_f1=0.9985 val_macro_f1=0.9982

2026-06-11 20:43:14,076 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:43:15,123 | INFO | Epoch 046/050 train_loss=0.00339 val_loss=0.00541 train_macro_f1=0.9990 val_macro_f1=1.0000

2026-06-11 20:43:16,177 | INFO | Epoch 047/050 train_loss=0.00084 val_loss=0.00314 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:17,225 | INFO | Epoch 048/050 train_loss=0.00154 val_loss=0.00358 train_macro_f1=0.9995 val_macro_f1=1.0000

2026-06-11 20:43:18,290 | INFO | Epoch 049/050 train_loss=0.00100 val_loss=0.00435 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:19,346 | INFO | Epoch 050/050 train_loss=0.00072 val_loss=0.00551 train_macro_f1=1.0000 val_macro_f1=1.0000

2026-06-11 20:43:19,378 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_1/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:43:23,918 | INFO | Fold completed strategy=full_finetune fold=1 test_macro_f1=0.8236 duration=58.3s

2026-06-11 20:43:23,920 | INFO | Finished strategy=full_finetune fold=1 status=OK

2026-06-11 20:43:23,942 | INFO | Loaded pretrained full model.

2026-06-11 20:43:23,943 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:43:25,043 | INFO | Epoch 001/050 train_loss=0.54838 val_loss=0.37277 train_macro_f1=0.7866 val_macro_f1=0.8790

2026-06-11 20:43:26,192 | INFO | Epoch 002/050 train_loss=0.30368 val_loss=0.32737 train_macro_f1=0.9043 val_macro_f1=0.8812

2026-06-11 20:43:27,305 | INFO | Epoch 003/050 train_loss=0.20353 val_loss=0.17839 train_macro_f1=0.9435 val_macro_f1=0.9519

2026-06-11 20:43:28,443 | INFO | Epoch 004/050 train_loss=0.17727 val_loss=0.20857 train_macro_f1=0.9427 val_macro_f1=0.9374

2026-06-11 20:43:29,531 | INFO | Epoch 005/050 train_loss=0.13721 val_loss=0.27781 train_macro_f1=0.9572 val_macro_f1=0.9148

2026-06-11 20:43:29,562 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:43:30,654 | INFO | Epoch 006/050 train_loss=0.10509 val_loss=0.20334 train_macro_f1=0.9680 val_macro_f1=0.9270

2026-06-11 20:43:31,744 | INFO | Epoch 007/050 train_loss=0.08532 val_loss=0.23688 train_macro_f1=0.9777 val_macro_f1=0.9306

2026-06-11 20:43:32,847 | INFO | Epoch 008/050 train_loss=0.06490 val_loss=0.17323 train_macro_f1=0.9845 val_macro_f1=0.9489

2026-06-11 20:43:33,954 | INFO | Epoch 009/050 train_loss=0.05865 val_loss=0.08530 train_macro_f1=0.9826 val_macro_f1=0.9709

2026-06-11 20:43:35,081 | INFO | Epoch 010/050 train_loss=0.05008 val_loss=0.23828 train_macro_f1=0.9831 val_macro_f1=0.9412

2026-06-11 20:43:35,114 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:43:36,182 | INFO | Epoch 011/050 train_loss=0.02868 val_loss=0.14042 train_macro_f1=0.9925 val_macro_f1=0.9611

2026-06-11 20:43:37,282 | INFO | Epoch 012/050 train_loss=0.05495 val_loss=0.07039 train_macro_f1=0.9878 val_macro_f1=0.9806

2026-06-11 20:43:38,396 | INFO | Epoch 013/050 train_loss=0.03793 val_loss=0.09791 train_macro_f1=0.9884 val_macro_f1=0.9751

2026-06-11 20:43:39,485 | INFO | Epoch 014/050 train_loss=0.03341 val_loss=0.11868 train_macro_f1=0.9938 val_macro_f1=0.9700

2026-06-11 20:43:40,570 | INFO | Epoch 015/050 train_loss=0.01618 val_loss=0.11401 train_macro_f1=0.9968 val_macro_f1=0.9690

2026-06-11 20:43:40,600 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:43:41,666 | INFO | Epoch 016/050 train_loss=0.02106 val_loss=0.12416 train_macro_f1=0.9963 val_macro_f1=0.9695

2026-06-11 20:43:42,756 | INFO | Epoch 017/050 train_loss=0.01479 val_loss=0.09890 train_macro_f1=0.9957 val_macro_f1=0.9741

2026-06-11 20:43:43,843 | INFO | Epoch 018/050 train_loss=0.01761 val_loss=0.02502 train_macro_f1=0.9950 val_macro_f1=0.9885

2026-06-11 20:43:44,966 | INFO | Epoch 019/050 train_loss=0.01837 val_loss=0.13229 train_macro_f1=0.9945 val_macro_f1=0.9719

2026-06-11 20:43:46,044 | INFO | Epoch 020/050 train_loss=0.01199 val_loss=0.04597 train_macro_f1=0.9979 val_macro_f1=0.9885

2026-06-11 20:43:46,073 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:43:47,155 | INFO | Epoch 021/050 train_loss=0.01494 val_loss=0.02044 train_macro_f1=0.9962 val_macro_f1=0.9963

2026-06-11 20:43:48,268 | INFO | Epoch 022/050 train_loss=0.01344 val_loss=0.04542 train_macro_f1=0.9950 val_macro_f1=0.9806

2026-06-11 20:43:49,345 | INFO | Epoch 023/050 train_loss=0.02008 val_loss=0.19266 train_macro_f1=0.9946 val_macro_f1=0.9658

2026-06-11 20:43:50,431 | INFO | Epoch 024/050 train_loss=0.00974 val_loss=0.01927 train_macro_f1=0.9954 val_macro_f1=0.9963

2026-06-11 20:43:51,513 | INFO | Epoch 025/050 train_loss=0.01007 val_loss=0.06872 train_macro_f1=0.9977 val_macro_f1=0.9774

2026-06-11 20:43:51,542 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:43:52,610 | INFO | Epoch 026/050 train_loss=0.00770 val_loss=0.00643 train_macro_f1=0.9985 val_macro_f1=0.9982

2026-06-11 20:43:53,734 | INFO | Epoch 027/050 train_loss=0.00915 val_loss=0.09844 train_macro_f1=0.9977 val_macro_f1=0.9723

2026-06-11 20:43:54,836 | INFO | Epoch 028/050 train_loss=0.00342 val_loss=0.01445 train_macro_f1=0.9991 val_macro_f1=0.9935

2026-06-11 20:43:55,923 | INFO | Epoch 029/050 train_loss=0.00425 val_loss=0.07462 train_macro_f1=0.9982 val_macro_f1=0.9848

2026-06-11 20:43:57,048 | INFO | Epoch 030/050 train_loss=0.00602 val_loss=0.05634 train_macro_f1=0.9989 val_macro_f1=0.9806

2026-06-11 20:43:57,079 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:43:58,183 | INFO | Epoch 031/050 train_loss=0.00100 val_loss=0.04201 train_macro_f1=1.0000 val_macro_f1=0.9903

2026-06-11 20:43:59,304 | INFO | Epoch 032/050 train_loss=0.01300 val_loss=0.16343 train_macro_f1=0.9958 val_macro_f1=0.9691

2026-06-11 20:44:00,397 | INFO | Epoch 033/050 train_loss=0.00792 val_loss=0.29974 train_macro_f1=0.9984 val_macro_f1=0.9564

2026-06-11 20:44:01,482 | INFO | Epoch 034/050 train_loss=0.00131 val_loss=0.05915 train_macro_f1=1.0000 val_macro_f1=0.9793

2026-06-11 20:44:02,567 | INFO | Epoch 035/050 train_loss=0.00036 val_loss=0.09380 train_macro_f1=1.0000 val_macro_f1=0.9816

2026-06-11 20:44:02,598 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:44:03,685 | INFO | Epoch 036/050 train_loss=0.00407 val_loss=0.00985 train_macro_f1=0.9995 val_macro_f1=0.9963

2026-06-11 20:44:04,776 | INFO | Epoch 037/050 train_loss=0.00188 val_loss=0.02949 train_macro_f1=0.9994 val_macro_f1=0.9853

2026-06-11 20:44:05,882 | INFO | Epoch 038/050 train_loss=0.00116 val_loss=0.07455 train_macro_f1=0.9994 val_macro_f1=0.9798

2026-06-11 20:44:06,981 | INFO | Epoch 039/050 train_loss=0.00161 val_loss=0.02655 train_macro_f1=0.9995 val_macro_f1=0.9927

2026-06-11 20:44:08,096 | INFO | Epoch 040/050 train_loss=0.00245 val_loss=0.01306 train_macro_f1=0.9988 val_macro_f1=0.9982

2026-06-11 20:44:08,125 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:44:09,223 | INFO | Epoch 041/050 train_loss=0.00051 val_loss=0.02415 train_macro_f1=1.0000 val_macro_f1=0.9945

2026-06-11 20:44:10,314 | INFO | Epoch 042/050 train_loss=0.00200 val_loss=0.02970 train_macro_f1=0.9995 val_macro_f1=0.9922

2026-06-11 20:44:11,413 | INFO | Epoch 043/050 train_loss=0.00029 val_loss=0.05379 train_macro_f1=1.0000 val_macro_f1=0.9848

2026-06-11 20:44:12,501 | INFO | Epoch 044/050 train_loss=0.00041 val_loss=0.02988 train_macro_f1=1.0000 val_macro_f1=0.9903

2026-06-11 20:44:13,634 | INFO | Epoch 045/050 train_loss=0.00064 val_loss=0.02866 train_macro_f1=1.0000 val_macro_f1=0.9922

2026-06-11 20:44:13,664 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:44:14,727 | INFO | Epoch 046/050 train_loss=0.00028 val_loss=0.02685 train_macro_f1=1.0000 val_macro_f1=0.9927

2026-06-11 20:44:15,814 | INFO | Epoch 047/050 train_loss=0.00016 val_loss=0.01837 train_macro_f1=1.0000 val_macro_f1=0.9963

2026-06-11 20:44:16,919 | INFO | Epoch 048/050 train_loss=0.00134 val_loss=0.03241 train_macro_f1=0.9994 val_macro_f1=0.9927

2026-06-11 20:44:18,030 | INFO | Epoch 049/050 train_loss=0.00033 val_loss=0.03106 train_macro_f1=1.0000 val_macro_f1=0.9890

2026-06-11 20:44:19,174 | INFO | Epoch 050/050 train_loss=0.00136 val_loss=0.01718 train_macro_f1=0.9987 val_macro_f1=0.9963

2026-06-11 20:44:19,202 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_2/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:44:23,792 | INFO | Fold completed strategy=full_finetune fold=2 test_macro_f1=0.9181 duration=59.9s

2026-06-11 20:44:23,794 | INFO | Finished strategy=full_finetune fold=2 status=OK

2026-06-11 20:44:23,816 | INFO | Loaded pretrained full model.

2026-06-11 20:44:23,816 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:44:24,917 | INFO | Epoch 001/050 train_loss=0.54782 val_loss=0.35468 train_macro_f1=0.7675 val_macro_f1=0.8428

2026-06-11 20:44:26,074 | INFO | Epoch 002/050 train_loss=0.32553 val_loss=0.34652 train_macro_f1=0.8896 val_macro_f1=0.8541

2026-06-11 20:44:27,223 | INFO | Epoch 003/050 train_loss=0.21841 val_loss=0.26847 train_macro_f1=0.9337 val_macro_f1=0.8990

2026-06-11 20:44:28,386 | INFO | Epoch 004/050 train_loss=0.16937 val_loss=0.29736 train_macro_f1=0.9490 val_macro_f1=0.8719

2026-06-11 20:44:29,499 | INFO | Epoch 005/050 train_loss=0.15217 val_loss=0.29641 train_macro_f1=0.9500 val_macro_f1=0.8955

2026-06-11 20:44:29,528 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:44:30,619 | INFO | Epoch 006/050 train_loss=0.10096 val_loss=0.09450 train_macro_f1=0.9744 val_macro_f1=0.9681

2026-06-11 20:44:31,803 | INFO | Epoch 007/050 train_loss=0.10069 val_loss=0.11219 train_macro_f1=0.9664 val_macro_f1=0.9719

2026-06-11 20:44:33,006 | INFO | Epoch 008/050 train_loss=0.07145 val_loss=0.09225 train_macro_f1=0.9796 val_macro_f1=0.9733

2026-06-11 20:44:34,192 | INFO | Epoch 009/050 train_loss=0.08379 val_loss=0.05299 train_macro_f1=0.9749 val_macro_f1=0.9845

2026-06-11 20:44:35,355 | INFO | Epoch 010/050 train_loss=0.07313 val_loss=0.19575 train_macro_f1=0.9788 val_macro_f1=0.9344

2026-06-11 20:44:35,385 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:44:36,476 | INFO | Epoch 011/050 train_loss=0.04085 val_loss=0.05535 train_macro_f1=0.9890 val_macro_f1=0.9838

2026-06-11 20:44:37,588 | INFO | Epoch 012/050 train_loss=0.05789 val_loss=0.08109 train_macro_f1=0.9838 val_macro_f1=0.9651

2026-06-11 20:44:38,711 | INFO | Epoch 013/050 train_loss=0.03330 val_loss=0.13457 train_macro_f1=0.9919 val_macro_f1=0.9615

2026-06-11 20:44:39,818 | INFO | Epoch 014/050 train_loss=0.03693 val_loss=0.08280 train_macro_f1=0.9896 val_macro_f1=0.9793

2026-06-11 20:44:40,932 | INFO | Epoch 015/050 train_loss=0.01705 val_loss=0.06013 train_macro_f1=0.9974 val_macro_f1=0.9788

2026-06-11 20:44:40,963 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:44:42,080 | INFO | Epoch 016/050 train_loss=0.01172 val_loss=0.10361 train_macro_f1=0.9971 val_macro_f1=0.9737

2026-06-11 20:44:43,186 | INFO | Epoch 017/050 train_loss=0.02178 val_loss=0.12584 train_macro_f1=0.9936 val_macro_f1=0.9592

2026-06-11 20:44:44,302 | INFO | Epoch 018/050 train_loss=0.01653 val_loss=0.01915 train_macro_f1=0.9938 val_macro_f1=0.9963

2026-06-11 20:44:45,757 | INFO | Epoch 019/050 train_loss=0.01053 val_loss=0.04424 train_macro_f1=0.9976 val_macro_f1=0.9872

2026-06-11 20:44:46,870 | INFO | Epoch 020/050 train_loss=0.01342 val_loss=0.19242 train_macro_f1=0.9967 val_macro_f1=0.9496

2026-06-11 20:44:46,899 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:44:48,028 | INFO | Epoch 021/050 train_loss=0.00397 val_loss=0.07895 train_macro_f1=1.0000 val_macro_f1=0.9756

2026-06-11 20:44:49,142 | INFO | Epoch 022/050 train_loss=0.00434 val_loss=0.04955 train_macro_f1=0.9995 val_macro_f1=0.9853

2026-06-11 20:44:50,264 | INFO | Epoch 023/050 train_loss=0.00590 val_loss=0.04368 train_macro_f1=0.9990 val_macro_f1=0.9885

2026-06-11 20:44:51,386 | INFO | Epoch 024/050 train_loss=0.00466 val_loss=0.01994 train_macro_f1=0.9994 val_macro_f1=0.9963

2026-06-11 20:44:52,499 | INFO | Epoch 025/050 train_loss=0.00302 val_loss=0.06905 train_macro_f1=0.9990 val_macro_f1=0.9784

2026-06-11 20:44:52,537 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:44:53,635 | INFO | Epoch 026/050 train_loss=0.00374 val_loss=0.01848 train_macro_f1=0.9995 val_macro_f1=0.9945

2026-06-11 20:44:54,761 | INFO | Epoch 027/050 train_loss=0.00211 val_loss=0.01072 train_macro_f1=0.9995 val_macro_f1=0.9963

2026-06-11 20:44:55,902 | INFO | Epoch 028/050 train_loss=0.00260 val_loss=0.01895 train_macro_f1=0.9995 val_macro_f1=0.9963

2026-06-11 20:44:57,010 | INFO | Epoch 029/050 train_loss=0.00336 val_loss=0.01807 train_macro_f1=0.9995 val_macro_f1=0.9945

2026-06-11 20:44:58,124 | INFO | Epoch 030/050 train_loss=0.00219 val_loss=0.02025 train_macro_f1=1.0000 val_macro_f1=0.9927

2026-06-11 20:44:58,152 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:44:59,240 | INFO | Epoch 031/050 train_loss=0.00516 val_loss=0.03605 train_macro_f1=0.9991 val_macro_f1=0.9872

2026-06-11 20:45:00,371 | INFO | Epoch 032/050 train_loss=0.00309 val_loss=0.04539 train_macro_f1=0.9995 val_macro_f1=0.9853

2026-06-11 20:45:01,482 | INFO | Epoch 033/050 train_loss=0.00444 val_loss=0.03346 train_macro_f1=0.9984 val_macro_f1=0.9890

2026-06-11 20:45:02,592 | INFO | Epoch 034/050 train_loss=0.00340 val_loss=0.01110 train_macro_f1=0.9991 val_macro_f1=0.9963

2026-06-11 20:45:03,706 | INFO | Epoch 035/050 train_loss=0.00527 val_loss=0.01078 train_macro_f1=0.9983 val_macro_f1=0.9963

2026-06-11 20:45:03,736 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:45:04,828 | INFO | Epoch 036/050 train_loss=0.00369 val_loss=0.02324 train_macro_f1=0.9994 val_macro_f1=0.9945

2026-06-11 20:45:05,945 | INFO | Epoch 037/050 train_loss=0.00383 val_loss=0.02462 train_macro_f1=0.9995 val_macro_f1=0.9927

2026-06-11 20:45:07,055 | INFO | Epoch 038/050 train_loss=0.00263 val_loss=0.04353 train_macro_f1=0.9991 val_macro_f1=0.9890

2026-06-11 20:45:08,193 | INFO | Epoch 039/050 train_loss=0.00159 val_loss=0.02348 train_macro_f1=1.0000 val_macro_f1=0.9927

2026-06-11 20:45:09,296 | INFO | Epoch 040/050 train_loss=0.00167 val_loss=0.03538 train_macro_f1=0.9995 val_macro_f1=0.9909

2026-06-11 20:45:09,325 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:45:10,441 | INFO | Epoch 041/050 train_loss=0.00206 val_loss=0.03082 train_macro_f1=1.0000 val_macro_f1=0.9909

2026-06-11 20:45:11,552 | INFO | Epoch 042/050 train_loss=0.00217 val_loss=0.05554 train_macro_f1=0.9991 val_macro_f1=0.9853

2026-06-11 20:45:12,660 | INFO | Epoch 043/050 train_loss=0.00241 val_loss=0.03042 train_macro_f1=0.9988 val_macro_f1=0.9927

2026-06-11 20:45:13,769 | INFO | Epoch 044/050 train_loss=0.00136 val_loss=0.04685 train_macro_f1=1.0000 val_macro_f1=0.9872

2026-06-11 20:45:14,879 | INFO | Epoch 045/050 train_loss=0.00262 val_loss=0.03223 train_macro_f1=0.9990 val_macro_f1=0.9927

2026-06-11 20:45:14,908 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:45:16,053 | INFO | Epoch 046/050 train_loss=0.00212 val_loss=0.03188 train_macro_f1=0.9995 val_macro_f1=0.9927

2026-06-11 20:45:17,198 | INFO | Epoch 047/050 train_loss=0.00150 val_loss=0.02938 train_macro_f1=1.0000 val_macro_f1=0.9927

2026-06-11 20:45:18,325 | INFO | Epoch 048/050 train_loss=0.00110 val_loss=0.02152 train_macro_f1=1.0000 val_macro_f1=0.9945

2026-06-11 20:45:19,438 | INFO | Epoch 049/050 train_loss=0.00142 val_loss=0.02623 train_macro_f1=1.0000 val_macro_f1=0.9927

2026-06-11 20:45:20,541 | INFO | Epoch 050/050 train_loss=0.00226 val_loss=0.02533 train_macro_f1=0.9990 val_macro_f1=0.9945

2026-06-11 20:45:20,569 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_3/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:45:25,121 | INFO | Fold completed strategy=full_finetune fold=3 test_macro_f1=0.8864 duration=61.3s

2026-06-11 20:45:25,123 | INFO | Finished strategy=full_finetune fold=3 status=OK

2026-06-11 20:45:25,145 | INFO | Loaded pretrained full model.

2026-06-11 20:45:25,146 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:45:26,266 | INFO | Epoch 001/050 train_loss=0.52543 val_loss=0.37659 train_macro_f1=0.7967 val_macro_f1=0.8536

2026-06-11 20:45:27,443 | INFO | Epoch 002/050 train_loss=0.29272 val_loss=0.35872 train_macro_f1=0.9051 val_macro_f1=0.8607

2026-06-11 20:45:28,610 | INFO | Epoch 003/050 train_loss=0.19262 val_loss=0.40859 train_macro_f1=0.9492 val_macro_f1=0.8629

2026-06-11 20:45:29,773 | INFO | Epoch 004/050 train_loss=0.16069 val_loss=0.34344 train_macro_f1=0.9553 val_macro_f1=0.8662

2026-06-11 20:45:30,927 | INFO | Epoch 005/050 train_loss=0.13198 val_loss=0.25900 train_macro_f1=0.9574 val_macro_f1=0.9144

2026-06-11 20:45:30,986 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:45:32,148 | INFO | Epoch 006/050 train_loss=0.08799 val_loss=0.23166 train_macro_f1=0.9785 val_macro_f1=0.9205

2026-06-11 20:45:33,313 | INFO | Epoch 007/050 train_loss=0.10728 val_loss=0.21232 train_macro_f1=0.9690 val_macro_f1=0.9383

2026-06-11 20:45:34,496 | INFO | Epoch 008/050 train_loss=0.08632 val_loss=0.13433 train_macro_f1=0.9759 val_macro_f1=0.9602

2026-06-11 20:45:35,698 | INFO | Epoch 009/050 train_loss=0.05887 val_loss=0.14782 train_macro_f1=0.9864 val_macro_f1=0.9511

2026-06-11 20:45:36,834 | INFO | Epoch 010/050 train_loss=0.04454 val_loss=0.17146 train_macro_f1=0.9888 val_macro_f1=0.9541

2026-06-11 20:45:36,864 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:45:38,014 | INFO | Epoch 011/050 train_loss=0.05260 val_loss=0.06220 train_macro_f1=0.9856 val_macro_f1=0.9872

2026-06-11 20:45:39,189 | INFO | Epoch 012/050 train_loss=0.05793 val_loss=0.15672 train_macro_f1=0.9857 val_macro_f1=0.9546

2026-06-11 20:45:40,347 | INFO | Epoch 013/050 train_loss=0.04182 val_loss=0.08979 train_macro_f1=0.9915 val_macro_f1=0.9732

2026-06-11 20:45:41,502 | INFO | Epoch 014/050 train_loss=0.02940 val_loss=0.05736 train_macro_f1=0.9931 val_macro_f1=0.9835

2026-06-11 20:45:42,670 | INFO | Epoch 015/050 train_loss=0.01448 val_loss=0.02870 train_macro_f1=0.9955 val_macro_f1=0.9945

2026-06-11 20:45:42,731 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:45:43,871 | INFO | Epoch 016/050 train_loss=0.02166 val_loss=0.01946 train_macro_f1=0.9939 val_macro_f1=0.9927

2026-06-11 20:45:45,032 | INFO | Epoch 017/050 train_loss=0.02385 val_loss=0.00658 train_macro_f1=0.9929 val_macro_f1=1.0000

2026-06-11 20:45:46,219 | INFO | Epoch 018/050 train_loss=0.02018 val_loss=0.09017 train_macro_f1=0.9955 val_macro_f1=0.9742

2026-06-11 20:45:47,375 | INFO | Epoch 019/050 train_loss=0.02654 val_loss=0.01410 train_macro_f1=0.9939 val_macro_f1=0.9964

2026-06-11 20:45:48,535 | INFO | Epoch 020/050 train_loss=0.01246 val_loss=0.16575 train_macro_f1=0.9968 val_macro_f1=0.9606

2026-06-11 20:45:48,565 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:45:49,738 | INFO | Epoch 021/050 train_loss=0.01719 val_loss=0.04703 train_macro_f1=0.9925 val_macro_f1=0.9872

2026-06-11 20:45:50,894 | INFO | Epoch 022/050 train_loss=0.01294 val_loss=0.04766 train_macro_f1=0.9972 val_macro_f1=0.9927

2026-06-11 20:45:52,068 | INFO | Epoch 023/050 train_loss=0.01242 val_loss=0.01687 train_macro_f1=0.9968 val_macro_f1=0.9964

2026-06-11 20:45:53,216 | INFO | Epoch 024/050 train_loss=0.00283 val_loss=0.02767 train_macro_f1=1.0000 val_macro_f1=0.9927

2026-06-11 20:45:54,353 | INFO | Epoch 025/050 train_loss=0.00663 val_loss=0.02093 train_macro_f1=0.9985 val_macro_f1=0.9945

2026-06-11 20:45:54,382 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:45:55,501 | INFO | Epoch 026/050 train_loss=0.01104 val_loss=0.01127 train_macro_f1=0.9971 val_macro_f1=0.9982

2026-06-11 20:45:56,668 | INFO | Epoch 027/050 train_loss=0.00344 val_loss=0.01787 train_macro_f1=0.9989 val_macro_f1=0.9964

2026-06-11 20:45:57,810 | INFO | Epoch 028/050 train_loss=0.00772 val_loss=0.01130 train_macro_f1=0.9977 val_macro_f1=0.9982

2026-06-11 20:45:58,947 | INFO | Epoch 029/050 train_loss=0.00487 val_loss=0.01657 train_macro_f1=0.9990 val_macro_f1=0.9964

2026-06-11 20:46:00,116 | INFO | Epoch 030/050 train_loss=0.00238 val_loss=0.00913 train_macro_f1=1.0000 val_macro_f1=0.9964

2026-06-11 20:46:00,151 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:46:01,314 | INFO | Epoch 031/050 train_loss=0.00287 val_loss=0.00968 train_macro_f1=0.9991 val_macro_f1=0.9982

2026-06-11 20:46:02,446 | INFO | Epoch 032/050 train_loss=0.00450 val_loss=0.00376 train_macro_f1=0.9991 val_macro_f1=0.9982

2026-06-11 20:46:03,584 | INFO | Epoch 033/050 train_loss=0.00099 val_loss=0.02518 train_macro_f1=1.0000 val_macro_f1=0.9945

2026-06-11 20:46:04,714 | INFO | Epoch 034/050 train_loss=0.00213 val_loss=0.00772 train_macro_f1=0.9995 val_macro_f1=0.9964

2026-06-11 20:46:05,849 | INFO | Epoch 035/050 train_loss=0.00092 val_loss=0.01409 train_macro_f1=1.0000 val_macro_f1=0.9945

2026-06-11 20:46:05,880 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:46:07,023 | INFO | Epoch 036/050 train_loss=0.00163 val_loss=0.01544 train_macro_f1=0.9995 val_macro_f1=0.9945

2026-06-11 20:46:08,168 | INFO | Epoch 037/050 train_loss=0.00111 val_loss=0.00842 train_macro_f1=1.0000 val_macro_f1=0.9982

2026-06-11 20:46:09,318 | INFO | Epoch 038/050 train_loss=0.00389 val_loss=0.00486 train_macro_f1=0.9990 val_macro_f1=0.9982

2026-06-11 20:46:10,510 | INFO | Epoch 039/050 train_loss=0.00293 val_loss=0.01073 train_macro_f1=0.9995 val_macro_f1=0.9982

2026-06-11 20:46:11,670 | INFO | Epoch 040/050 train_loss=0.00200 val_loss=0.01003 train_macro_f1=0.9995 val_macro_f1=0.9982

2026-06-11 20:46:11,701 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:46:12,853 | INFO | Epoch 041/050 train_loss=0.00042 val_loss=0.02360 train_macro_f1=1.0000 val_macro_f1=0.9945

2026-06-11 20:46:13,999 | INFO | Epoch 042/050 train_loss=0.00117 val_loss=0.01472 train_macro_f1=1.0000 val_macro_f1=0.9964

2026-06-11 20:46:15,146 | INFO | Epoch 043/050 train_loss=0.00053 val_loss=0.00632 train_macro_f1=1.0000 val_macro_f1=0.9982

2026-06-11 20:46:16,306 | INFO | Epoch 044/050 train_loss=0.00113 val_loss=0.00787 train_macro_f1=1.0000 val_macro_f1=0.9982

2026-06-11 20:46:17,488 | INFO | Epoch 045/050 train_loss=0.00119 val_loss=0.01012 train_macro_f1=1.0000 val_macro_f1=0.9982

2026-06-11 20:46:17,517 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:46:18,672 | INFO | Epoch 046/050 train_loss=0.00120 val_loss=0.01368 train_macro_f1=0.9995 val_macro_f1=0.9964

2026-06-11 20:46:19,832 | INFO | Epoch 047/050 train_loss=0.00098 val_loss=0.01380 train_macro_f1=1.0000 val_macro_f1=0.9964

2026-06-11 20:46:20,992 | INFO | Epoch 048/050 train_loss=0.00059 val_loss=0.00717 train_macro_f1=1.0000 val_macro_f1=0.9982

2026-06-11 20:46:22,175 | INFO | Epoch 049/050 train_loss=0.00088 val_loss=0.01035 train_macro_f1=0.9995 val_macro_f1=0.9982

2026-06-11 20:46:23,336 | INFO | Epoch 050/050 train_loss=0.00081 val_loss=0.00814 train_macro_f1=1.0000 val_macro_f1=0.9982

2026-06-11 20:46:23,367 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_4/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:46:28,023 | INFO | Fold completed strategy=full_finetune fold=4 test_macro_f1=0.8374 duration=62.9s

2026-06-11 20:46:28,026 | INFO | Finished strategy=full_finetune fold=4 status=OK

2026-06-11 20:46:28,057 | INFO | Loaded pretrained full model.

2026-06-11 20:46:28,058 | INFO | Parameters trainable=512933 total=512933 ratio=1.0000

2026-06-11 20:46:29,234 | INFO | Epoch 001/050 train_loss=0.50994 val_loss=0.29576 train_macro_f1=0.7999 val_macro_f1=0.8853

2026-06-11 20:46:30,440 | INFO | Epoch 002/050 train_loss=0.29920 val_loss=0.19417 train_macro_f1=0.9016 val_macro_f1=0.9389

2026-06-11 20:46:31,672 | INFO | Epoch 003/050 train_loss=0.20018 val_loss=0.22476 train_macro_f1=0.9422 val_macro_f1=0.9251

2026-06-11 20:46:32,855 | INFO | Epoch 004/050 train_loss=0.13856 val_loss=0.17520 train_macro_f1=0.9654 val_macro_f1=0.9474

2026-06-11 20:46:34,084 | INFO | Epoch 005/050 train_loss=0.10465 val_loss=0.11531 train_macro_f1=0.9772 val_macro_f1=0.9714

2026-06-11 20:46:34,143 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_005.pt

2026-06-11 20:46:35,301 | INFO | Epoch 006/050 train_loss=0.07586 val_loss=0.09357 train_macro_f1=0.9821 val_macro_f1=0.9812

2026-06-11 20:46:36,515 | INFO | Epoch 007/050 train_loss=0.07527 val_loss=0.12844 train_macro_f1=0.9762 val_macro_f1=0.9611

2026-06-11 20:46:37,719 | INFO | Epoch 008/050 train_loss=0.10244 val_loss=0.16366 train_macro_f1=0.9705 val_macro_f1=0.9495

2026-06-11 20:46:38,904 | INFO | Epoch 009/050 train_loss=0.05561 val_loss=0.15813 train_macro_f1=0.9839 val_macro_f1=0.9541

2026-06-11 20:46:40,105 | INFO | Epoch 010/050 train_loss=0.05225 val_loss=0.08421 train_macro_f1=0.9842 val_macro_f1=0.9769

2026-06-11 20:46:40,156 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_010.pt

2026-06-11 20:46:41,333 | INFO | Epoch 011/050 train_loss=0.04038 val_loss=0.06529 train_macro_f1=0.9891 val_macro_f1=0.9801

2026-06-11 20:46:42,558 | INFO | Epoch 012/050 train_loss=0.02794 val_loss=0.30563 train_macro_f1=0.9908 val_macro_f1=0.9170

2026-06-11 20:46:43,731 | INFO | Epoch 013/050 train_loss=0.02503 val_loss=0.03758 train_macro_f1=0.9943 val_macro_f1=0.9898

2026-06-11 20:46:44,927 | INFO | Epoch 014/050 train_loss=0.01173 val_loss=0.04032 train_macro_f1=0.9965 val_macro_f1=0.9940

2026-06-11 20:46:46,115 | INFO | Epoch 015/050 train_loss=0.01998 val_loss=0.06140 train_macro_f1=0.9952 val_macro_f1=0.9830

2026-06-11 20:46:46,144 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_015.pt

2026-06-11 20:46:47,307 | INFO | Epoch 016/050 train_loss=0.01199 val_loss=0.05060 train_macro_f1=0.9964 val_macro_f1=0.9879

2026-06-11 20:46:48,472 | INFO | Epoch 017/050 train_loss=0.01267 val_loss=0.04162 train_macro_f1=0.9986 val_macro_f1=0.9903

2026-06-11 20:46:49,640 | INFO | Epoch 018/050 train_loss=0.01380 val_loss=0.04137 train_macro_f1=0.9968 val_macro_f1=0.9927

2026-06-11 20:46:50,806 | INFO | Epoch 019/050 train_loss=0.01164 val_loss=0.02491 train_macro_f1=0.9966 val_macro_f1=0.9940

2026-06-11 20:46:52,002 | INFO | Epoch 020/050 train_loss=0.02010 val_loss=0.03719 train_macro_f1=0.9941 val_macro_f1=0.9945

2026-06-11 20:46:52,048 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_020.pt

2026-06-11 20:46:53,214 | INFO | Epoch 021/050 train_loss=0.00806 val_loss=0.02326 train_macro_f1=0.9986 val_macro_f1=0.9958

2026-06-11 20:46:54,456 | INFO | Epoch 022/050 train_loss=0.01301 val_loss=0.03486 train_macro_f1=0.9962 val_macro_f1=0.9940

2026-06-11 20:46:55,618 | INFO | Epoch 023/050 train_loss=0.02023 val_loss=0.02918 train_macro_f1=0.9942 val_macro_f1=0.9940

2026-06-11 20:46:56,796 | INFO | Epoch 024/050 train_loss=0.00598 val_loss=0.02431 train_macro_f1=0.9990 val_macro_f1=0.9982

2026-06-11 20:46:58,041 | INFO | Epoch 025/050 train_loss=0.01711 val_loss=0.01829 train_macro_f1=0.9954 val_macro_f1=0.9958

2026-06-11 20:46:58,087 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_025.pt

2026-06-11 20:46:59,256 | INFO | Epoch 026/050 train_loss=0.00580 val_loss=0.02849 train_macro_f1=0.9985 val_macro_f1=0.9945

2026-06-11 20:47:00,437 | INFO | Epoch 027/050 train_loss=0.00616 val_loss=0.02659 train_macro_f1=0.9979 val_macro_f1=0.9958

2026-06-11 20:47:01,628 | INFO | Epoch 028/050 train_loss=0.00509 val_loss=0.03406 train_macro_f1=0.9990 val_macro_f1=0.9940

2026-06-11 20:47:02,822 | INFO | Epoch 029/050 train_loss=0.00783 val_loss=0.04193 train_macro_f1=0.9949 val_macro_f1=0.9934

2026-06-11 20:47:04,002 | INFO | Epoch 030/050 train_loss=0.01019 val_loss=0.04068 train_macro_f1=0.9986 val_macro_f1=0.9903

2026-06-11 20:47:04,034 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_030.pt

2026-06-11 20:47:05,197 | INFO | Epoch 031/050 train_loss=0.00406 val_loss=0.03336 train_macro_f1=0.9985 val_macro_f1=0.9945

2026-06-11 20:47:06,394 | INFO | Epoch 032/050 train_loss=0.00494 val_loss=0.04053 train_macro_f1=0.9991 val_macro_f1=0.9927

2026-06-11 20:47:07,601 | INFO | Epoch 033/050 train_loss=0.00440 val_loss=0.03374 train_macro_f1=0.9991 val_macro_f1=0.9927

2026-06-11 20:47:08,788 | INFO | Epoch 034/050 train_loss=0.00743 val_loss=0.02943 train_macro_f1=0.9986 val_macro_f1=0.9921

2026-06-11 20:47:09,987 | INFO | Epoch 035/050 train_loss=0.00321 val_loss=0.02238 train_macro_f1=0.9983 val_macro_f1=0.9964

2026-06-11 20:47:10,017 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_035.pt

2026-06-11 20:47:11,181 | INFO | Epoch 036/050 train_loss=0.00636 val_loss=0.01838 train_macro_f1=0.9979 val_macro_f1=0.9964

2026-06-11 20:47:12,362 | INFO | Epoch 037/050 train_loss=0.00217 val_loss=0.04207 train_macro_f1=0.9995 val_macro_f1=0.9909

2026-06-11 20:47:13,539 | INFO | Epoch 038/050 train_loss=0.00609 val_loss=0.02110 train_macro_f1=0.9990 val_macro_f1=0.9982

2026-06-11 20:47:14,753 | INFO | Epoch 039/050 train_loss=0.00101 val_loss=0.03314 train_macro_f1=1.0000 val_macro_f1=0.9945

2026-06-11 20:47:15,934 | INFO | Epoch 040/050 train_loss=0.00426 val_loss=0.02565 train_macro_f1=0.9991 val_macro_f1=0.9958

2026-06-11 20:47:15,963 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_040.pt

2026-06-11 20:47:17,146 | INFO | Epoch 041/050 train_loss=0.00114 val_loss=0.02459 train_macro_f1=1.0000 val_macro_f1=0.9982

2026-06-11 20:47:18,317 | INFO | Epoch 042/050 train_loss=0.00716 val_loss=0.02722 train_macro_f1=0.9989 val_macro_f1=0.9945

2026-06-11 20:47:19,513 | INFO | Epoch 043/050 train_loss=0.00154 val_loss=0.02303 train_macro_f1=0.9994 val_macro_f1=0.9964

2026-06-11 20:47:20,709 | INFO | Epoch 044/050 train_loss=0.00088 val_loss=0.02526 train_macro_f1=1.0000 val_macro_f1=0.9964

2026-06-11 20:47:21,900 | INFO | Epoch 045/050 train_loss=0.00288 val_loss=0.02780 train_macro_f1=0.9991 val_macro_f1=0.9958

2026-06-11 20:47:21,934 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_045.pt

2026-06-11 20:47:23,102 | INFO | Epoch 046/050 train_loss=0.00234 val_loss=0.02567 train_macro_f1=0.9995 val_macro_f1=0.9964

2026-06-11 20:47:24,294 | INFO | Epoch 047/050 train_loss=0.00195 val_loss=0.02718 train_macro_f1=0.9995 val_macro_f1=0.9945

2026-06-11 20:47:25,474 | INFO | Epoch 048/050 train_loss=0.00186 val_loss=0.02933 train_macro_f1=1.0000 val_macro_f1=0.9945

2026-06-11 20:47:26,652 | INFO | Epoch 049/050 train_loss=0.00081 val_loss=0.02692 train_macro_f1=1.0000 val_macro_f1=0.9964

2026-06-11 20:47:27,869 | INFO | Epoch 050/050 train_loss=0.00058 val_loss=0.02872 train_macro_f1=1.0000 val_macro_f1=0.9945

2026-06-11 20:47:27,900 | INFO | Saved periodic 5-epoch checkpoint: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227/transfer_strategies/full_finetune/fold_5/checkpoints/per_5fold/epoch_050.pt

2026-06-11 20:47:32,608 | INFO | Fold completed strategy=full_finetune fold=5 test_macro_f1=0.9074 duration=64.6s

2026-06-11 20:47:32,611 | INFO | Finished strategy=full_finetune fold=5 status=OK

## 12. Aggregate Results and Plots

In [12]:
all_fold_metrics=pd.read_csv(AGG_DIR/'all_fold_metrics.csv')
ok=all_fold_metrics[all_fold_metrics['status'].eq('OK')].copy()
if ok.empty:
    raise RuntimeError('No successful fold results to aggregate.')

f1_detail_cols = [f'{split}_f1_{label}' for split in ['train','val','test'] for label in MAIN_LABEL_DISPLAY]
per_class_extra_cols = [f'test_{metric}_{label}' for metric in ['sensitivity','specificity','auc'] for label in MAIN_LABEL_DISPLAY]

summary_metrics = [
    'test_main_macro_f1', 'test_main_micro_f1', 'test_main_weighted_f1',
    'test_accuracy', 'test_balanced_accuracy', 'test_macro_auc', 'test_loss',
    *[f'test_f1_{label}' for label in MAIN_LABEL_DISPLAY],
    *per_class_extra_cols,
]
summary_metrics = [col for col in summary_metrics if col in ok.columns]

avg = ok.groupby('strategy').agg(
    avg_test_main_macro_f1=('test_main_macro_f1','mean'),
    std_test_main_macro_f1=('test_main_macro_f1','std'),
    avg_test_main_micro_f1=('test_main_micro_f1','mean'),
    std_test_main_micro_f1=('test_main_micro_f1','std'),
    avg_test_main_weighted_f1=('test_main_weighted_f1','mean'),
    std_test_main_weighted_f1=('test_main_weighted_f1','std'),
    avg_test_accuracy=('test_accuracy','mean'),
    std_test_accuracy=('test_accuracy','std'),
    avg_test_balanced_accuracy=('test_balanced_accuracy','mean'),
    std_test_balanced_accuracy=('test_balanced_accuracy','std'),
    avg_test_macro_auc=('test_macro_auc','mean'),
    std_test_macro_auc=('test_macro_auc','std'),
    avg_test_loss=('test_loss','mean'),
    std_test_loss=('test_loss','std'),
).reset_index()
best_by_strategy=ok.sort_values('test_main_macro_f1',ascending=False).groupby('strategy').first().reset_index()[['strategy','fold']].rename(columns={'fold':'best_fold_for_strategy'})
avg=avg.merge(best_by_strategy,on='strategy',how='left').sort_values('avg_test_main_macro_f1',ascending=False)

mean_std_rows=[]
for strategy, part in ok.groupby('strategy'):
    row={'strategy':strategy,'n_folds':int(len(part))}
    for metric in summary_metrics:
        mean=float(part[metric].mean())
        std=float(part[metric].std(ddof=1)) if len(part)>1 else 0.0
        row[f'{metric}_mean']=mean
        row[f'{metric}_std']=std
        row[f'{metric}_mean_std']=f'{mean:.4f} ± {std:.4f}'
    mean_std_rows.append(row)
mean_std=pd.DataFrame(mean_std_rows).sort_values('test_main_macro_f1_mean',ascending=False)

rank=ok.sort_values('test_main_macro_f1',ascending=False).reset_index(drop=True)
rank.insert(0,'rank',np.arange(1,len(rank)+1))
per_class_cols=[c for c in ['strategy','fold',*f1_detail_cols,*per_class_extra_cols] if c in all_fold_metrics.columns]
detailed_cols=[c for c in ['strategy','fold','train_main_macro_f1','val_main_macro_f1','test_main_macro_f1','test_main_micro_f1','test_main_weighted_f1','test_accuracy','test_balanced_accuracy','test_macro_auc','test_loss','trainable_params','total_params','trainable_ratio','status','checkpoint_path','output_dir',*f1_detail_cols,*per_class_extra_cols] if c in all_fold_metrics.columns]

# Save in both aggregate_results and root metrics for paper/table access.
for out_dir in [AGG_DIR, ROOT_METRICS_DIR]:
    avg.to_csv(out_dir/'average_metrics_by_strategy.csv',index=False)
    mean_std.to_csv(out_dir/'cross_validation_mean_std_by_strategy.csv',index=False)
    rank.to_csv(out_dir/'best_fold_ranking.csv',index=False)
    all_fold_metrics[detailed_cols].to_csv(out_dir/'detailed_fold_metrics.csv',index=False)
    all_fold_metrics[per_class_cols].to_csv(out_dir/'per_class_f1_by_strategy_fold.csv',index=False)

with pd.ExcelWriter(ROOT_METRICS_DIR/'alpanet_transfer_summary.xlsx') as writer:
    avg.to_excel(writer,sheet_name='avg_per_strategy',index=False)
    mean_std.to_excel(writer,sheet_name='mean_std_per_strategy',index=False)
    rank.to_excel(writer,sheet_name='best_fold_ranking',index=False)
    all_fold_metrics[detailed_cols].to_excel(writer,sheet_name='detailed_per_strategy_fold',index=False)
with pd.ExcelWriter(AGG_DIR/'alpanet_transfer_summary.xlsx') as writer:
    avg.to_excel(writer,sheet_name='avg_per_strategy',index=False)
    mean_std.to_excel(writer,sheet_name='mean_std_per_strategy',index=False)
    rank.to_excel(writer,sheet_name='best_fold_ranking',index=False)
    all_fold_metrics[detailed_cols].to_excel(writer,sheet_name='detailed_per_strategy_fold',index=False)

rank['strategy_fold']=rank['strategy']+'_fold_'+rank['fold'].astype(str)
plt.figure(figsize=(16,6)); sns.barplot(data=rank,x='strategy_fold',y='test_main_macro_f1',color='#d55e00'); plt.xticks(rotation=60,ha='right'); plt.title('All Strategy-Fold Test Macro-F1 Ranking'); plt.tight_layout(); plt.savefig(PLOTS_DIR/'all_strategy_fold_test_macro_f1_ranking.png',dpi=400,bbox_inches='tight'); plt.close()
plt.figure(figsize=(10,max(6,0.35*len(rank)))); sns.barplot(data=rank,y='strategy_fold',x='test_main_macro_f1',color='#d55e00'); plt.title('All Strategy-Fold Test Macro-F1 Ranking'); plt.tight_layout(); plt.savefig(PLOTS_DIR/'all_strategy_fold_test_macro_f1_ranking_horizontal.png',dpi=400,bbox_inches='tight'); plt.close()
plt.figure(figsize=(9,6)); sns.barplot(data=avg,x='strategy',y='avg_test_main_macro_f1',color='#d55e00'); plt.xticks(rotation=20); plt.title('Average Test Macro-F1 by Strategy'); plt.tight_layout(); plt.savefig(PLOTS_DIR/'avg_test_macro_f1_by_strategy.png',dpi=400,bbox_inches='tight'); plt.close()
plt.figure(figsize=(9,6)); sns.boxplot(data=ok,x='strategy',y='test_main_macro_f1',color='#f6ad55'); sns.stripplot(data=ok,x='strategy',y='test_main_macro_f1',color='black',alpha=.65); plt.xticks(rotation=20); plt.title('Foldwise Test Macro-F1 by Strategy'); plt.tight_layout(); plt.savefig(PLOTS_DIR/'foldwise_test_macro_f1_boxplot_by_strategy.png',dpi=400,bbox_inches='tight'); plt.close()
display(avg); display(mean_std); display(rank.head(10))
RUN_FINISHED_AT=datetime.now(); RUN_DURATION_SECONDS=time.time()-RUN_START_TIME
global_logger.info('Run finished at: %s', RUN_FINISHED_AT.strftime('%Y-%m-%d %H:%M:%S'))
global_logger.info('Total duration %.2f seconds', RUN_DURATION_SECONDS)
print('Notebook complete. Output:', OUTPUT_DIR)

,strategy,avg_test_main_macro_f1,std_test_main_macro_f1,avg_test_main_micro_f1,std_test_main_micro_f1,avg_test_main_weighted_f1,std_test_main_weighted_f1,avg_test_accuracy,std_test_accuracy,avg_test_balanced_accuracy,std_test_balanced_accuracy,avg_test_macro_auc,std_test_macro_auc,avg_test_loss,std_test_loss,best_fold_for_strategy
3,partial_finetune,0.878945,0.030881,0.873347,0.032295,0.872709,0.031740,0.873347,0.032295,0.869353,0.035797,0.980149,0.007008,0.435719,0.114978,2
1,full_finetune,0.874586,0.042088,0.878958,0.033997,0.877543,0.035540,0.878958,0.033997,0.866868,0.049535,0.985969,0.004564,0.414004,0.069521,2
2,no_pretrain,0.866505,0.063330,0.865331,0.052725,0.865678,0.053094,0.865331,0.052725,0.861610,0.069540,0.973993,0.008048,0.557973,0.164656,5
0,frozen_backbone,0.709164,0.040431,0.758717,0.018014,0.739518,0.028443,0.758717,0.018014,0.703531,0.031593,0.962713,0.001189,0.558541,0.032375,2

,strategy,n_folds,test_main_macro_f1_mean,test_main_macro_f1_std,test_main_macro_f1_mean_std,test_main_micro_f1_mean,test_main_micro_f1_std,test_main_micro_f1_mean_std,test_main_weighted_f1_mean,test_main_weighted_f1_std,...,test_auc_NORM_mean_std,test_auc_AMI_mean,test_auc_AMI_std,test_auc_AMI_mean_std,test_auc_IMI_mean,test_auc_IMI_std,test_auc_IMI_mean_std,test_auc_LMI_mean,test_auc_LMI_std,test_auc_LMI_mean_std
3,partial_finetune,5,0.878945,0.030881,0.8789 ± 0.0309,0.873347,0.032295,0.8733 ± 0.0323,0.872709,0.031740,...,0.9910 ± 0.0053,0.973227,0.014810,0.9732 ± 0.0148,0.956339,0.013310,0.9563 ± 0.0133,0.999983,0.000026,1.0000 ± 0.0000
1,full_finetune,5,0.874586,0.042088,0.8746 ± 0.0421,0.878958,0.033997,0.8790 ± 0.0340,0.877543,0.035540,...,0.9937 ± 0.0050,0.976186,0.006482,0.9762 ± 0.0065,0.974120,0.009072,0.9741 ± 0.0091,0.999832,0.000232,0.9998 ± 0.0002
2,no_pretrain,5,0.866505,0.063330,0.8665 ± 0.0633,0.865331,0.052725,0.8653 ± 0.0527,0.865678,0.053094,...,0.9975 ± 0.0021,0.941981,0.020511,0.9420 ± 0.0205,0.956482,0.019940,0.9565 ± 0.0199,0.999988,0.000026,1.0000 ± 0.0000
0,frozen_backbone,5,0.709164,0.040431,0.7092 ± 0.0404,0.758717,0.018014,0.7587 ± 0.0180,0.739518,0.028443,...,0.9570 ± 0.0057,0.973027,0.001588,0.9730 ± 0.0016,0.920914,0.005939,0.9209 ± 0.0059,0.999913,0.000130,0.9999 ± 0.0001

,rank,strategy,fold,status,error,train_main_macro_f1,val_main_macro_f1,test_main_macro_f1,test_main_micro_f1,test_main_weighted_f1,...,test_sensitivity_IMI,test_specificity_IMI,test_auc_IMI,train_f1_LMI,val_f1_LMI,test_f1_LMI,test_sensitivity_LMI,test_specificity_LMI,test_auc_LMI,strategy_fold
0,1,no_pretrain,5,OK,NaN,0.998633,0.990868,0.921050,0.917836,0.916537,...,0.961957,0.892063,0.982574,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,no_pretrain_fold_5
1,2,full_finetune,2,OK,NaN,0.998747,0.998176,0.918105,0.915832,0.915877,...,0.869565,0.955556,0.972257,0.995984,1.000000,1.000000,1.000000,1.000000,1.000000,full_finetune_fold_2
2,3,partial_finetune,2,OK,NaN,0.997586,0.985613,0.908475,0.907816,0.906888,...,0.940217,0.898413,0.977312,1.000000,1.000000,0.949367,0.903614,1.000000,0.999971,partial_finetune_fold_2
3,4,full_finetune,5,OK,NaN,1.000000,0.998179,0.907363,0.905812,0.905142,...,0.929348,0.895238,0.986111,1.000000,1.000000,0.994012,1.000000,0.997596,1.000000,full_finetune_fold_5
4,5,partial_finetune,3,OK,NaN,0.995419,1.000000,0.900986,0.895792,0.895198,...,0.864130,0.920635,0.960455,0.995984,1.000000,0.981595,0.963855,1.000000,1.000000,partial_finetune_fold_3
5,6,no_pretrain,4,OK,NaN,0.998790,0.998179,0.893742,0.887776,0.889710,...,0.815217,0.936508,0.926691,0.995984,1.000000,0.987805,0.975904,1.000000,1.000000,no_pretrain_fold_4
6,7,full_finetune,3,OK,NaN,0.998952,0.996350,0.886403,0.885772,0.885569,...,0.891304,0.904762,0.964044,1.000000,1.000000,0.957055,0.939759,0.995192,0.999623,full_finetune_fold_3
7,8,no_pretrain,3,OK,NaN,0.998292,1.000000,0.885645,0.877756,0.877116,...,0.842391,0.898413,0.955305,0.995984,1.000000,1.000000,1.000000,1.000000,1.000000,no_pretrain_fold_3
8,9,partial_finetune,4,OK,NaN,0.999407,1.000000,0.885563,0.877756,0.876435,...,0.842391,0.901587,0.951536,1.000000,1.000000,0.993939,0.987952,1.000000,1.000000,partial_finetune_fold_4
9,10,no_pretrain,1,OK,NaN,0.999089,0.993207,0.874639,0.865731,0.868634,...,0.809783,0.907937,0.956815,1.000000,0.984127,0.994012,1.000000,0.997596,1.000000,no_pretrain_fold_1

2026-06-11 20:47:34,136 | INFO | Run finished at: 2026-06-11 20:47:34

2026-06-11 20:47:34,137 | INFO | Total duration 906.27 seconds

Notebook complete. Output: /home/nugee/code-program/code-thesis/hibah/myocardial-infarction-localization/outputs/5_alpanet_finetune_no_attention/20260611_203227